Afsaneh/wallet switcher
deriv-com/e2e-deriv-app pull request #103
Opened 2024-02-26 04:16 UTC by afsaneh-rezaeinejad-deriv

2024-02-26 09:45 UTC, abuzar-deriv requested changes

2024-02-26 09:45 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/cashier/addcryptoWallet.cy.js
> +        cy.wait(3000)
Do we need this wait? Can it use dynamic wait to wait for some element instead?

2024-02-26 09:45 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/cashier/addcryptoWallet.cy.js
> +          cy.get('[data-testid="dt-wallets-add-more"]').within(()=>{
Since it's using data test id, can it use findByTestId() instead?

2024-02-26 09:45 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/cashier/addcryptoWallet.cy.js
> +        cy.findByTestId('dt-wallets-add-more').scrollIntoView()
Scrolling twice to the same element. Is this expected?

2024-02-26 09:45 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/cashier/addcryptoWallet.cy.js
> +        for (let j = buttoncount; i>j; j++){
I believe this loop will never be executed since i = j for the first run

2024-02-26 11:25 UTC, markodonnell-deriv reviewed
Good spots by Abuzar. Nothing more to add.

2024-02-27 02:31 UTC, abuzar-deriv commented
Looks good

2024-02-27 02:31 UTC, abuzar-deriv approved these changes

2024-02-27 12:16 UTC, markodonnell-deriv approved these changes
Looks good

2024-03-01 03:42 UTC, meeyun-deriv approved these changes
LGTM

2024-03-01 03:42 UTC, merged