usman/Edit Payment Methods in P2P - Responsive
deriv-com/e2e-deriv-app pull request #106
Opened 2024-02-26 13:20 UTC by usman-deriv

## Description
This pull request is for automation for updating already existing payment methods for P2P in responsive mode. 

### Implementations
- Improved readability by using descriptive variable names.
- Optimized code structure. Used functions to improve code organization and reusability. 
- Regardless of payment methods saved in the user's profile, the code is designed to handle all payment methods. i.e. Bank Transfers, E-wallets, and Others. 

### ClickUp Card
[Create Cypress test QATEST-2831 My Profile page - Edit Payment Method](https://app.clickup.com/t/20696747/P2PS-2449)

2024-02-26 13:45 UTC, markodonnell-deriv requested changes
Good first test. 
I notice there aren't any testing library commands in this test. If you're finding it difficult to identify them, use the Playwright Locator Generator as per the e2e docs: https://wikijs.deriv.cloud/en/Quality-Assurance/e2e-test-automation

2024-02-26 13:45 UTC, markodonnell-deriv commented on cypress/e2e/wip/P2P/editPaymentMethods.cy.js
> +            cy.wait(2000)
Is this wait necessary, we try and avoid these in Cypress as waits are built in to functions such as click and should?

2024-02-26 14:08 UTC, usman-deriv commented on cypress/e2e/wip/P2P/editPaymentMethods.cy.js
> +            cy.wait(2000)
This function checks and dynamically closes notifications, regardless of their number (of notifications). In **responsive**, the notifications come one by one and do not list down as they list on the full-screen web. 

When 1 notification is closed, the function is called again recursively to check for the next notification (if exists), as the first one is still closing, the cypress gets the objects of the first one as it still exists (the notification fades and closes slowly). The wait is just to wait for the notification to get removed from the dom.

I have tried to run tests without using wait but it then tries to get the 'x' button for the already closed notification and it fails there, hence this adequate wait is necessary.

2024-02-27 06:32 UTC, usman-deriv commented on cypress/e2e/wip/P2P/editPaymentMethods.cy.js
> +            cy.wait(2000)
[Update] - This wait command has been removed after debugging.

2024-02-27 08:26 UTC, abuzar-deriv commented on cypress/e2e/wip/P2P/editPaymentMethods.cy.js
> +        if (notification && notification != undefined && notification != null) {
Won't this work with just `if(notification)`?

2024-02-27 08:48 UTC, usman-deriv commented on cypress/e2e/wip/P2P/editPaymentMethods.cy.js
> +        if (notification && notification != undefined && notification != null) {
This has been updated, thank you.

2024-02-27 08:57 UTC, abuzar-deriv commented on cypress/e2e/wip/P2P/editPaymentMethods.cy.js
> +    it('should be able to edit the existing payment methods - responsive', () => {
Sorry 😅 Just one more thing. Can you please capitalize the start of this sentence
<img width="1042" alt="image" src="https://github.com/deriv-com/e2e-deriv-app/assets/132635598/53e96039-b6a3-4daa-a695-cffd71fee1a9">

2024-02-27 09:01 UTC, usman-deriv commented on cypress/e2e/wip/P2P/editPaymentMethods.cy.js
> +    it('should be able to edit the existing payment methods - responsive', () => {
This is done and thank you! :)

2024-02-27 09:13 UTC, abuzar-deriv approved these changes
Looks good.

2024-02-27 12:12 UTC, markodonnell-deriv requested changes
Good use of testing library now but please remove semi-colon as per coding standards in this doc: https://wikijs.deriv.cloud/en/Quality-Assurance/e2e-test-automation

2024-02-27 12:12 UTC, markodonnell-deriv commented on cypress/e2e/wip/P2P/editPaymentMethods.cy.js
> +            notification = null;
remove ;

2024-02-27 12:12 UTC, markodonnell-deriv commented on cypress/e2e/wip/P2P/editPaymentMethods.cy.js
> +    let result = '';
remove ;

2024-02-27 16:28 UTC, bilalmajid-deriv approved these changes
LGTM

2024-02-27 17:05 UTC, markodonnell-deriv approved these changes
Looks good

2024-02-28 03:03 UTC, meeyun-deriv approved these changes
LGTM

2024-02-28 03:04 UTC, merged