IDV POI submission verified scenario
deriv-com/e2e-deriv-app pull request #109
Opened 2024-02-27 10:42 UTC by deborah-deriv

## IDV POI submission verified scenario
This PR contains the tests for the POI IDV verified scenario.

2024-02-27 11:08 UTC, markodonnell-deriv requested changes
some comments that will make more sense if you refer to the e2e docs: https://wikijs.deriv.cloud/en/Quality-Assurance/e2e-test-automation and training video: see #need_help_cypress bookmark.

2024-02-27 11:08 UTC, markodonnell-deriv commented on cypress/support/e2e.js
> +
Remove line

2024-02-27 11:08 UTC, markodonnell-deriv commented on cypress/e2e/wip/KYC/idvPoiVerified.cy.js
> +        cy.get('input[name="document_number"]').type("12760978")
I don't see any testing library commands here. Please refer to the Playwright Generator documentation and watch the training video from min 12 (attached to #need_help_cypress). I've given Usman the same info, if you'd like to buddy on this?

2024-02-27 11:08 UTC, markodonnell-deriv commented on cypress/cypress/support/commands.js
> +// ***********************************************
Please remove comments as this looks like training code.

2024-02-27 11:08 UTC, markodonnell-deriv commented on cypress/cypress/fixtures/example.json
> +{
is this training code?

2024-02-27 14:12 UTC, deborah-deriv commented on cypress/cypress/fixtures/example.json
> +{
I found it by the time i branched out from master

2024-02-27 14:28 UTC, deborah-deriv commented on cypress/cypress/support/commands.js
> +// ***********************************************
Removed

2024-02-27 16:02 UTC, bilalmajid-deriv commented on cypress/cypress/fixtures/example.json
> +{
@deborah-deriv 

This usually occurs when you run 
```
npx cypress open || npx cypress run
```
after navigating into the original cypress folder instead of the root folder

Your root folder location is where the package.json or cypress.config.js is present 
if you run the command from there cypress will not generate new sample code nor ask you to setup sample code. Thanks

<img width="309" alt="Screenshot 2024-02-27 at 23 54 17" src="https://github.com/deriv-com/e2e-deriv-app/assets/155507124/2c450af6-fbb7-4c0e-963b-667e7efde87f">

2024-02-28 07:09 UTC, deborah-deriv commented on cypress/support/e2e.js
> +
This is done

2024-02-28 07:15 UTC, deborah-deriv commented on cypress/cypress/fixtures/example.json
> +{
Thanks @bilalmajid-deriv i have removed the nested cypress folder which contains that fixtures folder containing example.json file

2024-02-29 12:47 UTC, deborah-deriv commented on cypress/support/commands.js
> +  cy.get('button.notification__close-button').click();
This is a way of closing two notifications which obscure the country selector input.

2024-02-29 12:48 UTC, deborah-deriv commented on cypress/support/commands.js
> +  cy.get('button.notification__close-button').click();
I tried to apply testing library functions but there were throwing an errors

2024-03-01 03:07 UTC, bilalmajid-deriv commented on cypress/support/commands.js
> +  cy.get('button.notification__close-button').click();
@usman-deriv  has dealt with the notification in the test for p2p could take reference from that to deal with the notifications.

Cypress itself does not allow conditional testing but there is a work around which is very commonly used using the cy.document() we can use jquery to get an element and check if the element exists or not  and then perform a certain action if the condition passes, this is what I have been suggesting to other team members but it comes with one catch that this way does not have retry ability in it so I think for that @abuzar-deriv has shared something in the knowledge base which is attached in the #need_help_cypress channel for retry ability. We can use that approach and tweek it a little bit to make sure the notifications  are closed one by one.

Apart from this @abuzar-deriv what we could do is also make a common custom command or function which every one could use to try to get an element which might exist in the DOM and if that element is not found then instead of failing the test it should continue with the remaining test something like cy.c_getWithoutFailiure. what do you say?

2024-03-01 03:08 UTC, bilalmajid-deriv commented
@usman-deriv  has dealt with the notification in the test for p2p could take reference from that to deal with the notifications.

Cypress itself does not allow conditional testing but there is a work around which is very commonly used using the cy.document() we can use jquery to get an element and check if the element exists or not  and then perform a certain action if the condition passes, this is what I have been suggesting to other team members but it comes with one catch that this way does not have retry ability in it so I think for that @abuzar-deriv has shared something in the knowledge base which is attached in the #need_help_cypress channel for retry ability. We can use that approach and tweek it a little bit to make sure the notifications  are closed one by one.

Apart from this @abuzar-deriv what we could do is also make a common custom command or function which every one could use to try to get an element which might exist in the DOM and if that element is not found then instead of failing the test it should continue with the remaining test something like cy.c_getWithoutFailiure. what do you say?

2024-03-01 03:39 UTC, abuzar-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("navigate_to_poi_desktop", (country) => {
Command name should be prefixed by "c_" and should be in camel case to maintain consistency 🙏 
<img width="892" alt="image" src="https://github.com/deriv-com/e2e-deriv-app/assets/132635598/4e32c4a9-9fbc-4a8d-88e8-17c77056b851">

2024-03-01 03:40 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.c_visitResponsive("/account/proof-of-identity", "small")
Same here for command name. Please prefix with 'c_' and update to camel case.

2024-03-01 03:40 UTC, abuzar-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("navigate_to_poi_responsive", (country) => {
Same here for command name. Please prefix with 'c_' and update to camel case.

2024-03-01 03:44 UTC, abuzar-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("fill_date", (year, month, day) => {
Same as above for this command name

2024-03-01 03:51 UTC, abuzar-deriv commented
@deborah-deriv , for your test it also depends on your use case. If you don't necessarily need to test the notification, then you can use {force:true} inside you type command. This should help in typing even if the element is covered by notification. There's this existing command as well which seems to be closing the notifications. You can try this as well. Just remove the explicit wait please. 
<img width="512" alt="image" src="https://github.com/deriv-com/e2e-deriv-app/assets/132635598/3034d2d8-a718-4b6d-bbb6-b524926635ff">

2024-03-04 08:21 UTC, deborah-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("navigate_to_poi_desktop", (country) => {
This is fixed

2024-03-04 08:21 UTC, deborah-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("fill_date", (year, month, day) => {
This is fixed

2024-03-04 08:33 UTC, deborah-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("navigate_to_poi_responsive", (country) => {
this is updated

2024-03-04 09:59 UTC, abuzar-deriv requested changes
Is the package lock change intentional?

2024-03-04 09:59 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.get('select[name="country_input"]').select(country)
Can be replaced with cy.findByRole('textbox', {  name: 'Country'}) or cy.findByLabelText("Country").

2024-03-04 09:59 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.get('input[name="date_of_birth"]').click()
Can be replaced with cy.findByTestId("date_of_birth")

2024-03-04 09:59 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.get(`span[data-year="${year}"]`).click()
Can be replaced with cy.findByText("${year}").click()

2024-03-04 09:59 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.get(`span[data-month="${month - 1}"]`).click()
Can be replaced with cy.findByText("${month-1}").click()

2024-03-04 09:59 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.get(`span[data-date="2000-09-${day}"]`).click()
1. Can be replaced with cy.findByText("${day}").click()
2. Why are you hardcoding year and month if using user input above?

2024-03-04 09:59 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.get('select[name="country_input"]').select(country)
Can you refactor line 708 to 710 as well please although it's not your code? (Can do in another PR as well). It can be refactored to `cy.findByLabelText("Country").type(`${country}`);
  cy.findByText(`${country}`).click()`

2024-03-04 10:02 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/idvPoiVerified.cy.js
> +        cy.get('select[name="document_type"]').select('Passport');
Can be replaced with cy.findByLabelText("Choose the document type").select('Passport')

2024-03-04 10:03 UTC, abuzar-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("fill_date", (year, month, day) => {
Sorry, but name needs to be "c_fillDate" :)

2024-03-04 10:04 UTC, abuzar-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("c_navigate_to_poi_desktop", (country) => {
Please update to "c_navigateToPOIDesktop"

2024-03-04 10:04 UTC, abuzar-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("c_navigate_to_poi_responsive", (country) => {
Please update to "c_navigateToPOIResponsive"

2024-03-04 10:06 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.close_notification_banner();
Can you please update the command name in the command.js file to "c_CloseNotificationBanner"?

2024-03-04 10:18 UTC, bilalmajid-deriv commented on cypress/support/commands.js
> +  cy.close_notification_banner();
c_closeNotificationBanner to follow up with camel case

and @abuzar-deriv  would this not be a duplicate of what is being done by Usman in P2P tests?

2024-03-04 10:25 UTC, bilalmajid-deriv requested changes

2024-03-04 10:25 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/idvPoiVerified.cy.js
> +});
@deborah-deriv could you please remove all the semicolons as well, thanks

2024-03-04 10:31 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.close_notification_banner();
Yes, it would be. I was thinking maybe we let this PR merge and replace this function later. Or do you suggest just using Usman's implementation?

2024-03-04 10:35 UTC, bilalmajid-deriv commented on cypress/support/commands.js
> +  cy.close_notification_banner();
No was just bringing into attention because if both are using it, then it should be in common commands currently we can let go but we need to avoid duplication of code as well. Could be that we can do it after both the PRs are merged. 😊

2024-03-04 10:38 UTC, deborah-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("fill_date", (year, month, day) => {
sorry i missed out this but i have changed the name to "c_fillDate"

2024-03-04 13:55 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/idvPoiVerified.cy.js
> +});
This is done

2024-03-04 13:58 UTC, deborah-deriv commented on cypress/support/commands.js
> +  cy.close_notification_banner();
This is done

2024-03-04 13:59 UTC, deborah-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("c_navigate_to_poi_responsive", (country) => {
This is done

2024-03-04 14:01 UTC, deborah-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("c_navigate_to_poi_desktop", (country) => {
This is done

2024-03-04 14:03 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/idvPoiVerified.cy.js
> +        cy.get('select[name="document_type"]').select('Passport');
This is done

2024-03-04 14:06 UTC, deborah-deriv commented on cypress/support/commands.js
> +  cy.get(`span[data-date="2000-09-${day}"]`).click()
I have removed this function as i am no longer using it

2024-03-04 14:07 UTC, deborah-deriv commented on cypress/support/commands.js
> +  cy.get(`span[data-month="${month - 1}"]`).click()
i have removed the whole of this fill_date cypress command as i am no longer using it

2024-03-04 14:08 UTC, deborah-deriv commented on cypress/support/commands.js
> +  cy.get(`span[data-year="${year}"]`).click()
i have removed this fill_date function as i am no longer using it

2024-03-05 02:40 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/idvPoiVerified.cy.js
> +});
Some semi-colons are left, viz, line 5,6,22, and 23 😄

2024-03-05 02:40 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.c_closeNotificationBanner();
Remove the semi-colon from here as well please.

2024-03-05 02:47 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.findByRole('#dt_components_select-native_select-tag', { name: 'Country'})
Why this? Why not `cy.findByLabelText("Country")`? Did that not work?

2024-03-05 02:48 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  //cy.get('select[name="country_input"]').select(country)
Can you remove this commented code if not needed?

2024-03-05 02:48 UTC, abuzar-deriv commented on cypress/support/commands.js
> +
Please remove this extra line.

2024-03-05 02:48 UTC, abuzar-deriv commented on cypress/support/commands.js
> +
Please remove this extra line.

2024-03-05 02:49 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.contains("button", "Next").click()
Can be replaced with `cy.findByRole("button", {name: "Next").click() `😸

2024-03-05 02:50 UTC, abuzar-deriv commented
> Is the package lock change intentional?

What about this @deborah-deriv? Is this needed?

2024-03-05 10:22 UTC, deborah-deriv commented on cypress/support/commands.js
> +  cy.get('select[name="country_input"]').select(country)
Hi @abuzar-deriv regarding the comment on line 717, i checked that in responsive we have no library locators that is why i used cy.get

2024-03-05 11:50 UTC, deborah-deriv commented on cypress/support/commands.js
> +  cy.get('select[name="country_input"]').select(country)
This is addressed @abuzar-deriv

2024-03-05 11:50 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/idvPoiVerified.cy.js
> +});
removed them

2024-03-05 11:51 UTC, deborah-deriv commented on cypress/support/commands.js
> +  cy.c_closeNotificationBanner();
This is done

2024-03-05 11:51 UTC, deborah-deriv commented on cypress/support/commands.js
> +  //cy.get('select[name="country_input"]').select(country)
This is done

2024-03-05 11:57 UTC, deborah-deriv commented on cypress/support/commands.js
> +  cy.contains("button", "Next").click()
This is done

2024-03-05 11:58 UTC, deborah-deriv commented on cypress/support/commands.js
> +  cy.findByRole('#dt_components_select-native_select-tag', { name: 'Country'})
updated this

2024-03-05 12:04 UTC, deborah-deriv commented
> > Is the package lock change intentional?
> 
> What about this @deborah-deriv? Is this needed?

I haven't changed anything in this file. I think it might have updated after installing playwright

2024-03-06 10:03 UTC, abuzar-deriv approved these changes
Looks good

2024-03-06 10:26 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-07 02:06 UTC, meeyun-deriv approved these changes
LGTM

2024-03-11 08:56 UTC, abuzar-deriv requested changes
Hi @deborah-deriv, you haven't resolved the conflicts properly. These commands which you have just re-added are legacy commands and have been deleted.

2024-03-11 09:25 UTC, markodonnell-deriv commented
> > > Is the package lock change intentional?
> > 
> > 
> > What about this @deborah-deriv? Is this needed?
> 
> I haven't changed anything in this file. I think it might have updated after installing playwright

Hi @deborah-deriv you mustn't install Playwright into the same folder as Cypress. Playwright should be installed in another folder. We just use it for the generator.

2024-03-11 09:27 UTC, markodonnell-deriv requested changes
Please uninstall Playwright fromt he e2e-deriv-app folder.

2024-03-11 11:09 UTC, deborah-deriv commented
> Please uninstall Playwright fromt he e2e-deriv-app folder.

This is done

2024-03-11 11:10 UTC, deborah-deriv commented
> Hi @deborah-deriv, you haven't resolved the conflicts properly. These commands which you have just re-added are legacy commands and have been deleted.

I have resolved them properly. Would you please check again?

2024-03-12 04:43 UTC, abuzar-deriv approved these changes

2024-03-12 10:06 UTC, markodonnell-deriv approved these changes
Looks good. I notice the Cypress version has been bumped up, but that should be OK.

2024-03-13 07:36 UTC, merged