MT5 fundtransfer for all fiat currencies
deriv-com/e2e-deriv-app pull request #112
Opened 2024-02-28 13:44 UTC by ravali-deriv

MT5 fundtransfer deposit and withdrawal for all fiat currencies

These changes have one extra file fundTransferUSD_USD.cy.js which is a replacement for the existing fundTransfer.cy.js 
once this PR is merged we need to delete fundTransfer.cy.js file

cards : 
- https://app.clickup.com/t/20696747/CFDS-2831 (EUR-USD)
- https://app.clickup.com/t/20696747/CFDS-2850 (GBP-USD)
- https://app.clickup.com/t/20696747/CFDS-2848 (AUD-USD)

2024-02-28 19:28 UTC, markodonnell-deriv requested changes
This looks generally fine. Although, strangely some git comparison markers have crept into the code?

2024-02-28 19:28 UTC, markodonnell-deriv requested changes

2024-02-28 19:28 UTC, markodonnell-deriv commented on cypress/e2e/wip/CFD/PageElements/mt5TransferLocators.json
> +<<<<<<< HEAD
Please remove this and the others like it.

2024-02-29 03:03 UTC, meeyun-deriv requested changes

2024-02-29 03:03 UTC, meeyun-deriv commented on cypress/e2e/wip/CFD/testcases/MT5/fundTransferAUD_USD.cy.js
> +        fundTransferPageObjects.mt5Deposit('Australian Dollar','Derived SVG')
- Better to separate the action and validation in different commands
- Since it is transferring in different currently, does the validation includes the exchange rate?

2024-03-08 05:42 UTC, meeyun-deriv approved these changes
The separation of action and validation will be performed in next PR

2024-03-08 08:00 UTC, markodonnell-deriv requested changes
Can we remove the Waits. Rather assert on another element you expect to appear. This is Cypress and Playwrights strength.

2024-03-14 03:34 UTC, abuzar-deriv commented on cypress/e2e/wip/CFD/testcases/MT5/fundTransferEUR_USD.cy.js
> +        cy.c_login()
This test is using static login; how will it pass? I suggest creating accounts on run-time for this currency. Same for other tests as well.

2024-03-14 05:10 UTC, bilalmajid-deriv commented on cypress/e2e/wip/CFD/Pages/fundTransferPageObjects.js
> +            }
Line no. 49 to line no. 63 and Line no. 69 to line no. 84

are exact duplicates maybe you could create a separate function for these and call here thanks.

2024-03-14 05:13 UTC, bilalmajid-deriv requested changes
Can you please take care of the code duplication.

would suggest to create a function in the same class and call that function where required and parameterize the function if required.

2024-03-14 05:13 UTC, bilalmajid-deriv commented on cypress/e2e/wip/CFD/Pages/fundTransferPageObjects.js
> +        }
same here duplications here as well in if else condition

2024-03-14 05:15 UTC, bilalmajid-deriv commented on cypress/e2e/wip/CFD/testcases/MT5/fundTransferEUR_USD.cy.js
> +        cy.c_login()
We need a new signup because of the condition that we have transfer limit for a day and that might get exhausted on retrying/executing tests multiple times.

2024-03-14 05:16 UTC, bilalmajid-deriv commented on cypress/e2e/wip/CFD/Pages/fundTransferPageObjects.js
> +                cy.wait(2000)
We need the wait but can be decreased to 300-400 which is also working fine.

2024-03-14 05:20 UTC, ravali-deriv commented on cypress/e2e/wip/CFD/testcases/MT5/fundTransferAUD_USD.cy.js
> +        fundTransferPageObjects.mt5Deposit('Australian Dollar','Derived SVG')
this will be handled as an improvement in separate card

2024-03-21 05:43 UTC, ravali-deriv commented on cypress/e2e/wip/CFD/Pages/fundTransferPageObjects.js
> +                cy.wait(2000)
this is done

2024-03-21 05:43 UTC, ravali-deriv commented on cypress/e2e/wip/CFD/Pages/fundTransferPageObjects.js
> +                cy.wait(2000)
this is done

2024-03-21 05:44 UTC, ravali-deriv commented on cypress/e2e/wip/CFD/testcases/MT5/fundTransferEUR_USD.cy.js
> +        cy.c_login()
I will add signup code in the next improvement card - https://app.clickup.com/t/20696747/CFDS-3380

2024-03-21 05:44 UTC, ravali-deriv commented on cypress/e2e/wip/CFD/Pages/fundTransferPageObjects.js
> +            }
this will be covered in improvements card - https://app.clickup.com/t/20696747/CFDS-3380

2024-03-21 05:44 UTC, ravali-deriv commented on cypress/e2e/wip/CFD/Pages/fundTransferPageObjects.js
> +        }
will be covered in - https://app.clickup.com/t/20696747/CFDS-3380

2024-03-21 06:30 UTC, bilalmajid-deriv approved these changes
LGTM 

can update the snake_case class name in the code clean up ticket.
cc: @abuzar-deriv

2024-04-08 08:07 UTC, meeyun-deriv approved these changes
LGTM

2024-04-08 08:10 UTC, merged