Afsaneh/mt5 change password
deriv-com/e2e-deriv-app pull request #115
Opened 2024-02-29 09:39 UTC by afsaneh-rezaeinejad-deriv

2024-02-29 12:07 UTC, markodonnell-deriv approved these changes
Looks good

2024-03-01 02:20 UTC, abuzar-deriv approved these changes
Looks good

2024-03-01 02:20 UTC, merged

2024-03-01 02:25 UTC, meeyun-deriv requested changes

2024-03-01 02:25 UTC, meeyun-deriv commented on cypress/support/e2e.js
> +Cypress.Commands.add('c_emailVerificationMT5', (verification_code, base_url) => {
why cant we use `c_emailVerificationSignUp` and modify it to look for different expected email subject?

2024-03-01 02:46 UTC, afsaneh-rezaeinejad-deriv commented on cypress/support/e2e.js
> +Cypress.Commands.add('c_emailVerificationMT5', (verification_code, base_url) => {
@meeyun-deriv I will do this once https://github.com/deriv-com/e2e-deriv-app/pull/103 is merged since now we tests which use c_emailVerification are frailing