IDV POI Name Mismatch Test cases
deriv-com/e2e-deriv-app pull request #116
Opened 2024-02-29 15:26 UTC by bertrand-deriv

### IDV POI Name Mismatch Test cases
- Added test cases for the IDV POI name mismatch
- Created some custom commands
- Refactor tests for mobile view

2024-03-06 07:44 UTC, bilalmajid-deriv requested changes
@bertrand-deriv could you please update code to remove all the ; and update command names to follow format c_camelCase.
please do for the ones that Imight have missed as well in your changes. thanks

2024-03-06 07:44 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/idvPoiNameMismatch.cy.js
> +        cy.c_navigate_to_poi_responsive('Republic of QA');
please remove ;

2024-03-06 07:44 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/idvPoiNameMismatch.cy.js
> +        cy.findByLabelText('Enter your document number').type('12376678');
please remove ;

2024-03-06 07:44 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/idvPoiNameMismatch.cy.js
> +});
please remove ;

2024-03-06 07:44 UTC, bilalmajid-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("c_navigate_to_poi", (country) => {
rename command to c_navigateToPoi

to maintain pattern c_camelCase

2024-03-06 07:44 UTC, bilalmajid-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("c_navigate_to_poi_responsive", (country) => {
update command name in format c_camelCase

2024-03-06 07:44 UTC, bilalmajid-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("c_choose_document_type", (document_type) => {
update command name in format c_camelCase

2024-03-06 07:44 UTC, bilalmajid-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("c_choose_document_type_responsive", (document_type) => {
update command name in format c_camelCase

2024-03-06 07:44 UTC, bilalmajid-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("c_fill_data", (input_name, data) => {
update command name in format c_camelCase

2024-03-06 07:44 UTC, bilalmajid-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("c_fill_date", (year, month, day) => {
update command name in format c_camelCase

2024-03-06 07:44 UTC, bilalmajid-deriv commented on cypress/support/commands.js
> +  cy.findByTestId(`${input_name}`).clear().type(`${data}`);
please remove ;

2024-03-07 03:38 UTC, bilalmajid-deriv requested changes

2024-03-07 03:38 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/idvPoiNameMismatch.cy.js
> +});
@bertrand-deriv ; still left here

2024-03-07 03:38 UTC, bilalmajid-deriv commented on cypress/support/commands.js
> +
As decided we will not be using custom commands for actions like these because it is just adding an extra layer to a single operation. 

Now commands are to be preferred over functions and command should only be created for redundant line of codes and operations such as filling a form or something similar which is going to be used across multiple test files.

So can you please remove usage of commands for single operations, Thanks.

2024-03-07 03:38 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/idvPoiNameMismatch.cy.js
> +        cy.c_navigate_to_poi_responsive('Republic of QA')
need to update this as well to cy.c_navigateToPoiResponsive because this wont work 
and have suggested to merge both commands and parameterize the command in below comment.

2024-03-07 03:38 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/idvPoiNameMismatch.cy.js
> +        cy.wait(4000)
Do we have to use this wait(4000)  can we not wait for some element instead

2024-03-07 03:40 UTC, abuzar-deriv requested changes

2024-03-07 03:40 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.findByTestId(`${input_name}`).clear().type(`${data}`)
@bilalmajid-deriv , should this move inside test as we were discussing yesterday?

2024-03-07 03:40 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.findByTestId('date_of_birth').type(`${year}-${month}-${day}`)
Same question as above for this one @bilalmajid-deriv . It's also just filling data for one field.

2024-03-07 03:40 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.close_notification_banner()
Please replace this with cy.close_notification_banner()

2024-03-07 03:40 UTC, abuzar-deriv commented on cypress/support/commands.js
> +  cy.close_notification_banner()
Remove this line. Above command is retryable.

2024-03-07 03:40 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/idvPoiNameMismatch.cy.js
> +        cy.c_navigate_to_poi_responsive('Republic of QA')
Please update the call to c_navigateToPoiResponsive

2024-03-07 03:40 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/idvPoiNameMismatch.cy.js
> +        cy.c_fill_data("first_name", "Refuted")
No need for commands for these. Please see my comments below

2024-03-07 03:40 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/idvPoiNameMismatch.cy.js
> +        cy.c_fill_date("2000", "09", "20")
Same as above for line 13 and 14

2024-03-07 03:40 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/idvPoiNameMismatch.cy.js
> +        cy.wait(4000)
Why this explicit wait? Can you wait for any element instead?

2024-03-07 03:43 UTC, bilalmajid-deriv commented on cypress/support/commands.js
> +  cy.findByTestId(`${input_name}`).clear().type(`${data}`)
yes @abuzar-deriv requested for this change

2024-03-07 03:43 UTC, bilalmajid-deriv commented on cypress/support/commands.js
> +  cy.findByTestId('date_of_birth').type(`${year}-${month}-${day}`)
Agreed

2024-03-07 07:55 UTC, bertrand-deriv commented on cypress/support/commands.js
> +
yes
let me do that quickly
Thanks

2024-03-07 09:46 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-07 09:47 UTC, abuzar-deriv approved these changes
Looks good.

2024-03-11 09:40 UTC, meeyun-deriv approved these changes
LGTM

2024-03-11 09:51 UTC, markodonnell-deriv requested changes
Commands should be in a separate KYV file. Plus be of the correct naming standard.
Also, have we tried to use the testing library? Lot's of use of xpath :(

2024-03-15 10:16 UTC, markodonnell-deriv approved these changes
Looks good

2024-03-18 03:21 UTC, bilalmajid-deriv approved these changes

2024-03-18 03:22 UTC, merged