Usman/delete payment method p2p in responsive mode - Refactored editPaymentMethods - common.js
deriv-com/e2e-deriv-app pull request #118
Opened 2024-03-04 02:27 UTC by usman-deriv

### Cypress test for deletePaymentMethods, refactoring of editPaymentMethods and common.js for reusable functions

This test covers the deletion of a payment method for P2P from the user's profile page. 

I have also added a common.js file which includes common functions that I have used in both editPaymentMethods and deletePaymentMethods spec files. 

I have refactored the editPaymentMethods spec file to support the use of functions in common.js.

2024-03-04 03:02 UTC, abuzar-deriv requested changes
Can you please move common.js under cypress/support main folder as p2p.js for consistency's sake?

2024-03-04 03:02 UTC, abuzar-deriv commented on cypress/e2e/wip/P2P/support/common.js
> +export function navigateToDerivP2P() {
If it's going to be used across multiple tests, can you please convert it to cypress command instead of function?

2024-03-04 03:02 UTC, abuzar-deriv commented on cypress/e2e/wip/P2P/support/common.js
> +export function closeNotificationHeader() {
If it's going to be used across multiple tests, can you please convert it to cypress command instead of function?

2024-03-04 03:17 UTC, usman-deriv commented on cypress/e2e/wip/P2P/deletePaymentMethods.cy.js
> +            if (paymentName && paymentName != '' && paymentID) {
It is better to make sure that _paymentName_ is **not undefined** and is **not empty** '' because paymentName is needed for further test verification as its value is used further in the test. An empty-defined value ('') can break the test.

2024-03-04 04:53 UTC, abuzar-deriv approved these changes
Looks good.

2024-03-04 05:47 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-04 09:27 UTC, meeyun-deriv reviewed
is this test rerunnable? i dont see the setup step to add new payment method for the deletion

2024-03-04 10:10 UTC, meeyun-deriv approved these changes
LGTM

2024-03-05 09:40 UTC, markodonnell-deriv approved these changes
Looks good.

2024-03-05 09:50 UTC, merged