addfinancialaccount
deriv-com/e2e-deriv-app pull request #121
Opened 2024-03-05 07:44 UTC by infanta-deriv

test

2024-03-05 10:04 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/addDemoFinancialExistingMT5Pwd.cy.js
> +      })
Should we not have a common command or function for this as I see this it is being used in multiple test files

2024-03-05 10:07 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/addDemoFinancialExistingMT5Pwd.cy.js
> +  }
this is also being used in multiple files can we not place this in a single place and call in all files accordingly

2024-03-05 10:07 UTC, bilalmajid-deriv reviewed
Changes LGTM but don't we have a lot of code duplication in multiple test for sign up.

2024-03-08 02:50 UTC, bilalmajid-deriv approved these changes
LGTM
added a quick commit to convert snake_case variable to camelCase

2024-03-11 03:28 UTC, abuzar-deriv requested changes

2024-03-11 03:28 UTC, abuzar-deriv commented on cypress/support/commands.js
> +Cypress.Commands.add("c_verificationLinkSignUp", (epoch, country) => {
I believe it makes more sense to call this command `c_demoAccountSignup()`?

2024-03-11 03:28 UTC, abuzar-deriv commented on cypress/support/commands.js
> +    cy.c_completeOnboarding()
This should be pulled out of here and added in spec files itself. Reason: MF account signup doesn't show onboarding and directly lands on account creation modal so it will break.

2024-03-11 03:28 UTC, abuzar-deriv commented on cypress/support/tradersHub.js
> +Cypress.Commands.add("c_checkTradersHubhomePage", () => {
```suggestion
Cypress.Commands.add("c_checkTradersHubHomePage", () => {
```

2024-03-12 05:27 UTC, abuzar-deriv commented on cypress/support/commands.js
> +    cy.c_completeOnboarding()
Moved to conditional due to A/B testing so should be fine for now.

2024-03-12 05:29 UTC, abuzar-deriv commented on cypress/e2e/wip/Tradershub/addUSDAccount.cy.js
> +    cy.close_notification_banner()
Why this? `close_notification_banner()` no longer exists. `cy.c_closeNotificationHeader()` will work.

2024-03-12 05:31 UTC, abuzar-deriv commented on cypress/e2e/wip/Tradershub/addUSDAccount.cy.js
> +    cy.close_notification_banner()
Why this? `close_notification_banner()` no longer exists. `cy.c_closeNotificationHeader()` will work.

2024-03-12 07:44 UTC, abuzar-deriv approved these changes
Looks good

2024-03-12 07:50 UTC, meeyun-deriv approved these changes
LGTM

2024-03-12 07:50 UTC, merged