Usman/User add first payment method in P2P - Responsive
deriv-com/e2e-deriv-app pull request #123
Opened 2024-03-06 07:18 UTC by usman-deriv

### User add their first payment method in P2P responsive mode.

- Add first payment method. 
- delete the added payment method to make the test rerunnable.

2024-03-06 07:52 UTC, bilalmajid-deriv requested changes
@usman-deriv please remove duplications thanks,

2024-03-06 07:52 UTC, bilalmajid-deriv commented on cypress/e2e/wip/P2P/addFirstPaymentMethod.cy.js
> +}
These are redundant in multiple files please move to support/p2p.js
and use from there in all test files.

and please convert functions which are not returning any value into cypress custom commands

2024-03-06 09:03 UTC, usman-deriv commented on cypress/e2e/wip/P2P/addFirstPaymentMethod.cy.js
> +}
This has been done for the spec files for add, edit, and delete for payment methods. Thank you

2024-03-06 10:17 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-06 15:51 UTC, markodonnell-deriv approved these changes
Looks good

2024-03-07 01:57 UTC, meeyun-deriv requested changes

2024-03-07 01:57 UTC, meeyun-deriv commented on cypress/e2e/wip/P2P/addFirstPaymentMethod.cy.js
> +        cy.c_deletePaymentMethod(paymentID, paymentName)
instead of doing cleaning at the end of the test, it is better to do it before running the test

2024-03-07 02:30 UTC, usman-deriv commented on cypress/e2e/wip/P2P/addFirstPaymentMethod.cy.js
> +        cy.c_deletePaymentMethod(paymentID, paymentName)
There are a few reasons for this: I have first tried **cleanup first** approach but in some cases (like this one), cleanup is to be done after. 
- For this test - I am adding a payment method and deleting it, meaning the code is rerunnable. Hence, add -> delete the same added. 
- For instance, if I delete -> add, there is a very high chance that that already existing payment method cannot be deleted because it is being used in an existing Ad, hence it will be flaky. I have tried this approach and tested it. 
What do you suggest now? :)

2024-03-07 02:59 UTC, usman-deriv commented on cypress/e2e/wip/P2P/addFirstPaymentMethod.cy.js
> +        cy.c_deletePaymentMethod(paymentID, paymentName)
Apart from this, as I am generating a random bank account number every single time, hence, there would not be such a condition in which I would be creating a payment method that was already created before. Hence, we can say that it is not a requirement to clean up the state before running the script. It is just an added step to delete what is created. Even if it is not deleted, the next time the test runs, it will not be dependent on the previous payment method created.

2024-03-07 05:48 UTC, meeyun-deriv requested changes

2024-03-07 05:48 UTC, meeyun-deriv commented on cypress/e2e/wip/P2P/addFirstPaymentMethod.cy.js
> +        cy.c_deletePaymentMethod(paymentID, paymentName)
because there is possibility that the test fail half way without deleting the new payment method successfully. In this case, your subsequent test will fail because it will look for `You haven’t added any payment methods yet` before you add a new payment method.

Regarding the second point where the payment method might be in use for other orders, we should use an unique test account for this case, so the tests are independent to each other.

2024-03-07 06:48 UTC, usman-deriv commented on cypress/e2e/wip/P2P/addFirstPaymentMethod.cy.js
> +        cy.c_deletePaymentMethod(paymentID, paymentName)
As per the discussion, I have implemented the above suggestions. Thank you for highlighting this.

2024-03-07 06:56 UTC, meeyun-deriv approved these changes
LGTM

2024-03-07 07:07 UTC, merged