deposit button functionality
deriv-com/e2e-deriv-app pull request #124
Opened 2024-03-06 10:01 UTC by infanta-deriv

This PR has code to verify the deposit button functionality from account switcher in tradershub

2024-03-06 10:10 UTC, abuzar-deriv commented on cypress/e2e/wip/Tradershub/depositAccountSwitcher.cy.js
> +      cy.close_notification_banner()
Please use c_closeNotificationHeader(). This is legacy command and will be removed.

2024-03-06 10:33 UTC, bilalmajid-deriv requested changes

2024-03-06 10:33 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/depositAccountSwitcher.cy.js
> +      cy.url().should('include', '/cashier/deposit')
Could you please add an assertion on the content of the page such as the header on cashier Deposit page as well? because cy.url() only verifies if url and sometimes the page might not even open giving us false positive.thanks

2024-03-07 07:47 UTC, bilalmajid-deriv requested changes

2024-03-07 07:47 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/depositAccountSwitcher.cy.js
> +      cy.get('#dc_deposit_link').should('have.class', 'dc-vertical-tab__header--active');
I dont think we need this is this required? and if yes 
could you please use
`cy.findByRole('link', { name: 'Deposit' })`

2024-03-07 08:34 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/depositAccountSwitcher.cy.js
> +      cy.get('#dc_deposit_link').should('have.class', 'dc-vertical-tab__header--active');
I don't know if it is inactive in some condition 
but if you are only wanting to check if its there should go with 
cy.findByRole('link', { name: 'Deposit' }).should('be.visible') 
so that a playwright locator is used.

and because it was not initially part of the code I am assuming that this is not part of the test so better to use any one of the assertions amongst the two just to avoid false positives.
thanks

2024-03-07 08:55 UTC, abuzar-deriv approved these changes
Looks good.

2024-03-08 05:53 UTC, meeyun-deriv approved these changes
LGTM

2024-03-08 05:53 UTC, merged