validatelinks
deriv-com/e2e-deriv-app pull request #129
Opened 2024-03-07 14:33 UTC by infanta-deriv

card - https://app.clickup.com/t/20696747/TRAH-3020
This PR has script for validating the hyperlinks on Trader's hub

2024-03-08 08:04 UTC, meeyun-deriv requested changes

2024-03-08 08:04 UTC, meeyun-deriv commented on cypress/e2e/wip/Tradershub/linksTradersHub.cy.js
> +describe("QATEST 5930 - Validate the hyperlinks on Trader's hub", () => {
since the steps are quite straight forward, can we also include mobile test in the same PR?

2024-03-08 19:46 UTC, markodonnell-deriv approved these changes
Looks good

2024-03-11 05:49 UTC, abuzar-deriv requested changes

2024-03-11 05:49 UTC, abuzar-deriv commented on cypress/e2e/wip/Tradershub/linksTradersHub.cy.js
> +    cy.c_closeNotificationHeader()
Is this needed? Since the actual test starts from next line?

2024-03-11 05:49 UTC, abuzar-deriv commented on cypress/e2e/wip/Tradershub/linksTradersHub.cy.js
> +    cy.c_login()
Should be in before each block.

2024-03-11 05:49 UTC, abuzar-deriv commented on cypress/e2e/wip/Tradershub/linksTradersHub.cy.js
> +    cy.c_login()
Should be in before each block.

2024-03-11 05:49 UTC, abuzar-deriv commented on cypress/e2e/wip/Tradershub/linksTradersHub.cy.js
> +    }
Can it be handled by `if..else `instead of `if..else if`?

2024-03-11 06:53 UTC, infanta-deriv commented on cypress/e2e/wip/Tradershub/linksTradersHub.cy.js
> +    cy.c_closeNotificationHeader()
yes , because when changed to responsive because of notification header it is unable to detect the element and click . When trying to close the notification header after changing it to mobile view , it is not always reliable so closed the notifications pop before hand

2024-03-11 07:12 UTC, abuzar-deriv approved these changes
Looks good

2024-03-11 07:16 UTC, meeyun-deriv approved these changes
LGTM

2024-03-11 07:16 UTC, merged