P2P - Block and Unblock advertiser from profile page in responsive mode
deriv-com/e2e-deriv-app pull request #131
Opened 2024-03-11 06:57 UTC by usman-deriv

### New Cypress Test

- New cypress test for blocking and unblocking advertisers from profile page. 

[Block and unblock user from advertisers Profile page](https://app.clickup.com/t/20696747/P2PS-2452)

2024-03-11 10:25 UTC, meeyun-deriv requested changes

2024-03-11 10:25 UTC, meeyun-deriv commented on cypress/e2e/wip/P2P/blockUnblockAdvertiser.cy.js
> +    cy.findByText(`You have blocked ${userNickname}.`).should('be.visible')
some validations are missing, e.g. 
1. After blocking one advertiser their ads will not be visible in users buy/sell page
2. User will not able to place any more orders
3. But existing orders can be continued

Similar to `unblockProfile`, it also has some missing validation

2024-03-11 10:25 UTC, meeyun-deriv commented on cypress/e2e/wip/P2P/blockUnblockAdvertiser.cy.js
> +        cy.get('.buy-sell-row__advertiser-name--text').first().invoke('text').then((userNickname) => {
this element has bad locator, we need to create a card so that FE dev can help to improve the locator

2024-03-12 02:18 UTC, usman-deriv commented on cypress/e2e/wip/P2P/blockUnblockAdvertiser.cy.js
> +        cy.get('.buy-sell-row__advertiser-name--text').first().invoke('text').then((userNickname) => {
This is noted, and a card has been created for this. https://app.clickup.com/t/20696747/P2PS-2596
Once updated, I will update the locator to the new one.

2024-03-12 02:24 UTC, usman-deriv commented on cypress/e2e/wip/P2P/blockUnblockAdvertiser.cy.js
> +    cy.findByText(`You have blocked ${userNickname}.`).should('be.visible')
I have created the subtask for this and for the rest of the validations to be done for block/unblock in other PRs. 
Subtask for this PR: [Block and Unblock advert from the advertiser's profile page](https://app.clickup.com/t/20696747/P2PS-2592)

2024-03-12 07:13 UTC, meeyun-deriv approved these changes
LGTM

2024-03-13 05:41 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-13 06:37 UTC, merged