Afsaneh/verification link
deriv-com/e2e-deriv-app pull request #132
Opened 2024-03-11 08:13 UTC by afsaneh-rezaeinejad-deriv

2024-03-12 03:31 UTC, bilalmajid-deriv requested changes

2024-03-12 03:31 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/cashier/cryptoWithdrawal.cy.js
>        Cypress.config("baseUrl")
Is this needed?

2024-03-12 03:31 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/cfd/mt5_reset_password.cy.js
> +    cy.c_emailVerification(Cypress.env("mainQaBoxBaseUrl"),"New%20DMT5%20password%20request.html","QA script")
why hard code "QA script"

2024-03-12 03:31 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/cfd/mt5_reset_password.cy.js
>        Cypress.config("baseUrl")
Do we need Cypress.config("baseUrl") here?

2024-03-12 03:31 UTC, bilalmajid-deriv commented on cypress/support/e2e.js
> +})
is this being used somewhere? if not can remove.

2024-03-12 03:37 UTC, bilalmajid-deriv commented
after these recent changes can we not use the same command for verification of MT5 password email as well?

2024-03-12 05:07 UTC, abuzar-deriv reviewed
I think the idea was to modify it in such a way that it can replace `c_emailVerificationSignUp` as well. Current logic won't do so.

2024-03-12 05:13 UTC, abuzar-deriv requested changes

2024-03-12 05:13 UTC, abuzar-deriv commented on cypress/support/e2e.js
> +                    Cypress.env("verificationdUrl", href)
Spelling mistake, should be `"verificationUrl"`. Same for other instances.

2024-03-12 05:13 UTC, abuzar-deriv commented on cypress/support/e2e.js
> +                    const code = href.match(/code=([A-Za-z0-9]{8})/)
Can we make it conditional? Only extract code if needed?

2024-03-12 05:31 UTC, afsaneh-rezaeinejad-deriv commented on cypress/e2e/wip/Wallets/cashier/cryptoWithdrawal.cy.js
>        Cypress.config("baseUrl")
its required for this line
     cy.c_visitResponsive(
        `${withdrawal_url}?verification=${verification_code}`,
        "large"
      )

2024-03-12 05:44 UTC, afsaneh-rezaeinejad-deriv commented on cypress/e2e/wip/Wallets/cfd/mt5_reset_password.cy.js
> +    cy.c_emailVerification(Cypress.env("mainQaBoxBaseUrl"),"New%20DMT5%20password%20request.html","QA script")
MT5 reset password emails include account name instead of account_email. we can improve this part once creating account through api is merged, then we will create account first and then. there is a refactoring CU card for this
https://app.clickup.com/t/20696747/WALL-3586

2024-03-12 05:53 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/cashier/cryptoWithdrawal.cy.js
>        Cypress.config("baseUrl")
Sorry to be unclear, I meant the Cypress.config("baseUrl") because it does nothing

2024-03-14 08:24 UTC, bilalmajid-deriv requested changes

2024-03-14 08:24 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/accountSignupDIEL(CR+MF).cy.js
> +    cy.c_demoAccountSignup(epoch, country , sign_up_mail)
I think we do not need the epoch here anymore. If yes please remove from parameters for all similar cases.

2024-03-14 08:24 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/accountSignupMF.cy.js
> +  const sign_up_mail = `sanity${epoch}mf@deriv.com`
If epoch is no longer required multiple times we can update this line as 

```suggestion
  const sign_up_mail = `sanity${generateEpoch()}mf@deriv.com`
```

and remove const epoch = generateEpoch()

from all similar cases as well

2024-03-19 02:42 UTC, abuzar-deriv commented on cypress/support/common.js
> +      loginEmail = Cypress.env('walletloginEmail')
This will replace the email for all tests. Is this intended?

2024-03-19 02:51 UTC, abuzar-deriv commented on cypress/e2e/wip/Tradershub/mt5DerivedSVGRealAccount.cy.js
> +>>>>>>> 686aa61ae832488626152448705564295a1c1157
Should be removed.

2024-03-19 02:52 UTC, bilalmajid-deriv requested changes
Left a minor comment

2024-03-19 02:52 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/mt5DerivedSVGRealAccount.cy.js
> +>>>>>>> 686aa61ae832488626152448705564295a1c1157
Kindly remove

2024-03-19 03:31 UTC, abuzar-deriv commented on cypress/support/e2e.js
> +        cy.c_emailVerification(requestType,accountEmail, ++retryCount)
Have you tested this? Reassigning retryCount may not work in recursive call as it is a constant. 
Also, Don't you need to pass an object here instead of variable?

2024-03-19 03:59 UTC, abuzar-deriv commented on cypress/e2e/wip/Tradershub/accountSignupDIEL(CR+MF).cy.js
>      cy.c_setEndpoint(signUpMail)
Please update this to signUpEmail since var name is changing above. Same for other instances.

2024-03-19 08:34 UTC, abuzar-deriv commented on cypress/support/e2e.js
> +        cy.c_emailVerification(requestType,accountEmail, ++retryCount)
```suggestion
        cy.c_emailVerification(requestType,accountEmail, {retryCount: ++retryCount})
```

2024-03-19 08:35 UTC, abuzar-deriv commented on cypress/support/e2e.js
> +  const {
```suggestion
  let {
```

2024-03-19 08:40 UTC, abuzar-deriv approved these changes
Looks good

2024-03-19 08:49 UTC, bilalmajid-deriv approved these changes

2024-03-19 10:38 UTC, meeyun-deriv approved these changes

2024-03-19 10:38 UTC, merged