personaldetailspopup
deriv-com/e2e-deriv-app pull request #136
Opened 2024-03-13 08:15 UTC by infanta-deriv

card - https://app.clickup.com/t/20696747/TRAH-3050
This PR has script for validating the functionality when user closes the "complete your personal details" pop up during sign up

2024-03-13 11:19 UTC, bilalmajid-deriv requested changes

2024-03-13 11:19 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/personalDetailsPopUpValidation.js
> +    const sign_up_mail = `sanity${epoch}account@deriv.com`
please convert to camelCase

2024-03-13 11:19 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/personalDetailsPopUpValidation.js
> +      cy.c_enterValidEmail(sign_up_mail)
I think this code is duplicate and used in many files, can we create a command for this?

2024-03-14 02:16 UTC, meeyun-deriv approved these changes
LGTM

2024-03-14 10:29 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-15 06:52 UTC, bilalmajid-deriv approved these changes

2024-03-15 07:18 UTC, merged