Mali/wall 3591
deriv-com/e2e-deriv-app pull request #140
Opened 2024-03-14 08:58 UTC by maliheh-deriv

# Description : 
expand the test to cover and catch reported issue in production.

# cards 
https://app.clickup.com/t/20696747/WALL-3591

2024-03-15 03:27 UTC, abuzar-deriv requested changes

2024-03-15 03:27 UTC, abuzar-deriv commented on cypress/e2e/full/redirection.cy.js
> +    cy.get('.sc-mcd__item--1HZ10V > .sc-mcd__item__name').click()
Can you please use playwright generator to find testing library supported commands?

2024-03-15 03:27 UTC, abuzar-deriv commented on cypress/e2e/full/redirection.cy.js
> +    cy.get('.dc-btn').should('exist')
Same as above for these. We will only default to cypress locators if we can't testing library commands. Xpath is a no go in almost all cases.

2024-03-15 03:27 UTC, abuzar-deriv commented on cypress/e2e/full/redirection.cy.js
> +describe('WALL-3591 -production bug WALL-3588', () => {
Can you please update the description to what the test is doing?

2024-03-18 09:31 UTC, meeyun-deriv requested changes

2024-03-18 09:31 UTC, meeyun-deriv commented on cypress/e2e/full/redirection.cy.js
> +    cy.get('a[href="/bot"]').click()
it is possible to use testing library for selecting different plaftform, e.g. for DBOT:
```
getByTestId('dt_trading-app-card_real_deriv-bot').getByRole('button', { name: 'Open' }).click();
```

2024-03-18 09:31 UTC, meeyun-deriv commented on cypress/e2e/full/redirection.cy.js
> +    cy.get('a[href="/"]').click()
similar to comment above

2024-03-21 08:58 UTC, abuzar-deriv approved these changes

2024-04-23 04:31 UTC, maliheh-deriv commented
created new PR https://github.com/deriv-com/e2e-deriv-app/pull/240

2024-04-23 04:31 UTC, closed without merging