Add siblings account
deriv-com/e2e-deriv-app pull request #144
Opened 2024-03-15 14:08 UTC by indulekha-deriv

2024-03-18 03:03 UTC, bilalmajid-deriv requested changes

2024-03-18 03:03 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/addSiblingsAccounts.cy.js
> +      cy.c_enterValidEmail(sign_up_mail)
we have a new command for this now  as `cy.c_setEndpoint(signUpMail)`
```suggestion
      cy.c_setEndpoint(signUpMail)
```

2024-03-18 03:03 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/addSiblingsAccounts.cy.js
> +    const sign_up_mail = `sanity${epoch}@deriv.com`
this should be camelCase as
```suggestion
    const signUpMail = `sanity${epoch}@deriv.com`
```

2024-03-18 08:14 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-18 09:27 UTC, meeyun-deriv requested changes

2024-03-18 11:18 UTC, indulekha-deriv commented on cypress/e2e/wip/Tradershub/addSiblingsAccounts.cy.js
> +  cy.get('.dc-modal-header__close').click()
There is no testing library found for real account signup header close modal

2024-03-20 03:12 UTC, meeyun-deriv approved these changes
LGTM

2024-03-20 03:14 UTC, meeyun-deriv approved these changes
LGTM

2024-03-20 03:14 UTC, merged