Thivya/flaky
deriv-com/e2e-deriv-app pull request #145
Opened 2024-03-17 16:15 UTC by thivya-deriv

Created this branch to fix flaky errors and add temp workaround until bug fixes done.
Card: https://app.clickup.com/t/20696747/BOT-1518

2024-03-18 02:44 UTC, bilalmajid-deriv commented
@thivya-deriv can you please take latest pull form master. and resolve conflicts? Thanks

2024-03-18 05:33 UTC, bilalmajid-deriv requested changes

2024-03-18 05:33 UTC, bilalmajid-deriv commented on .github/workflows/cypress_cloud_manual.yml
> -        run: echo TEST_URL="$TEST_LINK" >> $GITHUB_ENV
please use the one in the red because the one on in the green are a security risk

2024-03-18 05:33 UTC, bilalmajid-deriv commented on .github/workflows/cypress_cloud_manual.yml
> -          TEST_SUITE: ${{ github.event.inputs.suite }}
please use the one in the red because the one on in the green are a security risk

2024-03-18 05:33 UTC, bilalmajid-deriv commented on cypress/e2e/wip/dbot/regression-tests/DashboardQuickAction.cy.js
> +import BotBuilder from '../pageobjects/bot_builder_page'
please remove this as well because it is no longer used.

2024-03-18 06:23 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-18 09:40 UTC, meeyun-deriv reviewed
Has this PR been triggered in the GitHub action, and have you observed its failure rate?

2024-03-19 02:52 UTC, meeyun-deriv approved these changes
LGTM

2024-03-19 02:52 UTC, merged