Crypto account creation check
deriv-com/e2e-deriv-app pull request #146
Opened 2024-03-18 04:10 UTC by vimalan-deriv

In this test case we would be creating all the available cryptocurrency in deriv and check for the confirmation message and also details displayed in the manage account page

2024-03-19 08:13 UTC, abuzar-deriv requested changes

2024-03-19 08:13 UTC, abuzar-deriv commented on cypress/e2e/wip/Crypto/crypto_account_check.cy.js
> +});
We already have a common command for this, `c_closeNotificationHeader()`. Can you please replace use that instead and remove this?

2024-03-19 08:13 UTC, abuzar-deriv commented on cypress/e2e/wip/Crypto/crypto_account_check.cy.js
> +  };
Function should be out of describe block.

2024-03-19 08:13 UTC, abuzar-deriv commented on cypress/e2e/wip/Crypto/crypto_account_check.cy.js
> +    cy.wait(1000).closenotificationbanner();
Please remove this dynamic wait and wait for an element instead.

2024-03-19 08:13 UTC, abuzar-deriv commented on cypress/e2e/wip/Crypto/crypto_account_check.cy.js
> +    const currency_code = ["BTC", "ETH", "LTC", "tUSDT", "USDC"];
Please remove semi-colons everywhere.

2024-03-19 08:13 UTC, abuzar-deriv commented on cypress/e2e/wip/Crypto/pageobject/common.js
> +        cryptoaddaccount: () => cy.get('[class*="dc-btn dc-btn__effect dc-btn--primary dc-btn__large"]'),
Were cypress testing library locators not available for these? Can you please check with playwright generator. Please ignore if they were not available.

2024-03-19 08:13 UTC, abuzar-deriv commented on cypress/e2e/wip/Crypto/pageobject/common.js
> +        closenotification: () => cy.get('.notification__close-button')
Same as above for this.

2024-03-21 00:41 UTC, vimalan-deriv commented on cypress/e2e/wip/Crypto/crypto_account_check.cy.js
> +});
I have resolved this issue, please help to check

2024-03-21 03:52 UTC, closed without merging