Validations for Block and Unblocked Advert with ongoing order
deriv-com/e2e-deriv-app pull request #148
Opened 2024-03-18 09:33 UTC by usman-deriv

### Cypress test update for validating blocked and unblocked state with ongoing order

1. Create an order, 
2. Blocked advertiser state validation,  [Blocked advertiser validation check](https://app.clickup.com/t/86bxvnr21)
3. Unblocked advertiser state validation, [Unblocked advertiser validation check](https://app.clickup.com/t/86bxvnr29)
4. Check for an ongoing order state when the advertiser is blocked/unblocked. [Current order status for advertiser](https://app.clickup.com/t/86bxvnr4j)

Main Card: [Create Cypress test QATEST-2871 Block and unblock user from advertisers Profile page](https://app.clickup.com/t/86bxhg8u5)

Also in the PR: Cypress version upgrade to 13.7.0

2024-03-18 09:43 UTC, meeyun-deriv requested changes

2024-03-18 09:43 UTC, meeyun-deriv commented on package.json
> -    "cypress": "^13.6.6",
do we really need to update this?

2024-03-18 09:43 UTC, meeyun-deriv commented on package-lock.json
> -        "cypress": "^13.6.6",
do we need to update this?

2024-03-18 09:47 UTC, bilalmajid-deriv commented on package.json
> -    "cypress": "^13.6.6",
@meeyun-deriv I asked for this as the updated version has no major breaking changes

2024-03-18 10:21 UTC, meeyun-deriv approved these changes
LGTM

2024-03-18 16:49 UTC, markodonnell-deriv approved these changes
Looks good.

2024-03-19 02:44 UTC, bilalmajid-deriv commented on cypress/e2e/wip/P2P/blockUnblockAdvertiser.cy.js
>          })
This is one good way of using session storage to your advantage. because cypress is a little tough on you, when you need to store values extracted from the UI and use through out the test

2024-03-19 02:44 UTC, bilalmajid-deriv approved these changes

2024-03-19 02:46 UTC, usman-deriv commented on cypress/e2e/wip/P2P/blockUnblockAdvertiser.cy.js
>          })
Thank you @bilalmajid-deriv, yes this is the only reason for using session storage as it is to my advantage. 🙇🏼‍♂️ 💯

2024-03-19 06:44 UTC, merged