Add support for login with different emails
deriv-com/e2e-deriv-app pull request #149
Opened 2024-03-19 05:00 UTC by abuzar-deriv

1. Added function setLoginUser: To switch user based on test vs production environment

2.Updated c_login() and getOAuthUrl(): getOAuthUrl() will now receive loginEmail & loginPassword as parameters instead of switching inside the function

3.Updated function calls of c_login() within tests where needed (The change is just on lines where c_login() is being called, rest are auto-formatting changes 😿 )

4.Added new env variables

2024-03-19 17:52 UTC, markodonnell-deriv reviewed
Quite a large PR and looks good in principle.

2024-03-20 04:10 UTC, bilalmajid-deriv reviewed
PR seems to be looking good 

but a question left for removing '' .

2024-03-20 04:10 UTC, bilalmajid-deriv commented on cypress/support/common.js
>          'Content-Type': 'application/json',
Should the '' here be removed?

2024-03-20 04:10 UTC, bilalmajid-deriv commented on cypress/support/common.js
> -          'Origin': 'https://oauth.deriv.com',
same as above

2024-03-20 04:10 UTC, bilalmajid-deriv commented on cypress/support/common.js
> -      'Origin': 'https://oauth.deriv.com'
same as above

2024-03-20 04:36 UTC, bilalmajid-deriv requested changes
a new command for getWalletOAuthUrl() is added can you please pass loing email and login password for that as well accordingly.

2024-03-20 05:09 UTC, abuzar-deriv commented
Good catch about quotes. It was prettier's doing; I've added a rule there now. As for `getWalletOAuthUrl()`, I don't think it's actually needed. I believe it was just added to handle different login credentials. I'll discuss with @afsaneh-rezaeinejad-deriv and remove it in another PR. Or if it's really required, then I'll add the login part there as well.

2024-03-20 05:13 UTC, bilalmajid-deriv commented
> Good catch about quotes. It was prettier's doing; I've added a rule there now. As for `getWalletOAuthUrl()`, I don't think it's actually needed. I believe it was just added to handle different login credentials. I'll discuss with @afsaneh-rezaeinejad-deriv and remove it in another PR. Or if it's really required, then I'll add the login part there as well.

okay sure

2024-03-20 09:17 UTC, meeyun-deriv approved these changes
LGTM

2024-03-20 09:24 UTC, markodonnell-deriv approved these changes
Look good

2024-03-20 09:38 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-21 08:34 UTC, merged