Deborah/idv document rejected
deriv-com/e2e-deriv-app pull request #150
Opened 2024-03-19 09:35 UTC by deborah-deriv

### Deborah/idv document rejected
This is the PR for IDV document rejected

2024-03-20 05:20 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.contains("We were unable to verify the identity document with the details provided.").should('be.visible')
use this instead
```suggestion
    cy.findByText("We were unable to verify the identity document with the details provided.").should('be.visible')
```

2024-03-20 05:20 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.contains("Your documents were submitted successfully").should('be.visible')
use this instead
```suggestion
    cy.findByText("Your documents were submitted successfully").should('be.visible')
```

2024-03-20 05:21 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.contains("Your identity verification failed").should('be.visible')
use this instead
```suggestion
    cy.findByText("Your identity verification failed").should('be.visible')
```

2024-03-20 05:22 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.findByText("Proof of address required").should('exist')
assert on visibility instead
```suggestion
    cy.findByText("Proof of address required").should('be.visible')
```

2024-03-20 05:23 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.findByText("Proof of address required").should('exist')
assert on visibility instead
```suggestion
    cy.findByText("Proof of address required").should('be.visible')
```

2024-03-20 05:27 UTC, bilalmajid-deriv requested changes
Changes requested

2024-03-20 09:46 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.contains("We were unable to verify the identity document with the details provided.").should('be.visible')
This is addressed

2024-03-20 09:46 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.contains("Your identity verification failed").should('be.visible')
I have removed this line as this notification is not showing

2024-03-20 09:47 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.contains("Your documents were submitted successfully").should('be.visible')
This is addressed

2024-03-20 09:47 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.findByText("Proof of address required").should('exist')
This is addressed

2024-03-20 09:47 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.findByText("Proof of address required").should('exist')
This is addressed

2024-03-20 09:51 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-20 10:09 UTC, abuzar-deriv requested changes

2024-03-20 10:09 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.findByText("Proof of address required").should('be.visible')
Can you please change these double quotes to single for consistency's sake?

2024-03-20 10:09 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.findByText("We were unable to verify the identity document with the details provided.").should('be.visible')
Same as above for this.

2024-03-20 10:14 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.findByText("Proof of address required").should('be.visible')
This is addressed

2024-03-20 10:14 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/idvDocumentRejected.cy.js
> +    cy.findByText("We were unable to verify the identity document with the details provided.").should('be.visible')
this is addressed

2024-03-21 02:48 UTC, abuzar-deriv approved these changes
Looks good.

2024-03-22 04:46 UTC, meeyun-deriv approved these changes
LGTM

2024-03-22 04:59 UTC, merged