demo reset balance addition
deriv-com/e2e-deriv-app pull request #16
Opened 2023-11-29 10:58 UTC by lubega-deriv

2023-11-29 11:53 UTC, markodonnell-deriv requested changes
Some changes required which may require a discussion.

2023-11-29 11:53 UTC, markodonnell-deriv commented on cypress/e2e/wip/Wallets/cashier/resetBalance.cy.js
1. I would prefer the test to be able to cater for both Real and Demo accounts, rather than hard code.
2. The testing library has been used a lot more in this one but as per PR 15, there may be some locators that I'd question. Is there really no equivalent testing library function for this one: .wallets-list-header__card_container > .wallets-list-header__content > .wallets-list-header__details-container > .wallets-list-details__action-container > .wallets-header__actions > button
3. It's usually best to avoid the hardcoding of magic numbers but I understand that the Testing Library offers up locators that include text such as this: Transfer from USD Wallet Balance: 9,990.00 USD Demo, so it's hard to avoid. It would be Ok if you always knew that your start point is 10,000 which would the case if you did a Reset Balance before a transfer. However the Reset Balance is in a separate test, so it's not guaranteed to run before the  transfer test. So you need to make an explicit call to ResetBalance at the start of the Transfer Test.

2023-11-30 02:36 UTC, lubega-deriv commented on cypress/e2e/wip/Wallets/cashier/resetBalance.cy.js
1. The functions listed in this `resetBalance.cy.js` file are specifically for Demo accounts and there are no reset balance flows for Real accounts
2. These locators are targeting buttons with no specific identifier or names so these were suggested. I'll try to see if I can find any equivalent ones
<img width="1263" alt="Screenshot 2023-11-30 at 10 31 25 AM" src="https://github.com/deriv-com/e2e-deriv-app/assets/142860499/36de2d09-02d3-4b1e-83d5-fa7b5c6c5474">

3. This flow was made under the impression that the Transfer test would run after Reset Balance. I'll add the `reset_balance_demo` function at the beginning of the Transfer test 👍

2023-11-30 11:03 UTC, markodonnell-deriv approved these changes
Looks good now. Thanks!

2023-11-30 11:03 UTC, merged