fix failing cypress tests
deriv-com/e2e-deriv-app pull request #160
Opened 2024-03-21 04:44 UTC by lubega-deriv

Updated locators for the following tests:
- [x] cryptoWithdrawal
- [x] demoResetBalance
- [x] demoTransactions
- [x] fiatTransactions
- [x] fiatWithdrawal

2024-03-22 05:14 UTC, bilalmajid-deriv requested changes

2024-03-22 05:14 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoResetBalance.cy.js
> +  cy.get('.wallets-list-details__content').within(()=>{
do we not have any Testing library locators for this?

2024-03-22 05:14 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoResetBalance.cy.js
> +  cy.contains('Reset balance').click()
can you please use Testing library locators here 
```suggestion
    cy.findByText('USD').should('be.visible')
  })
  cy.findByText('Reset balance').should('be.visible')
  cy.findByText('Reset balance').click()
```

2024-03-22 05:14 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +  cy.contains('Reset balance').click()
same as above

2024-03-22 05:14 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +  cy.contains(/Transfer from/)
same as above

2024-03-22 05:14 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +    cy.contains('Deriv X')
same as above

2024-03-22 05:14 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +    cy.contains(/Transfer from/).click()
same as above

2024-03-22 05:14 UTC, bilalmajid-deriv commented on cypressTemplate.config.js
can you remove this file it is no longer needed

2024-03-22 05:14 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/fiatWithdrawal.cy.js
> +      cy.contains('Withdraw').click()
same as above

2024-03-22 05:16 UTC, bilalmajid-deriv commented
@lubega-deriv can you please run `npm install` before committing as well
so the check for code formatting passes thanks

2024-03-22 07:11 UTC, lubega-deriv commented on cypress/e2e/wipWallet/demoResetBalance.cy.js
> +  cy.get('.wallets-list-details__content').within(()=>{
In this situation no as it's only a div with a classname prop and no other locators
<img width="310" alt="image" src="https://github.com/deriv-com/e2e-deriv-app/assets/142860499/72265b20-c657-4d7a-b52b-3d90d62cb7ee">

2024-03-22 07:11 UTC, lubega-deriv commented on cypress/e2e/wipWallet/demoResetBalance.cy.js
> +  cy.contains('Reset balance').click()
Updated

2024-03-22 07:11 UTC, lubega-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +  cy.contains('Reset balance').click()
Updated

2024-03-22 07:11 UTC, lubega-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +  cy.contains(/Transfer from/)
Updated

2024-03-22 07:11 UTC, lubega-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +    cy.contains('Deriv X')
Updated

2024-03-22 07:11 UTC, lubega-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +    cy.contains(/Transfer from/).click()
Updated

2024-03-22 07:12 UTC, lubega-deriv commented on cypressTemplate.config.js
Updated

2024-03-22 07:12 UTC, lubega-deriv commented on cypress/e2e/wipWallet/fiatWithdrawal.cy.js
> +      cy.contains('Withdraw').click()
Updated

2024-03-25 04:38 UTC, bilalmajid-deriv requested changes
Changes recommended to update to use Testing Library locators thanks.

2024-03-25 04:38 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/cryptoDeposit.cy.js
>        cy.contains('BTC').should('be.visible')
```suggestion
      cy.findByText('BTC').should('be.visible')
```

2024-03-25 04:38 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/cryptoDeposit.cy.js
>      cy.contains('Copied')
```suggestion
    cy.findByText('Copied')
```

2024-03-25 04:38 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/cryptoTransactions.cy.js
>      cy.contains('LTC Wallet')
```suggestion
    cy.findByText('LTC Wallet')
```

2024-03-25 04:38 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoResetBalance.cy.js
> +    cy.contains('USD').should('be.visible')
```suggestion
    cy.findByText('USD').should('be.visible')
```

2024-03-25 04:38 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoResetBalance.cy.js
> +  cy.findByText('Reset balance').click()
```suggestion
  cy.findByText('Reset balance').should('be.visible').click()
```

2024-03-25 04:38 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +    cy.contains('USD').should('be.visible')
```suggestion
    cy.findByText('USD').should('be.visible')
```

2024-03-25 04:38 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +  cy.findByText('Reset balance').click()
```suggestion
  cy.findByText('Reset balance').should('be.visible').click()
```

2024-03-25 04:38 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +    cy.contains('Deriv X')
```suggestion
    cy.findByText('MT5 Derived')
    cy.findByText('Deriv X')
```

2024-03-25 04:38 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/fiatTransactions.cy.js
>      cy.contains('ETH Wallet')
```suggestion
    cy.findByText('LTC Wallet')
    cy.findByText('ETH Wallet')
```

2024-03-25 04:45 UTC, lubega-deriv commented on cypress/e2e/wip/Wallets/cryptoDeposit.cy.js
>        cy.contains('BTC').should('be.visible')
Invalid locator and unable to find element which matches

2024-03-25 04:45 UTC, lubega-deriv commented on cypress/e2e/wip/Wallets/cryptoDeposit.cy.js
>      cy.contains('Copied')
Invalid locator and unable to find element which matches

2024-03-25 04:45 UTC, lubega-deriv commented on cypress/e2e/wip/Wallets/cryptoTransactions.cy.js
>      cy.contains('LTC Wallet')
Invalid locator and unable to find element which matches

2024-03-25 04:46 UTC, lubega-deriv commented on cypress/e2e/wipWallet/demoResetBalance.cy.js
> +    cy.contains('USD').should('be.visible')
Invalid locator and unable to find element which matches

2024-03-25 04:46 UTC, lubega-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +    cy.contains('USD').should('be.visible')
Invalid locator and unable to find element which matches

2024-03-25 04:46 UTC, lubega-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +    cy.contains('Deriv X')
Invalid locator and unable to find element which matches

2024-03-25 04:46 UTC, lubega-deriv commented on cypress/e2e/wipWallet/fiatTransactions.cy.js
>      cy.contains('ETH Wallet')
Invalid locator and unable to find element which matches

2024-03-25 05:34 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/cryptoDeposit.cy.js
>        cy.contains('BTC').should('be.visible')
edited previous suggestion can try that now

2024-03-25 05:34 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/cryptoDeposit.cy.js
>      cy.contains('Copied')
edited previous suggestion can try that now

2024-03-25 05:49 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/cryptoTransactions.cy.js
>      cy.contains('LTC Wallet')
edited previous suggestion can try that now

2024-03-25 05:51 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoResetBalance.cy.js
> +    cy.contains('USD').should('be.visible')
edited previous suggestion can try that now

2024-03-25 05:51 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +    cy.contains('USD').should('be.visible')
edited previous suggestion can try that now

2024-03-25 06:59 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/demoTransactions.cy.js
> +    cy.contains('Deriv X')
```suggestion
    cy.findByText(/-10.00 USD/)
    cy.findByText(/MT5 Derived/)
    cy.findByText(/Deriv X/)
```

2024-03-25 06:59 UTC, bilalmajid-deriv commented on cypress/e2e/wipWallet/fiatTransactions.cy.js
>      cy.contains('ETH Wallet')
edited previous suggestion can use that

2024-03-25 07:33 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-25 09:49 UTC, meeyun-deriv approved these changes
LGTM

2024-03-25 09:49 UTC, merged