IDV document expired scenario
deriv-com/e2e-deriv-app pull request #176
Opened 2024-03-22 18:28 UTC by ivo-deriv

Adds test spec for the IDV expired document scenario.

2024-03-25 03:30 UTC, bilalmajid-deriv requested changes

2024-03-25 03:30 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/idvExpired.cy.js
> +    cy.get('input[name="last_name"]').type('Leo')
Please use Testing Library locators for this 
can take a look into cypress/e2e/wip/KYC/idvDobMismatch.cy.js

2024-03-25 17:07 UTC, ivo-deriv commented on cypress/e2e/wip/KYC/idvExpired.cy.js
> +    cy.get('input[name="last_name"]').type('Leo')
have added locators

2024-03-26 02:33 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-28 09:25 UTC, markodonnell-deriv approved these changes
Looks good

2024-03-29 08:40 UTC, merged