Indu/tradershub gh
deriv-com/e2e-deriv-app pull request #178
Opened 2024-03-25 04:31 UTC by indulekha-deriv

2024-03-29 04:43 UTC, meeyun-deriv requested changes

2024-03-29 04:43 UTC, meeyun-deriv commented on cypress.config.js
> +    baseUrl: process.env.CYPRESS_BASE_URL,
are these new env var already added in github action secrets? If so, can you also share in `Cypress env var - deriv app` in Lastpass?

2024-04-01 16:37 UTC, indulekha-deriv commented on cypress.config.js
> +    baseUrl: process.env.CYPRESS_BASE_URL,
Added in LP. CYPRESS_BASE_URL- env is set from the workflow input filed -'environment' or input passed in test URL

2024-04-03 08:09 UTC, meeyun-deriv approved these changes
LGTM

2024-04-03 09:18 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/accountSignupDIEL(CR+MF).cy.js
> +    cy.c_addAccountMF('CR+MF')
is this CR+MF used in the command because i don't see any usage for this?

2024-04-03 09:18 UTC, bilalmajid-deriv commented on cypress/support/commands/tradersHub.js
> +  const mainURL = Cypress.env('baseUrl')
Why not use Cypress.config('baseUrl') ?

2024-04-03 10:14 UTC, indulekha-deriv commented on cypress/e2e/wip/Tradershub/accountSignupCR(Onfido+IDV).cy.js
> +  let counter = 0
Removed

2024-04-03 10:22 UTC, indulekha-deriv commented on cypress/e2e/wip/Tradershub/accountSignupDIEL(CR+MF).cy.js
> +    cy.c_addAccountMF('CR+MF')
MF is being used. I have removed 'CR+MF'

2024-04-03 10:50 UTC, indulekha-deriv commented on cypress/support/commands/tradersHub.js
> +  const mainURL = Cypress.env('baseUrl')
The c_setEndpoint function should utilize Cypress.config('baseUrl'). For other trading hub scenarios, the base URL can be derived from an environment variable. Update done.

2024-04-03 10:56 UTC, bilalmajid-deriv approved these changes

2024-04-03 10:57 UTC, merged