Crypto deposit
deriv-com/e2e-deriv-app pull request #18
Opened 2023-12-01 09:15 UTC by lubega-deriv

### Added Changes ###

- [x] Added e2e test for crypto deposit and fiat onramp modules
- [x] Updated locator for fiat deposit module to specify USD Wallet
- [x] Updated fiat withdrawal module to access qa box email for verification code fetching
- [x] Added onramp as an app in c_login function to access specific credential needed for onramp flow
- [x] Remove unused cypress command for qa box login

### TODO ###
- [ ] Check if external banxa provider is able to be fetched in the same tab

### Clickup Card ###

https://app.clickup.com/t/20696747/WALL-2831

2023-12-05 09:08 UTC, markodonnell-deriv requested changes
Looks good. Just a comment on the use of c_visitResponsive.
And cy.wait() is an anti-pattern in Cypress. Could you not use should("exist") on a given element?
Also, please remove extraneous semi-colons and we probably need to create standard around line length but I'll discuss that with you.

2023-12-06 02:56 UTC, lubega-deriv commented on cypress/e2e/wip/Wallets/cashier/fiatWithdrawal.cy.js
> +      cy.visit(
Tried recreating this method but it returns this error:

<img width="379" alt="image" src="https://github.com/deriv-com/e2e-deriv-app/assets/142860499/f6c91264-e5f6-48bb-b166-231af2ae7d0d">

Could be because we're trying to access a url with dynamic variables, which was why I resorted to using cy.visit instead

2023-12-06 02:57 UTC, lubega-deriv commented on cypress/e2e/wip/Wallets/cashier/fiatDeposit.cy.js
Updated

2023-12-06 10:13 UTC, markodonnell-deriv approved these changes
As discussed. Let's merge now and refactor the cy.Origin afterwards.

2023-12-06 10:13 UTC, merged

2023-12-07 01:42 UTC, lubega-deriv commented on cypress/e2e/wip/Wallets/cashier/fiatWithdrawal.cy.js
> +                cy.log(Cypress.env("walletsWithdrawalCode"))
This email verification is only needed for Fiat Withdrawal and Crypto Withdrawal AFAIK. The deposit flow for fiat and crypto could both be done without needing the email verification