New Test - Usman/createAdSellFixedRate.cy.js
deriv-com/e2e-deriv-app pull request #180
Opened 2024-03-25 08:08 UTC by usman-deriv

### New Test Scenario -> Create Sell Ad for **Fixed Rate**

1. [[Cleanup]](https://app.clickup.com/t/86bxzyqqb) - Delete existing ads and Payment Methods that were created
2. [[Validation of Input Fields]](https://app.clickup.com/t/86by1p4d7) - Create a sell Ad for Fixed Type Ads
3. [[Verification]](https://app.clickup.com/t/86by1p4q4) - Verify created ad in 'My ad' tab in P2P
5. All validation checks for the fields and test scenario is covered. 

More in PR:
**Enhancements** 
- Changes also covered for createAdBuy.cy.js, (createNewAd() function became parameterized)
- Enhancement in createAdBuyFixedRate for changes done for a function (createNewAd() function became parameterized)
- createNewAd() -> new parameter added (adType) so that sell and buy can be catered from 1 function. 
- c_verifyTextAreaBlock and c_verifyTextAreaLength function to check for the length and BVA for the fields. 
- 

Main Card - [QATEST-2425 Create a Sell type Advert :- Fixed Rate](https://app.clickup.com/t/20696747/P2PS-2424)

2024-03-25 08:28 UTC, bilalmajid-deriv requested changes
left some comments

2024-03-25 08:28 UTC, bilalmajid-deriv commented on cypress/support/commands/p2p.js
> +    ).should('exist')
why change assertion from visibility to existence ?
if the element does not exist test will fail at findByText()

2024-03-25 08:28 UTC, bilalmajid-deriv commented on cypress/support/commands/p2p.js
> +  cy.findByPlaceholderText('Add').should('not.exist')
duplicate

2024-03-25 08:28 UTC, bilalmajid-deriv commented on cypress/support/commands/p2p.js
>    })
can be used with above line 243 like
```suggestion
  cy.findByRole('button', { name: 'Delete' }).should('be.enabled').click().should('not.exist', {
    timeout: 10000,
  })
```

2024-03-25 08:34 UTC, usman-deriv commented on cypress/support/commands/p2p.js
> +    ).should('exist')
Element being checked is on the screen but is not visible as field being typed on is way below. Hence it has been changed to check for its existence on the page.

2024-03-25 08:35 UTC, abuzar-deriv commented on cypress/support/commands/p2p.js
> +    ).should('exist')
Why this change?

2024-03-25 08:35 UTC, abuzar-deriv commented on cypress/support/commands/p2p.js
> +    ).should('exist')
Same question as above.

2024-03-25 08:35 UTC, abuzar-deriv commented on cypress/support/commands/p2p.js
> +    cy.findByRole('button').should('exist').and('contain.text', 'Add')
Why not use `findByRole('button', {name: 'Add'}`?

2024-03-25 08:36 UTC, abuzar-deriv commented on cypress/support/commands/p2p.js
> +    ).should('exist')
Same comment as @bilalmajid-deriv 😄 . Resolving.

2024-03-25 08:37 UTC, usman-deriv commented on cypress/support/commands/p2p.js
> +    ).should('exist')
Element being checked is on the screen but is not visible as field being typed on is way below. Hence it has been changed to check for its existence on the page.

2024-03-25 08:37 UTC, usman-deriv commented on cypress/support/commands/p2p.js
> +    ).should('exist')
Element being checked is on the screen but is not visible as field being typed on is way below. Hence it has been changed to check for its existence on the page.

2024-03-25 08:42 UTC, usman-deriv commented on cypress/support/commands/p2p.js
> +    cy.findByRole('button').should('exist').and('contain.text', 'Add')
Because the button text can either me "Add new" (when there already exist a payment method) or "Add payment methods" (When there exist no payment method), operation of the either button is the same, Hence either of the two can be clicked when using `'contain.text', Add`

<img width="475" alt="Screenshot 2024-03-25 at 4 40 21 PM" src="https://github.com/deriv-com/e2e-deriv-app/assets/152943428/3e5411d3-7ac3-440e-ac90-92fb3e818255">

<img width="465" alt="Screenshot 2024-03-25 at 4 41 00 PM" src="https://github.com/deriv-com/e2e-deriv-app/assets/152943428/f436a4b3-9fda-4a07-adbd-2198a7e976de">

2024-03-25 08:47 UTC, usman-deriv commented on cypress/support/commands/p2p.js
> +    ).should('exist')
The field errors are from the first field when typing in 3rd and 4th field.
Validations are properly visible and at the correct positions, its just that when cypress is typing in the field, it scrolls way down and the above field gets behind the screen. 
<img width="473" alt="image" src="https://github.com/deriv-com/e2e-deriv-app/assets/152943428/63b43730-799d-4885-a297-afd10a61e7cd">

2024-03-25 08:54 UTC, abuzar-deriv commented on cypress/support/commands/p2p.js
> +    cy.findByRole('button').should('exist').and('contain.text', 'Add')
Can you try findByRole('button', {name: '/Add/'}?

2024-03-25 09:04 UTC, usman-deriv commented on cypress/support/commands/p2p.js
> +    cy.findByRole('button').should('exist').and('contain.text', 'Add')
findByRole('button', {name: /Add/}

2024-03-25 09:13 UTC, usman-deriv commented on cypress/support/commands/p2p.js
> +    ).should('exist')
now using .scrollIntoView() and it is working with 'be.visible'

2024-03-25 09:14 UTC, usman-deriv commented on cypress/support/commands/p2p.js
> +    ).should('exist')
now using .scrollIntoView() and it is working with 'be.visible'

2024-03-25 09:33 UTC, abuzar-deriv approved these changes
Looks good.

2024-03-25 10:51 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-26 03:22 UTC, meeyun-deriv approved these changes
LGTM

2024-03-26 03:22 UTC, merged