Check for blockly to be loaded
deriv-com/e2e-deriv-app pull request #196
Opened 2024-04-02 08:28 UTC by thivya-deriv

2024-04-03 04:51 UTC, abuzar-deriv requested changes

2024-04-03 04:51 UTC, abuzar-deriv commented on cypress/e2e/wip/dbot/pageobjects/common.js
> +    cy.get('.bot-dashboard.bot').should('be.visible').wait(2000)
Please use dynamic wait.
```suggestion
    cy.get('.bot-dashboard.bot', {timeout:2000}).should('be.visible')
```

2024-04-03 05:05 UTC, abuzar-deriv commented on cypress/e2e/wip/dbot/pageobjects/common.js
> +    cy.get('.bot-dashboard.bot').should('be.visible').wait(2000)
Also, just remembered. Cypress default timeout is already 4 sec so this isn't even needed unless you wait for something greater than 4 sec. ⏲️

2024-04-03 07:07 UTC, thivya-deriv commented on cypress/e2e/wip/dbot/pageobjects/common.js
> +    cy.get('.bot-dashboard.bot').should('be.visible').wait(2000)
ok will remove the wait then

2024-04-03 07:35 UTC, abuzar-deriv approved these changes

2024-04-05 11:02 UTC, bilalmajid-deriv approved these changes

2024-04-05 11:37 UTC, markodonnell-deriv approved these changes
Looks good

2024-04-05 12:01 UTC, merged