Crypto withdrawal
deriv-com/e2e-deriv-app pull request #20
Opened 2023-12-05 04:21 UTC by lubega-deriv

2023-12-05 04:23 UTC, lubega-deriv reviewed
Config files added in this PR to update cypress from 13.5.0 to 13.6.0

2023-12-05 04:23 UTC, lubega-deriv commented on cypress/support/e2e.js
> +    cy.findByRole('button', { name: 'Continue' }).click()
Additional step in c_login added as test-app now has a popup for SmartCharts after logging in

2023-12-05 09:21 UTC, markodonnell-deriv requested changes
As per comment in PR 18, the cy.Origin code block should be reusable as a command (if outside the spec file) or function (if within).

2023-12-05 09:21 UTC, markodonnell-deriv commented on cypress/support/e2e.js
> +    cy.findByRole('button', { name: 'Continue' }).click()
We should be able to make this conditional. See how I've coded the wallets checkbox click in c_login

2023-12-06 03:38 UTC, lubega-deriv commented on cypress/support/e2e.js
> +    cy.findByRole('button', { name: 'Continue' }).click()
Updated

2023-12-06 10:14 UTC, markodonnell-deriv approved these changes
As discussed. Happy to merge now and refactor cy.Origin afterwards. We have a bit of a backlog of PRs now.

2023-12-06 10:14 UTC, merged