Afsaneh/update transfer
deriv-com/e2e-deriv-app pull request #210
Opened 2024-04-05 04:49 UTC by afsaneh-rezaeinejad-deriv

2024-04-05 04:52 UTC, meeyun-deriv requested changes

2024-04-05 04:52 UTC, meeyun-deriv commented on cypress/e2e/wip/Wallets/cryptoTransactions.cy.js
> +    cy.findAllByText(/-0.00003000 BTC/)
better to put it as a variable so we no need to handle the code separately when changing the amount

2024-04-05 06:13 UTC, lubega-deriv approved these changes

2024-04-08 03:21 UTC, meeyun-deriv approved these changes
LGTM

2024-04-08 03:21 UTC, merged