Onfido x 2 >> Manual upload
deriv-com/e2e-deriv-app pull request #217
Opened 2024-04-12 07:23 UTC by deborah-deriv

**Onfido fails two times Manual upload:**
This are tests of failing onfido two times and then redirect to manual upload

2024-04-16 03:04 UTC, meeyun-deriv requested changes

2024-04-16 03:04 UTC, meeyun-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    cy.get('.dc-checkbox__box').click()
can you please check if this element is possible to use testing-libraries query? Same for other locator with `cy.get`

2024-04-16 03:09 UTC, bilalmajid-deriv requested changes
Left comments

2024-04-16 03:09 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    cy.findByText('Your proof of identity submission failed because:')
can we not make it a retry able command?

2024-04-16 03:09 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    )
same here can we not make it retryable?

2024-04-16 03:09 UTC, bilalmajid-deriv commented on cypress/support/commands/kyc.js
> +  cy.contains('button', 'Next').click()
can you use cy.findByText() here?

2024-04-16 13:09 UTC, deborah-deriv commented on cypress/support/commands/kyc.js
> +  cy.contains('button', 'Next').click()
Hi Bilal,  we have been trying to find a way to use these kinds of testing library commands to select a country from the selector dropdown, but they don't work well plus it will require 4 commands to achieve the same result. This is the faster way we can select a country from the dropdown. How about we create a custom locator to maintain elegance here in this test case codebase?

2024-04-16 13:43 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    cy.get('.dc-checkbox__box').click()
Hi @meeyun-deriv, actually I tried to find possible test-library commands for this checkbox but were all failing. We always try to use testing-library commands wherever we can but It seems like sometimes there is no way you can get an element other than using something like `cy.get` 
<img width="1728" alt="Screenshot 2024-04-16 at 15 35 06" src="https://github.com/deriv-com/e2e-deriv-app/assets/111048322/2410884b-5d97-45ce-8c07-a8339bf36284">
<img width="1728" alt="Screenshot 2024-04-16 at 15 36 15" src="https://github.com/deriv-com/e2e-deriv-app/assets/111048322/4f415059-8322-43ef-bc05-d01a83bbbf81">
<img width="805" alt="Screenshot 2024-04-16 at 15 37 47" src="https://github.com/deriv-com/e2e-deriv-app/assets/111048322/0dc2148f-6f7d-4f63-b489-a0586d13ee56">

2024-04-16 13:46 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    cy.findByText('Your proof of identity submission failed because:')
Hi @bilalmajid-deriv , sorry i am not getting this comment. Did you mean to use retryable command as the one we have in "c_emailVerification" ?

2024-04-19 08:08 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    cy.findByText('Your proof of identity submission failed because:')
Note: I have put that wait and reload because Onfido takes some time to trigger. So I have to wait for some seconds and then refresh the page to check the Onfido result

2024-04-19 08:08 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    )
Note: I have put that wait and reload because Onfido takes some time to trigger. So I have to wait for some seconds and then refresh the page to check the Onfido result

2024-04-29 09:52 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    cy.findByText('Your proof of identity submission failed because:')
Hi @bilalmajid-deriv I have tried to update the cy.wait() command. Would you please help to check again?

2024-04-29 09:54 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    )
Hi @bilalmajid-deriv i have tried to remove cy.wait(), would you please help check again?

2024-04-30 03:53 UTC, bilalmajid-deriv reviewed
@deborah-deriv have unresolved one conversation can you have a look thanks

2024-04-30 03:53 UTC, bilalmajid-deriv commented on cypress/support/commands/kyc.js
> +  cy.contains('button', 'Next').click()
@deborah-deriv I agree that sometimes cypress locators are better performing than playwright locators but over here I was specifying only for the 
`cy.contains('button', 'Next').click()`
I presume cy.findByRole('button',{name:'Next'}) will also work.

2024-04-30 07:24 UTC, deborah-deriv commented on cypress/support/commands/kyc.js
> +  cy.contains('button', 'Next').click()
Hi @bilalmajid-deriv this is addressed. Would you please have a look again?

2024-04-30 07:26 UTC, bilalmajid-deriv approved these changes
LGTM

2024-04-30 09:21 UTC, abuzar-deriv approved these changes
LGTM

2024-04-30 09:33 UTC, meeyun-deriv approved these changes
LGTM

2024-04-30 09:34 UTC, merged

2024-04-30 09:37 UTC, meeyun-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +describe('QATEST-22853 Onfido (2 attempts) failed clients are redirected to manual upload', () => {
this test scenario ID is not reflecting the test scope. Do you mean this test `QATEST-127508` instead?