Added Sign-up Flow in ES Language
deriv-com/e2e-deriv-app pull request #225
Opened 2024-04-18 04:30 UTC by faezeh-deriv

# Summary
This PR is for adding the sign-up flow in `ES` language after [WEBREL-2604](https://app.clickup.com/t/20696747/WEBREL-2604) production bug. The test is running on mobile view.

# Ticket
https://app.clickup.com/t/20696747/TRAH-3089

# Note
I've defined the commands I need in the `.cy.js` file itself cause I believe these commands are only usable for this test case due to the language checks.

2024-04-23 05:14 UTC, meeyun-deriv requested changes
Many custom command could have been duplicated with existing ones from create account. Since we are adding translation check for create account, we should update the existing custom command to support multi languages instead

2024-04-23 05:14 UTC, meeyun-deriv commented on cypress/e2e/wip/Tradershub/accountSignupES.cy.js
> +  cy.get('select[data-testid="place_of_birth_mobile"]').select(country)
please use testing library whenever possible. E.g. 
```
    cy.findByTestId('place_of_birth').click();
```

2024-04-23 05:14 UTC, meeyun-deriv commented on cypress/e2e/wip/Tradershub/accountSignupES.cy.js
> +  cy.get('select[data-testid="citizenship_mobile"]').select(country)
same for comment above. Please check across the PR.

2024-04-24 02:06 UTC, faezeh-deriv commented on cypress/e2e/wip/Tradershub/accountSignupES.cy.js
> +  cy.get('select[data-testid="place_of_birth_mobile"]').select(country)
I tried this but since it was the mobile view, it didn't work - But let me try it again.

2024-04-26 07:31 UTC, faezeh-deriv commented
> Many custom command could have been duplicated with existing ones from create account. Since we are adding translation check for create account, we should update the existing custom command to support multi languages instead

After all considerations, I don't think making the sign-up commands that general will be a good idea:
1. It will add to the command's complexity
2. There will be too many `if else` in one command and the runtime will increase
3. In my case, I am running the test in mobile and the already defined commands are compatible with desktop (element locators and some commands used are different)
4. Again, in my case, the URLs and redirections (the scenario) are also different in some places
In conclusion, I don't suggest making the commands general as it is not an efficient thing to do.

Let me know what do you think please. Thank you.

But if we insist on making the commands general, I can make commands for other languages rather than `EN` and those commands can be used in any language. So, we will have 2 sets of commands for sign-up:
1. Sign-up commands in `EN`
2. Sign-up commands in any other language rather than `EN`

2024-04-29 10:49 UTC, faezeh-deriv commented
Update: I talked with @abuzar-deriv and @bilalmajid-deriv, we came to a conclusion to create a fixture `.json` file and define different language translations in it so we can pass them to the same commands across the sign-up flow test cases (instead of creating different commands for different languages)

But we will need to create different sets of commands for mobile and desktop if the steps duplication is not a lot.

2024-05-02 22:38 UTC, faezeh-deriv commented on cypress/e2e/wip/Tradershub/accountSignupES.cy.js
> +  const mainURL = 'https://staging-app.deriv.com/endpoint?lang=ES'
the hardcode URL is removed.

2024-05-02 22:39 UTC, faezeh-deriv commented on cypress/e2e/wip/Tradershub/accountSignupES.cy.js
> +  cy.get('select[data-testid="place_of_birth_mobile"]').select(country)
this is done.

2024-05-02 22:39 UTC, faezeh-deriv commented
> Many custom command could have been duplicated with existing ones from create account. Since we are adding translation check for create account, we should update the existing custom command to support multi languages instead

this is done using fixtures.

2024-05-03 05:06 UTC, abuzar-deriv requested changes
@faezeh-deriv , it's breaking some English language tests when run right after Spanish test. You might need to clear some cookier and/or local storage in commands where it's visiting a URL. 
Can you please also run a few other signup tests just to check nothing else is breaking?
Thanks.

2024-05-03 06:05 UTC, faezeh-deriv commented on cypress/support/commands/tradersHub.js
>      const { isMobile = false } = options
done.

2024-05-03 06:05 UTC, faezeh-deriv commented on cypress/support/commands/tradersHub.js
> +  const { language = 'english' } = options
done.

2024-05-03 06:05 UTC, faezeh-deriv commented on cypress/support/commands/tradersHub.js
> +  const { language = 'english' } = options
done.

2024-05-03 06:06 UTC, faezeh-deriv commented on cypress/support/commands/tradersHub.js
> +  const { language = 'english' } = options
done.

2024-05-03 06:06 UTC, faezeh-deriv commented on cypress/support/commands/tradersHub.js
> +  const { language = 'english' } = options
done.

2024-05-03 06:59 UTC, faezeh-deriv commented
> @faezeh-deriv , it's breaking some English language tests when run right after Spanish test. You might need to clear some cookier and/or local storage in commands where it's visiting a URL. Can you please also run a few other signup tests just to check nothing else is breaking? Thanks.

this is done.

2024-05-03 06:59 UTC, abuzar-deriv approved these changes
LGTM

2024-05-03 07:05 UTC, markodonnell-deriv approved these changes
Looks good

2024-05-03 07:56 UTC, merged