CSIT-913 Create test for QATEST-116798 Self Exclusion [Session and login limits]
deriv-com/e2e-deriv-app pull request #231
Opened 2024-04-18 12:44 UTC by Alena-deriv

Test link: https://app.clickup.com/t/20696747/CSIT-913

Test is creating a client and sets self exclusion.

2024-04-23 11:29 UTC, meeyun-deriv requested changes
some of the expected behaviour are not included in the current test e.g. after self exclusion, client cant deposit, trader and create new sibling account. 

Please help to add all necessary validations

2024-04-23 11:29 UTC, meeyun-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +  cy.wait(2000)
why do we need different hard wait in this PR?

2024-04-23 11:29 UTC, meeyun-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +  cy.c_visitResponsive('/appstore/traders-hub', 'large')
can we also include responsive test as we need to prioritise responsive test first

2024-06-06 13:37 UTC, Alena-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +  cy.wait(2000)
Updated to the common approach - changed to timeouts, to let the page fully loaded in order to proceed with steps

2024-06-06 13:38 UTC, Alena-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +  cy.c_visitResponsive('/appstore/traders-hub', 'large')
On mobile view datapicker is not working as expected; will be added in a separate PR (subtask https://app.clickup.com/t/20696747/CSIT-1120)

2024-06-06 16:51 UTC, markodonnell-deriv requested changes

2024-06-06 16:51 UTC, markodonnell-deriv commented on cypress/e2e/wip/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    //cy.c_visitResponsive('/reports/statement', 'large')
Could you remove the comments?

2024-06-07 07:26 UTC, Alena-deriv commented on cypress/e2e/wip/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    //cy.c_visitResponsive('/reports/statement', 'large')
This is updated as requested

2024-06-07 07:31 UTC, markodonnell-deriv approved these changes

2024-06-07 07:35 UTC, markodonnell-deriv requested changes
Looks good

2024-06-07 07:36 UTC, markodonnell-deriv approved these changes
Looks good

2024-06-07 09:26 UTC, abuzar-deriv requested changes
Requesting some changes.

2024-06-07 09:26 UTC, abuzar-deriv commented on cypress/e2e/wip/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    cy.log('<E2EOAuthUrl - beforeEach>' + Cypress.env('oAuthUrl'))
No need to log this. Please remove.

2024-06-07 09:26 UTC, abuzar-deriv commented on cypress/e2e/wip/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    cy.get('[class="dc-text balance-text__text--real"]', {
Please use `findByDataTestId('dt_balance_text_container')`. You may use `cy.findAllByTestId('dt_balance_text_container').should('have.length', '2')` to verify page has loaded.

2024-06-07 09:26 UTC, abuzar-deriv commented on cypress/e2e/wip/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    cy.get('[class="dc-dialog__dialog"]').should(
Please try to use a testing library locator here. If not available, please change it to `cy.get('.dc-dialog__dialog')`

2024-06-07 09:26 UTC, abuzar-deriv commented on cypress/e2e/wip/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    cy.get('[class="dc-modal-body"]').should('be.visible') // checks Trade is unavailable
Please try to use a testing library locator here. If not available, please change it to `cy.get('.dc-modal-body')`

2024-06-07 09:27 UTC, abuzar-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +  cy.c_visitResponsive('/appstore/traders-hub', 'large')
What's the issue @Alena-deriv . You can type it out on responsive `cy.get(`input[type='Date']`).first().type(<Your date here>)`

2024-06-07 10:08 UTC, Alena-deriv commented on cypress/e2e/wip/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    cy.log('<E2EOAuthUrl - beforeEach>' + Cypress.env('oAuthUrl'))
Removed

2024-06-07 10:08 UTC, Alena-deriv commented on cypress/e2e/wip/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    cy.get('[class="dc-text balance-text__text--real"]', {
This is changed as suggested

2024-06-07 10:09 UTC, Alena-deriv commented on cypress/e2e/wip/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    cy.get('[class="dc-dialog__dialog"]').should(
Changed to `cy.get('.dc-dialog__dialog')` as was not able to use testing library locator here

2024-06-07 10:10 UTC, Alena-deriv commented on cypress/e2e/wip/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    cy.get('[class="dc-modal-body"]').should('be.visible') // checks Trade is unavailable
Changed to `cy.get('.dc-modal-body')` as was not able to use testing library locator here

2024-06-10 05:40 UTC, meeyun-deriv approved these changes
LGTM

2024-06-10 05:43 UTC, abuzar-deriv approved these changes
LGTM

2024-06-10 05:46 UTC, merged