Create Cypress test QATEST-123731 ---  POI switching(Failing IDV x 2 >> Onfido x 1 >> manual upload)
deriv-com/e2e-deriv-app pull request #232
Opened 2024-04-18 13:27 UTC by bertrand-deriv

### Create Cypress test QATEST-123731 ---  POI switching(Failing IDV x 2 >> Onfido x 1 >> manual upload)
- In this PR, I have developed the POI switching tests. The scenario is like this: Failing IDV x2 will redirect to Onfido x1 and then will redirect to manual upload.
- It's almost similar to  Deborah's changes in her [PR](https://github.com/deriv-com/e2e-deriv-app/pull/217)
- I'm using the `c_createRealAccount` command to create test account on the go!!

2024-04-22 10:34 UTC, abuzar-deriv requested changes

2024-04-22 10:34 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/idvPoiSwitching.cy.js
> +    )
Shouldn't this be a cypress command since it's being used in `cypress/e2e/wip/KYC/onfidoFailTwice.cy.js` test as well?

2024-04-22 10:34 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    cy.findByText('Proof of address required').should('be.visible')
We have a generic utility `c_waitUntilElementIsFound` now. Can you please try to use it with lesser wait time? You may modify it if needed to close notification header.

2024-04-22 10:34 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    cy.findByText('Please upload one of the following documents:').should(
Same for this.

2024-04-23 08:28 UTC, bertrand-deriv commented on cypress/e2e/wip/KYC/idvPoiSwitching.cy.js
> +    )
yes you are right.... let me use the command instead

2024-04-23 08:28 UTC, bertrand-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    cy.findByText('Proof of address required').should('be.visible')
yes.. let me take a look 👍

2024-04-23 13:42 UTC, bertrand-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    cy.findByText('Proof of address required').should('be.visible')
@abuzar-deriv  Can you tell me where i can find it. Probably i'll need to pull latest changes from master into my branch

2024-04-24 02:27 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/onfidoFailTwice.cy.js
> +    cy.findByText('Proof of address required').should('be.visible')
Hola @bertrand-deriv; yes, it will need latest master.

2024-04-30 03:56 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/idvPoiSwitching.cy.js
> +    cy.findByText('Please upload one of the following documents:').should(
Redundant assertion. If this text is not found, `c_waitUntilElementIsFound` will throw error after max retries.

2024-04-30 07:57 UTC, bertrand-deriv commented on cypress/e2e/wip/KYC/idvPoiSwitching.cy.js
> +    cy.findByText('Please upload one of the following documents:').should(
yeah
you are right... its kinda redundant.. let me remove it

2024-05-02 08:13 UTC, abuzar-deriv approved these changes
LGTM

2024-05-03 06:57 UTC, bilalmajid-deriv approved these changes

2024-05-03 07:09 UTC, markodonnell-deriv approved these changes
Looks good

2024-05-03 07:11 UTC, merged