Crypto account
deriv-com/e2e-deriv-app pull request #233
Opened 2024-04-19 08:43 UTC by vimalan-deriv

In this testcase we have added checks to check on the deposit flow of all cryptocurrency to ensure that the address and QR code in deposit page are generated. 

Clickup card to refer: https://app.clickup.com/t/86bxa0c1w

2024-04-22 10:22 UTC, abuzar-deriv requested changes
Left some comments related to test description and locators.

2024-04-22 10:22 UTC, abuzar-deriv commented on cypress/e2e/wip/Crypto/crypto_deposit_check.cy.js
> +describe('QATEST-707 - Create crypto account', () => {
Linked card links to QATEST-715. Please update the description. If required, you may merge both tests if they share functionality.

2024-04-22 10:22 UTC, abuzar-deriv commented on cypress/e2e/wip/Crypto/crypto_deposit_check.cy.js
> +      cy.xpath('//canvas[contains(@class,"qrcode")]').then(($canvas) => {
Can you please use `cy.get("canvas[class*='qrcode']")` instead? XPath usage is not recommended and must be an exception.

2024-04-22 10:22 UTC, abuzar-deriv commented on cypress/e2e/wip/Crypto/crypto_deposit_check.cy.js
> +      cy.findAllByTestId('dt_traders_hub_home_button').click()
Does this work? If it's finding multiple elements, please specify by index which element you want to click. If not, please use findByTestId. OR, use click({multiple:true}) if you're trying to click multiple elements.

2024-04-22 10:22 UTC, abuzar-deriv commented on cypress/e2e/wip/Crypto/crypto_deposit_check.cy.js
> +  it('should be able to create crypto account from Traders Hub.', () => {
Same as above for this.

2024-04-24 05:09 UTC, abuzar-deriv approved these changes
LGTM.

2024-04-30 03:49 UTC, meeyun-deriv requested changes

2024-04-30 03:49 UTC, meeyun-deriv commented on cypress.config.js
> +        PSWD: process.env.E2E_CRYPTO_PASSWORD,
can replace this with `E2E_QA_ACCOUNT_PASSWORD`

2024-04-30 03:49 UTC, meeyun-deriv commented on cypress/e2e/wip/Crypto/crypto_deposit_check.cy.js
> +        cy.get('.deposit-crypto-wallet-address__hash-container')
quite some elements are using classname, did we create a card to let dev to update the locators with best practice?

2024-04-30 08:52 UTC, meeyun-deriv commented on cypress/e2e/wip/Crypto/crypto_deposit_check.cy.js
> +        cy.get('.deposit-crypto-wallet-address__hash-container')
locator will get update in this card https://app.clickup.com/t/86byjmgdg

2024-05-03 06:37 UTC, markodonnell-deriv approved these changes
Looks good

2024-05-03 06:48 UTC, merged