Improving api account creation functionality
deriv-com/e2e-deriv-app pull request #239
Opened 2024-04-22 16:14 UTC by bertrand-deriv

### Improving api account creation functionality
In this PR, 
- I have done some improvements to the api account creation functions so that we can be able to re-run successfully the tests that use `c_createRealAccount` command in one cypress session. Before, it used to throw timeout error because no api calls were being made.
- I have refactored the function to use cypress command instead of playwright for **getting verification code** from the events url. If you check well, I'm using the new command `c_emailVerificationV2` but it's almost similar to `c_emailVerification` already existing.

2024-04-22 17:46 UTC, markodonnell-deriv requested changes
Just some minor comments. Good job.

2024-04-22 17:46 UTC, markodonnell-deriv commented on cypress/e2e/api/createAccountAndLogin.cy.js
> +    cy.log('<E2EOAuthUrl - Test >' + Cypress.env('oAuthUrl'))
Might be a good idea to log some of the credentials data here.

2024-04-22 17:46 UTC, markodonnell-deriv commented on cypress/support/commands/common.js
> +    cy.task('createRealAccountTask').then(() => {
Could we have a try catch finally here, just incase we get an exception as the WS needs to alway disconnect and should go in the finally..

2024-04-23 05:37 UTC, abuzar-deriv reviewed
Some minor comments. Looks great overall 💯

2024-04-23 05:37 UTC, abuzar-deriv commented on cypress.config.js
> +          if (connection && connection.readyState === WebSocket.OPEN) {
Can you please shorten it to following for brevity?
```suggestion
          if(connection?.readyState === WebSocket.OPEN) {
```

2024-04-23 05:37 UTC, abuzar-deriv commented on cypress.config.js
> +          if (connection && connection.readyState === WebSocket.OPEN) {
Same here:
```suggestion
          if (connection?.readyState === WebSocket.OPEN) {
```

2024-04-23 07:49 UTC, bertrand-deriv commented on cypress/e2e/api/createAccountAndLogin.cy.js
> +    cy.log('<E2EOAuthUrl - Test >' + Cypress.env('oAuthUrl'))
Which ones would you recommend to log ? like an email ??

2024-04-23 07:50 UTC, bertrand-deriv commented on cypress/support/commands/common.js
> +    cy.task('createRealAccountTask').then(() => {
yeah
That's right. Let me do it

2024-04-23 10:12 UTC, markodonnell-deriv approved these changes
Looks good

2024-04-24 02:24 UTC, abuzar-deriv approved these changes

2024-04-24 02:24 UTC, merged