P2P - Fixed Rate - Edit Existing Ad Details - Edit Ad
deriv-com/e2e-deriv-app pull request #246
Opened 2024-04-25 03:04 UTC by usman-deriv

- This is for Fixed Rate type advert
- It will edit an existing ad

**Mode of run:** 

1. Cleanup (delete existing ad)
2. Create an ad successfully
3. Edit the newly existing ad.
4. Verify details after successfully saving the advert. 

[Clickup Card](https://app.clickup.com/t/20696747/P2PS-2426)

![image](https://github.com/deriv-com/e2e-deriv-app/assets/152943428/a1cca36d-fe84-4535-8118-9d6be4e82c83)

2024-04-25 05:09 UTC, bilalmajid-deriv commented on cypress/e2e/wip/P2P/editFixedAdDetails.cy.js
> +    cy.c_visitResponsive('/appstore/traders-hub', 'small')
is it important that you navigate to this url ?

2024-04-25 05:12 UTC, usman-deriv commented on cypress/e2e/wip/P2P/editFixedAdDetails.cy.js
> +    cy.c_visitResponsive('/appstore/traders-hub', 'small')
Yes, as per the test scenario, I am supposed to login and then navigate to My ads tab after login. Just a fine check that P2P is navigable.

2024-04-25 05:14 UTC, bilalmajid-deriv approved these changes

2024-04-25 08:25 UTC, meeyun-deriv requested changes

2024-04-25 08:25 UTC, meeyun-deriv commented on cypress/e2e/wip/P2P/editFixedAdDetails.cy.js
> +      cy.c_verifyCompletionOrderDropdown()
These validations already covered in `createAdBuyFixedRate.cy.js`, so I think we can remove from this test and focus on edit ad only

2024-04-25 08:25 UTC, meeyun-deriv commented on cypress/e2e/wip/P2P/editFixedAdDetails.cy.js
> +      cy.get('.my-ads-table__row .dc-dropdown-container')
have we create a card for FE dev to improve this locator?

2024-04-25 08:25 UTC, meeyun-deriv commented on cypress/e2e/wip/P2P/editFixedAdDetails.cy.js
> +      cy.findByText(`${(minOrder + 1).toFixed(2)} - ${maxOrder.toFixed(2)} USD`)
how about checking the updated order duration?

2024-04-25 08:25 UTC, meeyun-deriv commented on cypress/e2e/wip/P2P/editFixedAdDetails.cy.js
> +    cy.clearAllLocalStorage()
I think we should delete all existing ad in the `beforeEach` because the test might be running multiple times. So from the 2nd times onwards, the account will contain the edited ad which has the condition ``${(minOrder + 1).toFixed(2)} - ${maxOrder.toFixed(2)} USD`)`.

if the edit ad function has bug and does not save the new change properly, then the test will still report as pass because it can use the existing old ad as the validation.

2024-04-26 02:25 UTC, usman-deriv commented on cypress/e2e/wip/P2P/editFixedAdDetails.cy.js
> +      cy.findByText(`${(minOrder + 1).toFixed(2)} - ${maxOrder.toFixed(2)} USD`)
Added in this card -> https://app.clickup.com/t/20696747/P2PS-2596

2024-04-26 02:25 UTC, usman-deriv commented on cypress/e2e/wip/P2P/editFixedAdDetails.cy.js
> +      cy.get('.my-ads-table__row .dc-dropdown-container')
Added in this card -> https://app.clickup.com/t/20696747/P2PS-2596

2024-04-26 02:26 UTC, usman-deriv commented on cypress/e2e/wip/P2P/editFixedAdDetails.cy.js
> +      cy.findByText(`${(minOrder + 1).toFixed(2)} - ${maxOrder.toFixed(2)} USD`)
After saving changes, we do not see the order duration in the My Ads screen for that order. 😞

2024-04-26 02:30 UTC, usman-deriv commented on cypress/e2e/wip/P2P/editFixedAdDetails.cy.js
> +    cy.clearAllLocalStorage()
Yes this is what my test is doing but the deletion part is happening in the `it` block rather that `beforeEach` as I have pre-reqs happening before deleting the ads, (closing notification, accepting safety instructions, navigating to My ads screen)
I am deleting all the existing ads in my test prior to creating one and editing it. Hence, if my test fails in the midst of testing, it will delete all the existing ads again and hence start from creating a new ad from scratch.

2024-04-26 02:32 UTC, usman-deriv commented on cypress/e2e/wip/P2P/editFixedAdDetails.cy.js
> +      cy.c_verifyCompletionOrderDropdown()
Addressed in new commit. 👍🏼

2024-04-26 03:22 UTC, meeyun-deriv approved these changes
LGTM

2024-04-26 03:22 UTC, meeyun-deriv commented on cypress/e2e/wip/P2P/editFixedAdDetails.cy.js
> +      cy.findByText(`${(minOrder + 1).toFixed(2)} - ${maxOrder.toFixed(2)} USD`)
update - the duration check has been added by opening the ad again

2024-04-26 03:23 UTC, merged