P2P - Fixed Rate - Delete Ad
deriv-com/e2e-deriv-app pull request #250
Opened 2024-04-26 08:36 UTC by usman-deriv

Test will do the following:

1. If ad exists, it will delete it and the test ends. 

3. If no ad exists, it will create a new ad and then delete it and the test ends. 

This has been catered to not always create ad and do deletion. And to decrease time of test run.

2024-04-26 14:39 UTC, markodonnell-deriv approved these changes
Looks good

2024-04-30 05:19 UTC, bilalmajid-deriv requested changes
Some changes requested

2024-04-30 05:19 UTC, bilalmajid-deriv commented on cypress/support/commands/p2p.js
> +  cy.findByTestId('dt_initial_loader').should('not.exist')
We already have a command for this as c_loadingCheck

2024-04-30 05:19 UTC, bilalmajid-deriv commented on cypress/support/commands/p2p.js
> +      return 1 // Ads found
Return bool values true or false here.

2024-04-30 05:19 UTC, bilalmajid-deriv commented on cypress/e2e/wip/P2P/deleteAdFixedRate.cy.js
> +    cy.c_checkForExistingAds().then((returnedValue) => {
make name more meaningful
```suggestion
    cy.c_checkForExistingAds().then((adExists) => {
```

2024-04-30 05:19 UTC, bilalmajid-deriv commented on cypress/e2e/wip/P2P/deleteAdFixedRate.cy.js
> +      if (returnedValue === 0) {
```suggestion
      if (adExists == false) {
```

2024-04-30 05:19 UTC, bilalmajid-deriv commented on cypress/e2e/wip/P2P/deleteAdFixedRate.cy.js
> +          cy.c_removeExistingAds()
this can be moved otside of the if else block as it is common for both if else condition 

and remove the else condition 

the test would then work as :

IF (ad does not exist) {
create add 
}
delete add

2024-04-30 06:10 UTC, usman-deriv commented on cypress/support/commands/p2p.js
> +  cy.findByTestId('dt_initial_loader').should('not.exist')
This is done

2024-04-30 06:10 UTC, usman-deriv commented on cypress/support/commands/p2p.js
> +      return 1 // Ads found
Using true and false for boolean returns

2024-04-30 06:11 UTC, usman-deriv commented on cypress/e2e/wip/P2P/deleteAdFixedRate.cy.js
> +    cy.c_checkForExistingAds().then((returnedValue) => {
This has been changed for better readability.

2024-04-30 06:11 UTC, usman-deriv commented on cypress/e2e/wip/P2P/deleteAdFixedRate.cy.js
> +      if (returnedValue === 0) {
This has been changed for better readability.

2024-04-30 06:11 UTC, usman-deriv commented on cypress/e2e/wip/P2P/deleteAdFixedRate.cy.js
> +          cy.c_removeExistingAds()
This has been edited as suggested, thank you.

2024-04-30 06:15 UTC, bilalmajid-deriv approved these changes
LGTM

2024-04-30 06:16 UTC, merged