Responsive tests for CR, MF, and DIEL account signup
deriv-com/e2e-deriv-app pull request #251
Opened 2024-04-26 09:23 UTC by abuzar-deriv

- https://app.clickup.com/t/20696747/QATEST-5533
- https://app.clickup.com/t/20696747/QATEST-5554
- https://app.clickup.com/t/20696747/QATEST-5569
- https://app.clickup.com/t/20696747/QATEST-5827
- https://app.clickup.com/t/20696747/QATEST-6211
- https://app.clickup.com/t/20696747/QATEST-24427

2024-04-26 14:32 UTC, markodonnell-deriv commented on cypress/support/commands/tradersHub.js
> +      // cy.c_visitResponsive(Cypress.env('verificationUrl'), size)
Please remove comment

2024-04-29 02:36 UTC, abuzar-deriv commented on cypress/support/commands/tradersHub.js
> +      // cy.c_visitResponsive(Cypress.env('verificationUrl'), size)
Done.

2024-04-29 06:27 UTC, markodonnell-deriv approved these changes
Look good.

2024-04-29 06:36 UTC, abuzar-deriv commented on cypress/support/commands/tradersHub.js
> +    if (isMobile) cy.findByTestId('date_of_birth').type('2006-02-09')
Sure @markodonnell-deriv, I can do it once the tests are stable.

2024-04-30 03:45 UTC, bilalmajid-deriv requested changes
One minor change requested

2024-04-30 03:45 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Tradershub/accountSignupMF.cy.js
> +          { isMobile: size == 'small' ? true : false }
why not specify this at the start of the test the way you ar doing it in other spec files.
for all occurrences in this file

2024-04-30 03:51 UTC, abuzar-deriv commented on cypress/e2e/wip/Tradershub/accountSignupMF.cy.js
> +          { isMobile: size == 'small' ? true : false }
Had overlooked it. Updated.

2024-04-30 04:42 UTC, bilalmajid-deriv approved these changes
LGTM

2024-04-30 04:50 UTC, merged