transferCRtoMT5
deriv-com/e2e-deriv-app pull request #259
Opened 2024-04-29 14:18 UTC by infanta-deriv

Card - https://app.clickup.com/t/20696747/TRAH-3124 , https://app.clickup.com/t/20696747/TRAH-3123

This PR has code for transfer from CR (with and without account balance)  to MT5

2024-04-29 14:27 UTC, markodonnell-deriv requested changes
Question abotu env var

2024-04-29 14:27 UTC, markodonnell-deriv commented on cypress/e2e/wip/Tradershub/transferCRToMT5.cy.js
> +    Cypress.env('oAuthUrl', '<empty>')
How come you're setting this empty?
Note, you shouldn't expect the first test to run before the second.

2024-04-29 15:10 UTC, infanta-deriv commented on cypress/e2e/wip/Tradershub/transferCRToMT5.cy.js
> +    Cypress.env('oAuthUrl', '<empty>')
i set this empty , because otherwise it was using the same user login from my first test case . 
Both test cases should have different login accounts for its different scenarios  . That is why i had to set the oauthURL as empty , so that it will take a fresh login .

2024-04-30 03:39 UTC, meeyun-deriv submitted a review, later dismissed
Can we also include mobile test? we should prioritize mobile test first

2024-04-30 08:48 UTC, abuzar-deriv commented on cypress/e2e/wip/Tradershub/transferCRToMT5.cy.js
> +    Cypress.env('oAuthUrl', '<empty>')
@infanta-deriv , you may remove this from here. I've added the logic inside c_login https://github.com/deriv-com/e2e-deriv-app/pull/262. Thanks for noticing this. 🙇

2024-04-30 16:26 UTC, markodonnell-deriv commented on cypress/e2e/wip/Tradershub/transferCRToMT5.cy.js
> +    Cypress.env('oAuthUrl', '<empty>')
Thank you both!

2024-04-30 16:27 UTC, markodonnell-deriv approved these changes
Looks good

2024-05-02 05:25 UTC, bilalmajid-deriv approved these changes
LGTM

2024-05-02 05:40 UTC, abuzar-deriv approved these changes

2024-05-03 06:32 UTC, markodonnell-deriv approved these changes
Looks good

2024-05-03 06:36 UTC, merged