Afsaneh/add responsive
deriv-com/e2e-deriv-app pull request #265
Opened 2024-05-01 07:39 UTC by afsaneh-rezaeinejad-deriv

2024-05-01 07:52 UTC, markodonnell-deriv approved these changes
Looks good

2024-05-02 03:12 UTC, lubega-deriv approved these changes

2024-05-02 06:48 UTC, afsaneh-rezaeinejad-deriv commented on cypress/e2e/wip/Wallets/cryptoTransactions.cy.js
> +  cy.contains('Transfer fees:')
no it doesn't work as transfer fee might vary we can't use the full text

2024-05-02 06:49 UTC, afsaneh-rezaeinejad-deriv commented on cypress/e2e/wip/Wallets/demoResetBalance.cy.js
> +    cy.contains('Reset balance', { timeout: 10000 }).should('be.visible')
I tried earlier @abuzar-deriv unfortunately it didn't work with findByText()

2024-05-02 07:08 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/mt5.cy.js
> +import '@testing-library/cypress/add-commands'
@afsaneh-rezaeinejad-deriv , was this test added just now? Ideally there shouldn't be such new additions in the PR, and if there're any, a review should be requested again from all approvers since the earlier approvals were for older changes. 🙏

2024-05-02 07:10 UTC, abuzar-deriv requested changes

2024-05-02 07:10 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/mt5.cy.js
> +    // })
Can you please remove the commented out code?

2024-05-02 07:19 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/mt5.cy.js
> +import '@testing-library/cypress/add-commands'
File removed. Was accidentally added.

2024-05-02 07:19 UTC, abuzar-deriv approved these changes

2024-05-02 07:28 UTC, merged