charts popup
deriv-com/e2e-deriv-app pull request #27
Opened 2023-12-11 15:06 UTC by anitha-deriv

Handling Charts after logging in - Dtrader page.

2023-12-12 11:12 UTC, markodonnell-deriv requested changes

2023-12-12 11:12 UTC, markodonnell-deriv commented on cypress.config.js
> -    fiatOnrampAppId: process.env.E2E_FIAT_ONRAMP_APPID,
Should we be removing the fiatOnrampAppId environment variable?

2023-12-12 12:01 UTC, anitha-deriv commented on cypress.config.js
> -    fiatOnrampAppId: process.env.E2E_FIAT_ONRAMP_APPID,
Hi @markodonnell-deriv , This environmental variable got changed recently. Lubega was addressing that he needs it. should we retain the onrampConfigAppId variable?

2023-12-12 12:03 UTC, anitha-deriv commented
Verified the code locally with and without popup 
1. test-app.deriv.com(Deriv app -current prod behavior - without Popup) 
2. https://new-charts1.binary.sx - the new testlink (having the popup)
<img width="1792" alt="Screenshot 2023-12-12 at 2 53 39 PM" src="https://github.com/deriv-com/e2e-deriv-app/assets/115210942/71497914-f9de-4f0c-a86a-85a68ee95f78">
<img width="1792" alt="Screenshot 2023-12-12 at 3 55 16 PM" src="https://github.com/deriv-com/e2e-deriv-app/assets/115210942/2d4fd0c6-4a58-436f-babc-a25eb8841ac1">

2023-12-12 12:12 UTC, markodonnell-deriv commented on cypress.config.js
> -    fiatOnrampAppId: process.env.E2E_FIAT_ONRAMP_APPID,
I think it could be could shared between your test and @lubega-deriv 's ?

2023-12-12 13:15 UTC, markodonnell-deriv commented on cypress.config.js
> -    fiatOnrampAppId: process.env.E2E_FIAT_ONRAMP_APPID,
As discussed, I've understood and am happy with this change now.

2023-12-12 13:15 UTC, markodonnell-deriv approved these changes
Looks good

2023-12-13 02:27 UTC, merged

2023-12-13 05:00 UTC, anitha-deriv commented on cypress.config.js
> -    fiatOnrampAppId: process.env.E2E_FIAT_ONRAMP_APPID,
thank you @markodonnell-deriv