Log in from deriv.com dbot and redirect to app.deriv.com/bot
deriv-com/e2e-deriv-app pull request #276
Opened 2024-05-08 05:49 UTC by thivya-deriv

This card is to log in from deriv app dbot page and redirect to app.deriv.com/bot
Card: https://app.clickup.com/t/20696747/BOT-1658

`Note: This is only done for prod atm as for staging there are still some changes to be done on db`

2024-05-08 07:31 UTC, abuzar-deriv requested changes

2024-05-08 07:31 UTC, abuzar-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +    cy.c_visitResponsive('https://deriv.com', 'dektop')
Better to use env var `derivComProdURL` instead of hard-coding the url here.

2024-05-08 07:31 UTC, abuzar-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +      cy.wait(3000)
Why the wait?

2024-05-08 07:31 UTC, abuzar-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +      cy.get('input[id="txtEmail"]')
Can you please try using this instead?
```suggestion
      cy.findByLabel('Email')
```

2024-05-08 07:31 UTC, abuzar-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +      cy.get('input[id="txtPass"]')
Can you please try using this instead?
```suggestion
      cy.findByLabel('Password')
```

2024-05-08 07:31 UTC, abuzar-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +  })
Is this small it block really needed? Can it be merged with the previous block?
https://wikijs.deriv.cloud/en/Quality-Assurance/e2e-test-automation
<img width="1092" alt="image" src="https://github.com/deriv-com/e2e-deriv-app/assets/132635598/0e08385a-6c4e-420d-a849-72fc591ca742">

2024-05-08 10:09 UTC, abuzar-deriv approved these changes
LGTM

2024-05-09 10:30 UTC, markodonnell-deriv approved these changes
Looks good

2024-05-10 05:49 UTC, meeyun-deriv requested changes

2024-05-10 05:49 UTC, meeyun-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +    cy.c_visitResponsive(Cypress.env('derivComProdURL'), 'desktop')
we can visit bot page (`${Cypress.env('derivComProdURL')}/dbot) here as we are not validating the navigation from header menu

2024-05-10 05:49 UTC, meeyun-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +        .type(Cypress.env('credentials').production.dBot.ID)
```suggestion
cy.findByLabelText('Email').type(Cypress.env('credentials').production.dBot.ID)
```

2024-05-10 05:49 UTC, meeyun-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +        .type(Cypress.env('credentials').production.dBot.PSWD)
```suggestion
cy.findByLabelText('Email').type(Cypress.env('credentials').production.dBot.PWSD)
```

2024-05-10 05:49 UTC, meeyun-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +      cy.c_visitResponsive(`${Cypress.env('derivComProdURL')}/dbot`, 'desktop')
why we need to visit dbot page after login? this test should make sure the login landed on dbot page automatically

2024-05-10 05:49 UTC, meeyun-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +        .click()
```suggestion
cy.findByRole('button', { name: 'Log in' }).click()
```

2024-05-10 06:08 UTC, thivya-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +        .click()
@meeyun-deriv this was added so upon clicking log in > app.deriv.com/bot url will be opened on the same tab instead of opening a new tab.

2024-05-10 06:08 UTC, thivya-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +      cy.c_visitResponsive(`${Cypress.env('derivComProdURL')}/dbot`, 'desktop')
> why we need to visit dbot page after login? this test should make sure the login landed on dbot page automatically

@meeyun-deriv here i want to check on Go to live demo functionalities from deriv.com/dbot as well.

Previously i had it on 2 seperate it block , but @abuzar-deriv mentioned to add it under one block instead.

2024-05-10 06:31 UTC, meeyun-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +        .click()
but currently the login button will open login page in the same tab. Why we need to specifically do that?

2024-05-10 06:31 UTC, meeyun-deriv commented on cypress/e2e/wip/dbot/regression-tests/LogInFromDerivCom.cy.js
> +      cy.c_visitResponsive(`${Cypress.env('derivComProdURL')}/dbot`, 'desktop')
ok i got your point now, it is going back to deriv.com to check the logged in behaviour.

2024-05-14 01:40 UTC, meeyun-deriv approved these changes
LGTM

2024-05-14 01:40 UTC, merged