Skip fake link pop up banner for brazil client
deriv-com/e2e-deriv-app pull request #281
Opened 2024-05-10 04:01 UTC by thivya-deriv

Card: https://app.clickup.com/t/20696747/BOT-1718

2024-05-15 05:54 UTC, bilalmajid-deriv approved these changes

2024-05-15 07:12 UTC, markodonnell-deriv approved these changes
Looks good

2024-05-15 07:40 UTC, meeyun-deriv requested changes
can we also log the cookie value in the initial steps of the test? this can help us for future debugging if the pop up is appearing in non-Brazil countries.

2024-05-15 07:58 UTC, abuzar-deriv commented on cypress/support/commands/common.js
> +    if (cookie && cookie.value === expectedCookieValue) {
Can you try with this? Just for simplicity :)
```suggestion
    if (cookie?.value === expectedCookieValue) {
```

2024-05-16 01:46 UTC, meeyun-deriv approved these changes
LGTM

2024-05-16 01:46 UTC, meeyun-deriv commented
Please help to resolve conflicts

2024-05-16 02:35 UTC, abuzar-deriv approved these changes
LGTM

2024-05-16 02:35 UTC, merged