Creating a different branch with same code as the rajendra/checkBalan…
deriv-com/e2e-deriv-app pull request #284
Opened 2024-05-10 19:26 UTC by rajendra-deriv

…ce was having merge conflicts beyond corrections

2024-05-13 08:55 UTC, markodonnell-deriv requested changes

2024-05-13 08:55 UTC, markodonnell-deriv commented on cypress.config.js
> +    appRegisterHomePage: process.env.E2E_APP_REGISTER_HOMEPAGE,
This is the PR Url? So probably best to just rename 'HOMEPAGE' TO 'URL'

2024-05-13 08:55 UTC, markodonnell-deriv commented on cypress/support/commands/common.js
> +  cy.wait(1000)
You should need waits here. See best practises documentation.

2024-05-13 08:55 UTC, markodonnell-deriv commented on cypress/support/helper/loginUtility.js
> +            confirm_scopes: 'read,trade,payments,trading_information,admin',
Having changed this. Have you tested that a standard QA account still gets auto-authorized?

2024-05-13 10:41 UTC, rajendra-deriv commented on cypress.config.js
> +    appRegisterHomePage: process.env.E2E_APP_REGISTER_HOMEPAGE,
Renamed

2024-05-13 10:46 UTC, rajendra-deriv commented on cypress/support/commands/common.js
> +  cy.wait(1000)
Removed the waits

2024-05-13 10:48 UTC, rajendra-deriv commented on cypress/support/helper/loginUtility.js
> +            confirm_scopes: 'read,trade,payments,trading_information,admin',
Checked /oAuthLogin.cy.js . Was working fine when executed

2024-05-13 10:51 UTC, markodonnell-deriv requested changes

2024-05-13 10:51 UTC, markodonnell-deriv commented on cypress.config.js
> +    appRegisterHomePage: process.env.E2E_APP_REGISTER_URL,
Can you rename appRegisterHomePage to appRegisterUrl too?

2024-05-13 10:52 UTC, markodonnell-deriv commented on cypress/support/helper/loginUtility.js
> +            confirm_scopes: 'read,trade,payments,trading_information,admin',
You would have had to create a new account first. Did you do that?

2024-05-13 11:03 UTC, rajendra-deriv commented on cypress.config.js
> +    appRegisterHomePage: process.env.E2E_APP_REGISTER_URL,
Updated The name to appRegisterUrl

2024-05-13 11:07 UTC, markodonnell-deriv approved these changes

2024-05-13 11:07 UTC, markodonnell-deriv commented on cypress/support/commands/common.js
> +        Cypress.env('newAppId', token)
You're setting the token to the newAppId. This looks like an old bug

2024-05-13 11:50 UTC, markodonnell-deriv requested changes
Just the c_login issue now

2024-05-13 12:38 UTC, rajendra-deriv commented on cypress/support/commands/common.js
> +        Cypress.env('newAppId', token)
Removed the lines 
        const urlParams = new URLSearchParams(Cypress.env('oAuthUrl'))
        const token = urlParams.get('token1')
        Cypress.env('newAppId', token)
        cy.log('getOAuthUrl : The Auth Token is :' + Cypress.env('newAppId'))

2024-05-13 12:39 UTC, markodonnell-deriv approved these changes
Looks good now

2024-05-13 13:00 UTC, markodonnell-deriv requested changes

2024-05-13 13:00 UTC, markodonnell-deriv commented on cypress/support/commands/common.js
> +    const authAppId = Cypress.env('newAppId')
This is wrong, surely this should be token, not appId

2024-05-13 13:36 UTC, markodonnell-deriv requested changes

2024-05-13 13:36 UTC, markodonnell-deriv commented on cypress/e2e/api/createApplicationRegister.cy.js
> +    cy.c_login() // Here Login is required as we need Auth ID for running RegisterApplication API. We are updating the 'configAppId' with 'newAppId'
This comment is wrong, we need a need an auth token and we're saving the token retrieved in c_login to .oAuthToken

2024-05-13 13:45 UTC, markodonnell-deriv requested changes

2024-05-13 13:45 UTC, markodonnell-deriv commented on cypress/support/commands/common.js
> +    Cypress.env('oAuthToken', oAuthNewToken)
This line doesn't make sense. Please remove.

2024-05-13 13:45 UTC, markodonnell-deriv commented on cypress.config.js
> +          process.env.E2E_OAUTH_TOKEN  = authToken
You  don't need this here. Please remove.

2024-05-13 13:52 UTC, rajendra-deriv commented on cypress/support/helper/loginUtility.js
> +            confirm_scopes: 'read,trade,payments,trading_information,admin',
Run  oAuthLogin.cy.js with qa10.deriv.dev and 1007 which was working.
Run createApplicationRegister.cy.js and newly created an APP Id, Now run oAuthLogin.cy.js with TestLink URL and AppID and it was working.

2024-05-13 13:53 UTC, rajendra-deriv commented on cypress/support/commands/common.js
> +    const authAppId = Cypress.env('newAppId')
Removed the variable as per comment.

2024-05-13 13:54 UTC, markodonnell-deriv requested changes

2024-05-13 13:54 UTC, markodonnell-deriv commented on cypress/support/commands/common.js
> +    Cypress.prevAppId = appId
You probably need to use Cypress.env to set the var. As above.

2024-05-13 13:54 UTC, markodonnell-deriv commented on cypress/support/commands/common.js
> +    newApplicationId = appId
What's this for? It's not declared and doesn't get used.

2024-05-13 14:14 UTC, rajendra-deriv commented on cypress/e2e/api/createApplicationRegister.cy.js
> +    cy.c_login() // Here Login is required as we need Auth ID for running RegisterApplication API. We are updating the 'configAppId' with 'newAppId'
Updated the comments

2024-05-13 14:14 UTC, rajendra-deriv commented on cypress/support/commands/common.js
> +    Cypress.env('oAuthToken', oAuthNewToken)
Removed

2024-05-13 14:14 UTC, rajendra-deriv commented on cypress.config.js
> +          process.env.E2E_OAUTH_TOKEN  = authToken
Removed

2024-05-13 14:15 UTC, rajendra-deriv commented on cypress/support/commands/common.js
> +    Cypress.prevAppId = appId
Cypress.prevAppId is a local variable, so using it to assign the appId

2024-05-13 14:17 UTC, markodonnell-deriv requested changes

2024-05-13 14:17 UTC, markodonnell-deriv commented on cypress/support/commands/common.js
> +    // Cypress.env('oAuthToken', oAuthNewToken)
Please remove comment

2024-05-13 15:35 UTC, markodonnell-deriv requested changes
The wsConnects and wsDisconnects are generally in the wrong places. Which leads me to wonder if they're necessary, if your code is working without them, on occasion.

2024-05-13 15:35 UTC, markodonnell-deriv commented on cypress/e2e/api/createApplicationRegister.cy.js
> +    cy.c_wsConnect()
Wrong place got this

2024-05-13 15:35 UTC, markodonnell-deriv commented on cypress/e2e/api/createApplicationRegister.cy.js
> +    cy.c_wsDisconnect()
Wrong place

2024-05-13 15:35 UTC, markodonnell-deriv commented on cypress/e2e/api/createApplicationRegister.cy.js
> +      cy.c_wsConnect()
Unnecessary connect. c_login doesn't use websockets.

2024-05-14 06:33 UTC, meeyun-deriv requested changes

2024-05-15 05:48 UTC, rajendra-deriv commented on cypress/support/commands/common.js
> +    // Cypress.env('oAuthToken', oAuthNewToken)
Removed

2024-05-15 05:49 UTC, rajendra-deriv commented on cypress/e2e/api/createApplicationRegister.cy.js
> +    cy.c_wsConnect()
Updated

2024-05-15 05:49 UTC, rajendra-deriv commented on cypress/e2e/api/createApplicationRegister.cy.js
> +    cy.c_wsDisconnect()
Updated

2024-05-15 05:50 UTC, rajendra-deriv commented on cypress/e2e/api/createApplicationRegister.cy.js
> +      cy.c_wsConnect()
Moved c_login before wsConnect

2024-05-15 05:51 UTC, rajendra-deriv commented on cypress/support/helper/applicationRegister.js
> + * @returns 4-digit random runber
Updated :)

2024-05-15 05:52 UTC, rajendra-deriv commented on cypress/e2e/api/createApplicationRegister.cy.js
> +      cy.c_login()
We are using the Login to get the Auth Key. But after we create a New App Id, to test we are login with that app id and testlink URL.

2024-05-15 05:56 UTC, rajendra-deriv commented on cypress.config.js
> +        let registerRedirectURI = process.env.E2E_APP_REGISTER_URL + '/redirect'
Hi Meeyun, We will pass the Testlink URL from GH Actions parameter into E2E_APP_REGISTER_URL for FE execution.

2024-05-15 07:38 UTC, meeyun-deriv requested changes

2024-05-15 07:38 UTC, meeyun-deriv commented on cypress/e2e/api/createApplicationRegister.cy.js
> +      cy.c_login()
oh I see the reason now. Since this is API test, I think we should not validate it through UI. Just checking on the API response and status will be sufficient.

One a side note - the `c_login` is not able to validate if the login is using the newly created app id, because it has a logic to decide which app id to use based on the URL and app. Thus, it will overwrite the app id that you set in the previous step.

2024-05-15 07:40 UTC, markodonnell-deriv commented on cypress/e2e/api/createApplicationRegister.cy.js
> +      cy.c_login()
Just to quality, WS calls need Auth Tokens (more accurate term than Auth Key). You are only getting token1 but hopefully this isn't an issue Rajendra.

2024-05-15 07:43 UTC, markodonnell-deriv requested changes
Remove commented line.

2024-05-15 07:43 UTC, markodonnell-deriv commented on cypress/support/commands/common.js
> +    // Cypress.prevAppId = appId
Remove this line. Best practise is to removed unnecessary commented lines.

2024-05-15 07:50 UTC, rajendra-deriv commented on cypress/support/commands/common.js
> + * Method to Register a New Apllication ID
Updated

2024-05-15 07:58 UTC, rajendra-deriv commented on cypress/support/commands/common.js
> +    // Cypress.prevAppId = appId
Done Mark

2024-05-15 08:02 UTC, rajendra-deriv commented on cypress/e2e/api/createApplicationRegister.cy.js
> +      cy.c_login()
Sure Mark, I have made all necessary changes as per the review comments. Initially i made the same suggestion to minimize UI interactions as less as possible. I will work on it to make UI interactions just for necessary actions like the one for ApplicationRegister.

2024-05-15 09:28 UTC, markodonnell-deriv approved these changes
Looks good

2024-05-15 09:57 UTC, meeyun-deriv approved these changes
LGTM

2024-05-15 09:58 UTC, merged