update
deriv-com/e2e-deriv-app pull request #305
Opened 2024-05-21 10:27 UTC by afsaneh-rezaeinejad-deriv

after changes of [this card](https://app.clickup.com/t/20696747/WALL-3964) is merged, onbaording test is failing, cypress code should be updated based on new changes
CU card: https://app.clickup.com/t/20696747/WALL-4097

2024-05-21 20:30 UTC, markodonnell-deriv requested changes

2024-05-21 20:30 UTC, markodonnell-deriv commented on cypress/e2e/wip/Wallets/onboarding.cy.js
> +  cy.wait(800)
Is this definitely needed? :)

2024-05-23 07:42 UTC, meeyun-deriv approved these changes
LGTM (other than the 800 as commented by Mark)

2024-05-23 12:14 UTC, markodonnell-deriv approved these changes
Looks good

2024-05-23 12:19 UTC, markodonnell-deriv approved these changes
Looks good

2024-05-23 12:19 UTC, merged