Afsaneh/check migration
deriv-com/e2e-deriv-app pull request #310
Opened 2024-05-23 11:07 UTC by afsaneh-rezaeinejad-deriv

2024-05-23 13:49 UTC, markodonnell-deriv requested changes
typo

2024-05-23 13:49 UTC, markodonnell-deriv commented on cypress.config.js
> +        PSWD: process.env.E2E_DERIV_PASSWOR
Missing the D in E2E_DERIV_PASSWOR

2024-05-24 04:02 UTC, abuzar-deriv approved these changes
LGTM

2024-05-24 04:58 UTC, bilalmajid-deriv approved these changes
LGTM

2024-05-24 07:25 UTC, markodonnell-deriv approved these changes
Looks good

2024-05-24 07:34 UTC, merged