Adding Passkeys Folder in Smoke and Adding Basic Passkeys Button Veri…
deriv-com/e2e-deriv-app pull request #314
Opened 2024-05-24 07:08 UTC by rajendra-deriv

Adding Passkeys Folder in Smoke and Adding Basic Passkeys Button Verification on Login page

2024-05-24 07:41 UTC, markodonnell-deriv requested changes
Some comments

2024-05-24 07:41 UTC, markodonnell-deriv commented on cypress/e2e/smoke/Passkeys/passkeys.cy.js
> +    Cypress.env('stdConfigAppId', Cypress.env('passkeyAppId'))
I wouldn't override the stdConfigAppId as that could affect other tests.

2024-05-24 07:41 UTC, markodonnell-deriv commented on cypress/e2e/smoke/Passkeys/passkeys.cy.js
> +        Cypress.env('passkeyUrl') + '?app_id=' + Cypress.env('stdConfigAppId')
Just use the passkeyAppId here.

2024-05-24 08:23 UTC, rajendra-deriv commented on cypress/e2e/smoke/Passkeys/passkeys.cy.js
> +    Cypress.env('stdConfigAppId', Cypress.env('passkeyAppId'))
Removed the assignment.

2024-05-24 08:24 UTC, rajendra-deriv commented on cypress/e2e/smoke/Passkeys/passkeys.cy.js
> +        Cypress.env('passkeyUrl') + '?app_id=' + Cypress.env('stdConfigAppId')
using passkeyAppId directly

2024-05-24 08:32 UTC, markodonnell-deriv requested changes

2024-05-24 08:32 UTC, markodonnell-deriv commented on cypress/e2e/smoke/Passkeys/passkeys.cy.js
> +      cy.visit(
Put this path in c_visitRepsonsive and you won't need the second visit.
Also, surely you need a login?

2024-05-24 11:19 UTC, markodonnell-deriv approved these changes
Looks good

2024-05-27 02:19 UTC, bilalmajid-deriv approved these changes

2024-05-27 02:28 UTC, bilalmajid-deriv requested changes
Can you pleas cover all of these steps as well for web version
![image](https://github.com/deriv-com/e2e-deriv-app/assets/155507124/214e3418-dde0-425b-8d48-11a6846ef8f3)

2024-05-29 05:21 UTC, meeyun-deriv requested changes

2024-05-29 05:21 UTC, meeyun-deriv commented on cypress/e2e/smoke/Passkeys/passkeys.cy.js
> +        cy.get('a#btnPasskeys.button.passkey-btn').should('not.exist')
can we use `findByLabel('Login with passkeys')` or `findByText('Passkey')` for consistency?

2024-05-29 05:21 UTC, meeyun-deriv commented on cypress/e2e/smoke/Passkeys/passkeys.cy.js
> +describe('QATEST - 142511, QATEST - 125330 - Passkeys Login Page Button Check', () => {
Please help to update the test case custom id to `QATEST-142511` and `QATEST-125330` (without spaces before and after the `-`) for easier grep in future

2024-05-29 05:21 UTC, meeyun-deriv commented on cypress.config.js
> +    passkeyAppId: process.env.E2E_PASSKEY_APP_ID,
can you please share the values through LP? so we can add this into GH secret?

2024-06-03 05:35 UTC, rajendra-deriv commented on cypress/e2e/smoke/Passkeys/passkeys.cy.js
> +        cy.get('a#btnPasskeys.button.passkey-btn').should('not.exist')
Updated the code as per comments.

2024-06-03 05:36 UTC, rajendra-deriv commented on cypress/e2e/smoke/Passkeys/passkeys.cy.js
> +describe('QATEST - 142511, QATEST - 125330 - Passkeys Login Page Button Check', () => {
Updated as per these changes.

2024-06-03 05:38 UTC, rajendra-deriv commented
Hi @bilalmajid-deriv , I have update these steps as per QATEST-125357 test case. The older one needs implementation. So the scope of this test case is good to go.

2024-06-04 03:51 UTC, bilalmajid-deriv approved these changes

2024-06-04 09:00 UTC, meeyun-deriv approved these changes
LGTM

2024-06-04 09:00 UTC, merged