Indu/wallets
deriv-com/e2e-deriv-app pull request #317
Opened 2024-05-24 14:06 UTC by indulekha-deriv

2024-05-24 15:30 UTC, indulekha-deriv commented on cypress/support/commands/common.js
Earlier we were using only 1 wallet account. For Wallet migration cases we need to pass multiple accounts.

2024-05-24 15:40 UTC, markodonnell-deriv approved these changes
Looks OK to me in principle. 
I've added @bilalmajid-deriv and @abuzar-deriv to the review list as @meeyun-deriv and I are OOH till Tuesday and they will be covering.
I've also, add @afsaneh-rezaeinejad-deriv as I saw a similar PR from her recently, just incase there's any conflict.

2024-05-25 07:24 UTC, indulekha-deriv commented on cypress/support/helper/loginUtility.js
> +  } //else {
Removed this else condition to ensure getWalletOAuthUrl does not always log in with E2E_DERIV_LOGIN_WALLET.

2024-05-27 07:13 UTC, bilalmajid-deriv requested changes
left comments

2024-05-27 07:13 UTC, bilalmajid-deriv commented on cypress.config.js
> +      walletMigrationnewClient: {
```suggestion
      walletMigrationNewClient: {
```

2024-05-27 07:13 UTC, bilalmajid-deriv commented on cypress.config.js
> +      walletMigrationwithoutVRTC: {
```suggestion
      walletMigrationWithoutVRTC: {
```

2024-05-27 07:13 UTC, bilalmajid-deriv commented on cypress.config.js
> +      walletMigrationnoCurrency: {
```suggestion
      walletMigrationNoCurrency: {
```

2024-05-27 07:13 UTC, bilalmajid-deriv commented on cypress.config.js
> +      walletMigrationonUSD: {
```suggestion
      walletMigratioNonUSD: {
```

2024-05-27 07:13 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/migrationIneligibleNewuser.cy.js
> +    cy.c_login({ app: 'wallets', user: 'walletMigrationnewClient' })
```suggestion
    cy.c_login({ app: 'wallets', user: 'walletMigrationNewClient' })
```

2024-05-27 07:13 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/migrationIneligibleNoCurrency.cy.js
> +    cy.c_login({ app: 'wallets', user: 'walletMigrationnoCurrency' })
```suggestion
    cy.c_login({ app: 'wallets', user: 'walletMigrationNoCurrency' })
```

2024-05-27 07:13 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/migrationIneligibleNonUSD.cy.js
> +    cy.c_login({ app: 'wallets', user: 'walletMigrationonUSD' })
```suggestion
    cy.c_login({ app: 'wallets', user: 'walletMigratioNonUSD' })
```

2024-05-27 07:13 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/migrationIneligiblePA.cy.js
> +    cy.c_checkForbanner()
```suggestion
    cy.c_checkForBanner()
```
Do same for all instances

2024-05-27 07:13 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/migrationIneligibleVRTC.cy.js
> +    cy.c_login({ app: 'wallets', user: 'walletMigrationwithoutVRTC' })
```suggestion
    cy.c_login({ app: 'wallets', user: 'walletMigrationWithoutVRTC' })
```

2024-05-27 07:13 UTC, bilalmajid-deriv commented on cypress/support/helper/loginUtility.js
> +  } //else {
Is this else condition required later on if not can remove thanks.

2024-05-27 07:19 UTC, afsaneh-rezaeinejad-deriv commented on cypress/support/commands/wallets.js
> +  cy.c_visitResponsive('/appstore/traders-hub' , 'large')
before verifying wallet banner, add a condition to make sure page is loaded completely, "Buy or sell at a specific time for a specific price" is common between wallet and non-wallet tradershub

2024-05-27 07:19 UTC, abuzar-deriv requested changes

2024-05-27 07:19 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/migrationIneligibleVRTC.cy.js
> +describe('QATEST-153921 -  Client  VRTC', () => {
Typo: Should be QATEST-153921 - Client without VRTC

2024-05-27 07:19 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/migrationIneligibleVRTC.cy.js
> +  it('Client without VRTC', () => {
Lang needs update. It block should mention what's expected behaviour

2024-05-27 07:19 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/migrationIneligibleVRTC.cy.js
> +  it('Client with only VRTC', () => {
Lang needs update. It block should mention what's expected behaviour

2024-05-27 07:19 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/migrationineligibleP2P.cy.js
> +  it('Client with USD more than 3 months, but P2P registered', () => {
Lang needs update. It block should mention what's expected behaviour

2024-05-27 07:19 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/migrationIneligiblePA.cy.js
> +  it('Client used PA service in recent 3 months, joined more than 3 months', () => {
Lang needs update. It block should mention what's expected behaviour

2024-05-27 07:19 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/migrationIneligibleNonUSD.cy.js
> +  it('Client with Non-USD curency', () => {
Lang needs update. It block should mention what's expected behaviour

2024-05-27 07:19 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/migrationIneligiblePA.cy.js
> +  it('Client with USD more than 3 months & Payment agent', () => {
Lang needs update. It block should mention what's expected behaviour

2024-05-27 07:19 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/migrationIneligibleNoCurrency.cy.js
> +  it('Client without currency added', () => {
Lang needs update. It block should mention what's expected behaviour

2024-05-27 07:19 UTC, abuzar-deriv commented on cypress/e2e/wip/Wallets/migrationIneligibleNewuser.cy.js
> +  it('Client with USD for less than 3 months', () => {
Lang needs update. It block should mention what's expected behaviour. i.e. Should or should't see the banner.

2024-05-27 07:19 UTC, abuzar-deriv commented on cypress/support/helper/loginUtility.js
> +  } //else {
getWalletOAuthUrl looks redundant now. It's usage should be replaced with getOAuthUrl since it looks to be doing pretty much the same thing now. c_login will also need minor update in that case. Background: It was created by @afsaneh-rezaeinejad-deriv , when c_login() didn't have multi-user support, but it's no longer needed. Ideally should be done in this PR itself just not to make the code more convoluted but can be done separately as well if these changes are urgent. But in that case pleae create a card.

2024-05-27 07:19 UTC, abuzar-deriv commented on cypress/support/commands/wallets.js
> +Cypress.Commands.add('c_checkForbanner', () =>{
```suggestion
Cypress.Commands.add('c_checkForBanner', () =>{
```

2024-05-27 08:31 UTC, indulekha-deriv commented on cypress/support/helper/loginUtility.js
> +  } //else {
We already have a task added for this. Will work on it separate.

2024-05-27 09:52 UTC, bilalmajid-deriv approved these changes
LGTM

2024-05-27 10:00 UTC, afsaneh-rezaeinejad-deriv commented on cypress/support/commands/common.js
> +    loginEmail,
@indulekha-deriv can we apply this change to all of the 6 tests

2024-06-04 03:43 UTC, meeyun-deriv approved these changes
LGTM

2024-06-04 04:29 UTC, afsaneh-rezaeinejad-deriv requested changes

2024-06-04 04:29 UTC, afsaneh-rezaeinejad-deriv commented on cypress.config.js
> +        PSWD: process.env.E2E_DERIV_PASSWORD,
@indulekha-deriv can you please use E2E_QA_ACCOUNT_PASSWORD instead of E2E_DERIV_PASSWORD
as we prefer not to hard coded password in our cypress_setup script, these accounts are all created with "E2E_QA_ACCOUNT_PASSWORD"

2024-06-04 04:40 UTC, abuzar-deriv approved these changes
LGTM; pending password update in config file.

2024-06-04 07:25 UTC, indulekha-deriv commented on cypress.config.js
> +        PSWD: process.env.E2E_DERIV_PASSWORD,
Updated to E2E_QA_ACCOUNT_PASSWORD

2024-06-04 08:19 UTC, afsaneh-rezaeinejad-deriv approved these changes

2024-06-04 08:21 UTC, merged