mt5 fundtransfer usd to usd
deriv-com/e2e-deriv-app pull request #32
Opened 2023-12-26 12:51 UTC by ravali-deriv

MT5 fund transfer, both deposit and withdrawal, USD to USD

card : https://app.clickup.com/t/20696747/CFDS-2826

2023-12-26 13:31 UTC, ravali-deriv commented
This is successful execution of mt5 fundtransfer
<img width="1728" alt="Screenshot 2023-12-26 at 6 59 26 PM" src="https://github.com/deriv-com/e2e-deriv-app/assets/106730390/796ea9ff-b717-411d-9926-60dc6b8df8c3">

2023-12-29 01:43 UTC, meeyun-deriv requested changes

2023-12-29 01:43 UTC, meeyun-deriv commented on cypress/e2e/wip/mt5/fundtransfer.cy.js
> +    cy.get('[class="dc-dropdown-container account-transfer-form__drop-down"]').should("be.visible").click()
lets not use class, use the testing library queries instead - https://testing-library.com/docs/cypress-testing-library/intro/. Please update all the locator to use testing library queries if possible.

2023-12-29 01:43 UTC, meeyun-deriv commented on cypress/support/e2e.js
> +
remove this changes as this is not needed

2023-12-29 01:43 UTC, meeyun-deriv commented on cypress/e2e/wip/mt5/fundtransfer.cy.js
> +  let fiataccount='US Dollar'
standardize the naming convention, it should be `fiatAccount`. Please check across the entire PR on the naming convention.

Same for file name too, please update `fundtransfer.cy.js` to `fundTransfer.cy.js`

2023-12-29 01:43 UTC, meeyun-deriv commented on cypress/e2e/wip/mt5/tradersHub.cy.js
> +describe('QATEST-5778, QATEST-5781, QATEST-5615', () => {
where is QATEST-5778 and QATEST-5781 coming from? I cant seem to find them in Clickup

2023-12-29 01:43 UTC, meeyun-deriv commented on cypress/e2e/wip/mt5/fundtransfer.cy.js
> +    cy.c_visitResponsive('/appstore/traders-hub', 'large')
why do we handle the desktop view and not responsive first?

2024-01-02 12:27 UTC, ravali-deriv commented on cypress/e2e/wip/mt5/fundtransfer.cy.js
> +  let fiataccount='US Dollar'
This is done

2024-01-02 12:30 UTC, ravali-deriv commented on cypress/e2e/wip/mt5/tradersHub.cy.js
> +describe('QATEST-5778, QATEST-5781, QATEST-5615', () => {
I have changed this to correct description

2024-01-09 14:34 UTC, markodonnell-deriv approved these changes

2024-01-10 06:23 UTC, ravali-deriv commented
closing this PR because I have created a new PR for this task 
new PR - https://github.com/deriv-com/e2e-deriv-app/pull/44
card - https://app.clickup.com/t/20696747/CFDS-2826

2024-01-10 06:24 UTC, closed without merging