Check on Summary tab
deriv-com/e2e-deriv-app pull request #324
Opened 2024-05-27 09:12 UTC by thivya-deriv

Card: https://app.clickup.com/t/20696747/BOT-1663
Description : Just a small check to ensure that the summary panel is working as expected when bot is run/stopped.

2024-05-27 09:44 UTC, bilalmajid-deriv approved these changes
LGTM

2024-05-27 09:55 UTC, maliheh-deriv approved these changes

2024-05-28 01:06 UTC, abuzar-deriv requested changes

2024-05-28 01:06 UTC, abuzar-deriv commented on cypress/support/commands/dBot.js
> +        .find('[data-testid="dt_span"]')
Why not findByTestId()?

2024-05-28 01:34 UTC, thivya-deriv commented on cypress/support/commands/dBot.js
> +        .find('[data-testid="dt_span"]')
Abuzar the dt_span is being used in multiple places hence why i did not use that.

2024-05-28 05:26 UTC, abuzar-deriv commented on cypress/support/commands/dBot.js
> +        .find('[data-testid="dt_span"]')
Doesn't matter. Once you chain with parent(), findByTestId() should find only that element.

2024-05-28 06:17 UTC, meeyun-deriv approved these changes
LGTM but please check Abuzar latest comment

2024-05-28 08:57 UTC, merged