Added e2e to check self exclusion max trade option
deriv-com/e2e-deriv-app pull request #336
Opened 2024-05-31 04:34 UTC by zain-deriv

# Summary 
Added e2e to check self exclusion max trade option for both Options and Multipliers trade types

# Ticket
https://app.clickup.com/t/20696747/CSIT-933

# Notes
Using different account for both trade types to avoid rate limit issue as both tests executes for mobile and desktop resolutions

![image](https://github.com/deriv-com/e2e-deriv-app/assets/167836892/27f7fafa-938d-4b89-a260-30b0f53c4bdb)

2024-05-31 04:36 UTC, faezeh-deriv approved these changes
LGTM 🚀

2024-05-31 05:11 UTC, abuzar-deriv requested changes
Left some comments.

2024-05-31 05:11 UTC, abuzar-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +    isLanguageTest: true,
Why true? This sets a session value c_rateLimitOccurred. Are you using it somewhere?

2024-05-31 05:11 UTC, abuzar-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      cy.contains('button', 'Open').eq(0).click()
Can you please try:
```suggestion
      cy.findAllByRole('button', {name:'Open'}).first().click()
```

2024-05-31 05:11 UTC, abuzar-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      cy.contains('button', 'Open').eq(0).click()
Same comment as above for this.

2024-05-31 05:11 UTC, abuzar-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +        cy.log('CLOSE THE TRADE PANEL ON MOBILE RESOLTION')
Typo:
```suggestion
        cy.log('CLOSE THE TRADE PANEL ON MOBILE RESOLUTION')
```

2024-05-31 05:11 UTC, abuzar-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      cy.contains('button', 'Open').eq(0).click()
Same comment as above for this.

2024-05-31 05:12 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      }
any particular reason to add this over here? As I see only one test and it will always result in log in with selfExclusionOptions.

2024-05-31 05:12 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      cy.c_clearTrades()
should we not clear trades before running test?

2024-05-31 05:13 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +    isLanguageTest: true,
the isLanguageTest should remain false is only valid for one particular test case.

2024-05-31 06:13 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      }
missed the second it

2024-05-31 06:14 UTC, zain-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      }
I'm using two separate users here, there are 2 tests @bilalmajid-deriv

2024-05-31 06:15 UTC, zain-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      cy.c_clearTrades()
Its been used in beforeEach hook as well. Calling its again after the final trade count assertion

2024-05-31 06:36 UTC, zain-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +    isLanguageTest: true,
Updated to false

2024-05-31 06:37 UTC, zain-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      cy.contains('button', 'Open').eq(0).click()
Done

2024-05-31 06:37 UTC, zain-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +        cy.log('CLOSE THE TRADE PANEL ON MOBILE RESOLTION')
Done

2024-05-31 06:37 UTC, zain-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      cy.contains('button', 'Open').eq(0).click()
Done

2024-05-31 06:43 UTC, zain-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      cy.contains('button', 'Open').eq(0).click()
Done

2024-05-31 06:56 UTC, abuzar-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +    isLanguageTest: true,
It's already set to false by default. Better to just remove this ` isLanguageTest: true,`line in this case.

2024-05-31 07:01 UTC, zain-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +    isLanguageTest: true,
Updated @abuzar-deriv

2024-05-31 07:36 UTC, abuzar-deriv approved these changes
LGTM

2024-05-31 09:11 UTC, markodonnell-deriv requested changes
Have you checked to see whether there was a testing library function available you've used css id selector, eg. #dt_contract_turboslong_item

I assume you have tried, given that line 89 is using a testing library function?  : cy.findByTestId('dt_contract_dropdown').click()

This is the recommended priority list: vhttps://testing-library.com/docs/queries/about/#priority

The playwright recorder is pretty good at picking the top priority functions.

2024-05-31 09:11 UTC, markodonnell-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      cy.get('#dt_contract_turboslong_item').should('be.visible')
Is a testing library function available here? And others like it?

2024-05-31 09:37 UTC, zain-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      cy.get('#dt_contract_turboslong_item').should('be.visible')
The data-testid used for this element was not unique, and same for all trade options so opted for using the ID instead since its unique and work both resolutions. 
![image](https://github.com/deriv-com/e2e-deriv-app/assets/167836892/226240ae-dcf5-414a-a371-21e05a88a4c0)

2024-06-03 15:02 UTC, markodonnell-deriv approved these changes
Looks good

2024-06-04 05:03 UTC, meeyun-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionMaxLimit.cy.js
> +      cy.get('#dt_contract_turboslong_item').should('be.visible')
@markodonnell-deriv since this is part of the Dtrader which will go through new UI changes, so I opt for using whatever is available for now to validate the self exclusion open position behaviour.

2024-06-04 05:04 UTC, meeyun-deriv approved these changes
LGTM

2024-06-04 05:14 UTC, meeyun-deriv approved these changes
LGTM

2024-06-04 05:14 UTC, merged