Testing POA Verified and POA rejected scenario
deriv-com/e2e-deriv-app pull request #337
Opened 2024-05-31 11:24 UTC by bertrand-deriv

### Testing POA Verified and POA rejected scenario
- created tests for the POA verified scenario
- created tests for the POA rejected scenario
- created utility function for date generation

2024-06-03 15:12 UTC, markodonnell-deriv requested changes
Do these tests need to be in separate spec file?
They look quite similar and could be differnet it()'s within the same describe and the common steps could be shared within a function in the same spec file?

2024-06-03 15:59 UTC, markodonnell-deriv requested changes
Also, c_createRealAccount set env vars which I've been meaning to review before we use it in e2e tests. I think it might impact other tests.
As you wrote it, would you mind double-checking that?

2024-06-04 10:11 UTC, markodonnell-deriv commented
> Also, c_createRealAccount set env vars which I've been meaning to review before we use it in e2e tests. I think it might impact other tests. As you wrote it, would you mind double-checking that?

Disregard this now, as per discussions.

2024-06-04 10:14 UTC, markodonnell-deriv approved these changes
Looks good.

2024-06-05 02:26 UTC, meeyun-deriv requested changes

2024-06-05 02:26 UTC, meeyun-deriv commented on cypress/e2e/wip/KYC/poaVerifyAndReject.cy.js
> +const BO_URL = `https://${Cypress.env('configServer')}/d/backoffice/login.cgi`
put the BO URL in env var as well

2024-06-05 10:58 UTC, bertrand-deriv commented on cypress/e2e/wip/KYC/poaVerifyAndReject.cy.js
> +const BO_URL = `https://${Cypress.env('configServer')}/d/backoffice/login.cgi`
I have implemented it

2024-06-05 11:02 UTC, meeyun-deriv approved these changes
LGTM

2024-06-05 11:02 UTC, merged