Check on quick strategy run using Mobile
deriv-com/e2e-deriv-app pull request #338
Opened 2024-06-03 05:08 UTC by thivya-deriv

Desc: This is a test to run quick strategies using responsive 
Card: https://app.clickup.com/t/20696747/BOT-1738

2024-06-03 15:14 UTC, markodonnell-deriv approved these changes
Looks good

2024-06-04 04:43 UTC, abuzar-deriv requested changes
Minor text update needed.

2024-06-04 04:43 UTC, abuzar-deriv commented on cypress/e2e/wip/dbot/sanity-tests/QuickStrategies.cy.js
> +    it(`Run Martingale Quick Strategy ${size == 'small' ? 'mobile' : 'desktop'}`, () => {
```suggestion
    it(`Run Martingale Quick Strategy on ${size == 'small' ? 'mobile' : 'desktop'}`, () => {
```

2024-06-04 06:39 UTC, abuzar-deriv approved these changes
LGTM

2024-06-04 07:43 UTC, merged