trade account switcher
deriv-com/e2e-deriv-app pull request #339
Opened 2024-06-03 18:36 UTC by indulekha-deriv

this PR is to add wallet test case for Trder page account switcher https://app.clickup.com/t/20696747/QATEST-129858

2024-06-03 20:36 UTC, markodonnell-deriv approved these changes
Looks good

2024-06-04 04:55 UTC, abuzar-deriv commented on cypress/e2e/wipWallet/tradepageAccountswticher.cy.js
> +      '.acc-switcher-wallet-item__content',
Since the first arg `'.acc-switcher-wallet-item__content'` is the same across all function calls, why not use it as a local variable inside function?

2024-06-04 08:53 UTC, indulekha-deriv commented on cypress/e2e/wipWallet/tradepageAccountswticher.cy.js
> +      '.acc-switcher-wallet-item__content',
Fixed and have renamed test to have better meaning.

2024-06-04 08:59 UTC, abuzar-deriv approved these changes
LGTM

2024-06-05 02:01 UTC, meeyun-deriv reviewed
why this test is put in wip folder?

2024-06-06 06:46 UTC, indulekha-deriv commented
> why this test is put in wip folder?

@meeyun-deriv It was suggested that to add new test cases in WIP folder and later to smoke folder.

2024-06-10 02:25 UTC, afsaneh-rezaeinejad-deriv requested changes

2024-06-10 02:25 UTC, afsaneh-rezaeinejad-deriv commented on cypress/e2e/wipWallet/accountSwitcher.cy.js
> +  cy.get('.wallets-deriv-apps-section__title-and-badge')
this class name is updated

2024-06-10 09:48 UTC, indulekha-deriv commented on cypress/e2e/wipWallet/accountSwitcher.cy.js
> +  cy.get('.wallets-deriv-apps-section__title-and-badge')
This is fixed

2024-06-10 09:53 UTC, afsaneh-rezaeinejad-deriv approved these changes

2024-06-10 10:52 UTC, meeyun-deriv approved these changes
LGTM

2024-06-10 10:52 UTC, merged