Feed Verification on dbot for Responsive
deriv-com/e2e-deriv-app pull request #340
Opened 2024-06-04 08:31 UTC by thivya-deriv

Card: https://app.clickup.com/t/20696747/BOT-1739
Desc: Add check to verify feed on dbot using responsive.

2024-06-04 09:19 UTC, markodonnell-deriv requested changes

2024-06-04 09:19 UTC, markodonnell-deriv commented on cypress/e2e/wip/dbot/sanity-tests/FeedVerification.cy.js
>        cy.c_createRealAccount()
Bertrand needs to make a minor change to c_createRealAccount. So, you'd have to wait until this is completed unfortunately.

2024-06-04 14:18 UTC, markodonnell-deriv approved these changes
Looks good

2024-06-04 14:18 UTC, markodonnell-deriv commented on cypress/e2e/wip/dbot/sanity-tests/FeedVerification.cy.js
>        cy.c_createRealAccount()
Disregard this comment now, as discussed :)

2024-06-05 02:06 UTC, meeyun-deriv approved these changes
LGTM

2024-06-05 02:07 UTC, merged