Add USD Trading account
deriv-com/e2e-deriv-app pull request #357
Opened 2024-06-07 08:48 UTC by zubair-deriv

### Card
https://app.clickup.com/t/20696747/WALL-4244

2024-06-07 14:21 UTC, markodonnell-deriv approved these changes
Looks good

2024-06-10 01:45 UTC, afsaneh-rezaeinejad-deriv requested changes

2024-06-10 01:45 UTC, afsaneh-rezaeinejad-deriv commented on cypress/support/commands/wallets.js
> +    })
@zubair-deriv can you modify this command to switch to USD wallet if its needed, also better to make is generic

2024-06-11 03:27 UTC, abuzar-deriv reviewed
Some questions..

2024-06-11 03:27 UTC, abuzar-deriv commented on cypress/support/commands/wallets.js
> +          cy.wait(300)
Why this wait?

2024-06-11 03:27 UTC, abuzar-deriv commented on cypress/support/commands/wallets.js
> +      cy.log('inside then')
Is this log needed? Looks more like something needed for debugging only.

2024-06-11 03:27 UTC, abuzar-deriv commented on cypress/e2e/smoke/Wallets/addTradingAccount.cy.js
> +
Can you please add testid for this?

2024-06-11 03:31 UTC, zubair-deriv commented on cypress/support/commands/wallets.js
> +          cy.wait(300)
In responsive view, the carousel switched to USD so quickly, that even assertion on dom element is not enough to setup a trading account due to which I have to add this wait

2024-06-11 03:33 UTC, zubair-deriv commented on cypress/support/commands/wallets.js
> +      cy.log('inside then')
correct. It was added while debugging. 
I have removed this log.

2024-06-11 03:35 UTC, zubair-deriv commented on cypress/e2e/smoke/Wallets/addTradingAccount.cy.js
> +
Updated

2024-06-12 06:51 UTC, zubair-deriv commented
I am closing this PR, as this would not be a valid use case after migration.

2024-06-12 06:51 UTC, closed without merging