Translation/branch
deriv-com/e2e-deriv-app pull request #365
Opened 2024-06-10 12:05 UTC by infanta-deriv

2024-06-11 02:13 UTC, maliheh-deriv commented on cypress/support/commands/tradersHub.js
> +  cy.wait(2000)
please add justification why we need hard sleep here.

2024-06-11 02:14 UTC, maliheh-deriv commented on cypress/support/commands/common.js
> +          //cy.findAllByText("Trader's Hub").last().should('be.visible')
please remove the commented line

2024-06-11 02:15 UTC, maliheh-deriv commented on cypress/support/commands/common.js
> +        //cy.findAllByText("Trader's Hub").last().should('be.visible')
please remove the commented line

2024-06-11 06:43 UTC, infanta-deriv commented on cypress/support/commands/tradersHub.js
> +  cy.wait(2000)
when executing at times it was failing due to loading issue , so i added it to prevent failures due to flakiness . Here we are checking in all languages in both desktop and mobile so this sometimes slows the execution and fails

2024-06-11 07:22 UTC, maliheh-deriv approved these changes

2024-06-11 09:35 UTC, abuzar-deriv requested changes

2024-06-11 09:35 UTC, abuzar-deriv commented on cypress/support/commands/tradersHub.js
> +  cy.findByText(langChangeCheck).should('be.visible')
Why the wait? Won't the line below wait by default for a few seconds?

2024-06-11 09:35 UTC, abuzar-deriv commented on cypress/support/commands/tradersHub.js
> +Cypress.Commands.add('checkHyperLinks', (language, isMobile = false) => {
```suggestion
Cypress.Commands.add('c_checkHyperLinks', (language, isMobile = false) => {
```

2024-06-11 09:35 UTC, abuzar-deriv commented on cypress/support/commands/tradersHub.js
> +  cy.wait(1000)
Why not wait for any DOM element instead of this?

2024-06-11 09:35 UTC, abuzar-deriv commented on cypress/support/commands/tradersHub.js
> +})
What's the purpose of calling just one command inside another command?

2024-06-11 09:35 UTC, abuzar-deriv commented on cypress/support/commands/tradersHub.js
> +const validateLink = (
Can't it be custom command instead of function?

2024-06-11 09:35 UTC, abuzar-deriv commented on cypress/support/commands/tradersHub.js
> +function clickCompareAccounts(language) {
Can't it be custom command instead of function?

2024-06-11 09:35 UTC, abuzar-deriv commented on cypress/support/commands/tradersHub.js
> +function clickAndGetTerms(language, bviCFD, vanuatuCFD, labuanCFD, isMobile) {
Can't it be custom command instead of function?

2024-06-11 11:19 UTC, infanta-deriv commented on cypress/support/commands/tradersHub.js
> +})
This function is not needed , added before my mistake . removing it

2024-06-12 03:46 UTC, abuzar-deriv requested changes
Needs a few minor changes.

2024-06-12 03:46 UTC, abuzar-deriv commented on cypress/support/commands/tradersHub.js
> +            cy.go('back')
Need an assertion here for content otherwise test will be flaky.

2024-06-12 03:46 UTC, abuzar-deriv commented on cypress/support/commands/tradersHub.js
> +            cy.go('back')
Same here; needs an assertion here for content otherwise test will be flaky.

2024-06-12 03:46 UTC, abuzar-deriv commented on cypress/support/commands/common.js
> +          cy.findByTestId('dt_traders_hub').should('be.visible')
Please change it back to as it was in master (`cy.findAllByText("Trader's Hub").should('have.length', '2')`)

2024-06-12 03:46 UTC, abuzar-deriv commented on cypress/support/commands/common.js
> +        cy.findByTestId('dt_traders_hub').should('be.visible')
Same here.

2024-06-12 07:48 UTC, meeyun-deriv approved these changes
The code LGTM, but can you also run the test in github action to make sure the tests are fine? Then attach the result in this PR

2024-06-13 05:21 UTC, abuzar-deriv approved these changes
LGTM

2024-06-13 05:23 UTC, merged