These are end to end tests that covered CR Low risk client
deriv-com/e2e-deriv-app pull request #371
Opened 2024-06-11 10:44 UTC by deborah-deriv

**End to End tests for CR Low risk**

1. These are end-to-end tests that demonstrate that no cashier locks applicable to the CR low-risk client.
2. I have covered the E2E test for the manual upload form

2024-06-13 09:31 UTC, markodonnell-deriv approved these changes
Looks good

2024-06-14 08:58 UTC, abuzar-deriv requested changes
Looks good in general (apart from a minor request), but I'm assuming there will be lot of tests accessing BO in future. We should create a custom command for it instead of keeping inside test.

2024-06-14 08:58 UTC, abuzar-deriv commented on cypress/e2e/wip/KYC/poiExpireCrLow.cy.js
> +    cy.c_visitResponsive('/')
Please remove this line as it's already there inside `c_createRealAccount().`

2024-06-14 08:58 UTC, abuzar-deriv commented on cypress/support/commands/kyc.js
> -  }
@usman-deriv , can you review this change?

2024-06-14 09:04 UTC, usman-deriv requested changes

2024-06-14 09:04 UTC, usman-deriv commented on cypress/support/commands/kyc.js
> -  }
This is an optional parameter and required in P2P. It will have no effect on your code @deborah-deriv. Kindly do not remove this.

2024-06-18 07:20 UTC, usman-deriv commented on cypress/e2e/wip/KYC/poiExpireCrLow.cy.js
> +    //cy.c_visitResponsive('/')
Please remove the commented code line.

2024-06-18 07:22 UTC, usman-deriv commented on cypress/e2e/wip/KYC/poiExpireCrLow.cy.js
> +
Please remove whitespace.

2024-06-18 07:23 UTC, usman-deriv commented on cypress/e2e/wip/KYC/poiExpireCrLow.cy.js
> +
Please remove whitespace.

2024-06-18 07:23 UTC, usman-deriv commented on cypress/e2e/wip/KYC/poiExpireCrLow.cy.js
> +
Please remove whitespace.

2024-06-18 07:23 UTC, usman-deriv commented on cypress/e2e/wip/KYC/poiExpireCrLow.cy.js
> +
Please remove whitespace.

2024-06-18 07:25 UTC, usman-deriv commented on cypress/e2e/wip/KYC/poiExpireCrLow.cy.js
> +  it('No cashier lock when POI expire for CR low risk', () => {
Can make the it's string a little more descriptive like "it('Should .... no cashier lock when POI expire for CR low risk', ()" something like this.

2024-06-18 08:46 UTC, usman-deriv approved these changes
LGTM

2024-06-18 09:08 UTC, abuzar-deriv approved these changes
LGTM

2024-06-18 09:09 UTC, merged