Improve KYC tests
deriv-com/e2e-deriv-app pull request #372
Opened 2024-06-11 11:16 UTC by bertrand-deriv

### Improve KYC tests
- Added random name to names used in idv tests
- Added a reset name function to the `IdvVerified.cy.js` test
- Improved some assertions

2024-06-13 09:30 UTC, markodonnell-deriv approved these changes
Looks good

2024-06-14 09:00 UTC, bilalmajid-deriv requested changes
left a comment

2024-06-26 12:19 UTC, bertrand-deriv commented on cypress/e2e/smoke/KYC/idvPoiVerified.cy.js
> +  })
@bilalmajid-deriv Since there are some discussion going on regarding this changes and how we can solve this better... I'll close it for now

2024-06-26 12:23 UTC, bertrand-deriv commented
Closing this PR as we are going to find an improved way on how to solve this problem. I have created a separate PR for the other changes implemented in this PR.

2024-06-26 12:23 UTC, closed without merging