Thivya/update yml
deriv-com/e2e-deriv-app pull request #38
Opened 2024-01-08 06:00 UTC by thivya-deriv

2024-01-08 10:22 UTC, markodonnell-deriv requested changes
Just a path change and also can you remove the extra lines in the 4 sanity tests files. Unless it was intended?

2024-01-08 10:22 UTC, markodonnell-deriv commented on .github/workflows/cypress_cloud_manual.yml
> +        - wip/bot
I've just just it should be dbot not bot :) And you will need to add the /sanity-tests folder to the path too

2024-01-08 14:02 UTC, markodonnell-deriv approved these changes
Looks good

2024-01-09 03:04 UTC, meeyun-deriv approved these changes
LGTM

2024-01-09 03:04 UTC, merged