CSIT-913 BO steps and mobile view steps for Self Exclusion test
deriv-com/e2e-deriv-app pull request #380
Opened 2024-06-13 06:42 UTC by Alena-deriv

Completed all steps for https://app.clickup.com/t/20696747/CSIT-913 (subtask https://app.clickup.com/t/20696747/CSIT-1120)
Changes made:
1. BO steps are added
2. Mobile view steps are added
3. Rearranged test steps to be logically divided (like /* Sets self exclusion on FE */)
4. Moved test from wip folder to smoke since all steps cases are automated

<img width="1724" alt="Screenshot 2024-06-13 at 09 35 13" src="https://github.com/deriv-com/e2e-deriv-app/assets/153058266/75f07c93-127c-4285-b529-62a42766ceeb">

2024-06-13 09:39 UTC, markodonnell-deriv approved these changes
Looks good.

2024-06-14 09:12 UTC, bilalmajid-deriv approved these changes

2024-06-14 09:12 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    cy.findByTestId('dt_traders_hub').should('be.visible') //temp solution
Do we need this temp solution now?
@abuzar-deriv  can you confirm

2024-06-14 09:15 UTC, abuzar-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    cy.findByTestId('dt_traders_hub').should('be.visible') //temp solution
No longer needed.

2024-06-14 09:28 UTC, Alena-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    cy.findByTestId('dt_traders_hub').should('be.visible') //temp solution
This is removed

2024-06-14 09:30 UTC, bilalmajid-deriv approved these changes
LGTM

2024-06-14 10:06 UTC, abuzar-deriv requested changes
Why two different describe blocks for same test? Can be done with one describe, two its . Also I feel like a lot of these steps are duplicated such as /* Checks self exclusion is saved on FE */, /* Clears self exclusion date from BO */, and other similar areas which can be moved to a function and then called. 
Can you please review and move all the duplicate code into their separate functions?

2024-06-20 07:04 UTC, abuzar-deriv requested changes
One minor change needed.

2024-06-20 07:04 UTC, abuzar-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    it('should login, set self exclusion, verify its applied, check from BO side, remove it from BO and verify restrictions are removed from FE side ', () => {
```suggestion
    it(`Should login, set self exclusion, verify it's applied, check from BO side, remove it from BO and verify restrictions are removed from FE side on {size=='small'?'mobile:'desktop'}`, () => {
```

2024-06-20 07:11 UTC, Alena-deriv commented on cypress/e2e/smoke/CSIT/selfExclusionSessionAndLoginLimits.cy.js
> +    it('should login, set self exclusion, verify its applied, check from BO side, remove it from BO and verify restrictions are removed from FE side ', () => {
It is updated

2024-06-20 07:21 UTC, abuzar-deriv approved these changes
LGTM

2024-06-24 08:26 UTC, meeyun-deriv approved these changes
LGTM

2024-06-24 08:26 UTC, merged