add passykey to responsive test
deriv-com/e2e-deriv-app pull request #383
Opened 2024-06-14 09:25 UTC by afsaneh-rezaeinejad-deriv

add passkey to all of the responsive tests.

2024-06-14 09:39 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/fiatDeposit.cy.js
> +    cy.c_skipPasskeysV2()
better to run before the asssertion no?
and can we not use findByText instead of contains if it is partial text you are trying to check then can use 
cy.findByText(/wallets/) or cy.findAllByText(/wallets/) if multiple elements

```suggestion
    cy.c_visitResponsive('/', 'small')
        cy.c_skipPasskeysV2()
    cy.contains('Wallet', { timeout: 10000 }).should('exist')
```

2024-06-14 09:40 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/fiatTransactions.cy.js
> +    cy.c_skipPasskeysV2()
same as above

2024-06-14 09:40 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/fiatWithdrawal.cy.js
> +    cy.c_skipPasskeysV2()
same as above

2024-06-18 05:36 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/fiatDeposit.cy.js
> +    cy.c_skipPasskeysV2()
this is still the same.

2024-06-18 05:36 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/fiatTransactions.cy.js
> +  it.only('should be able to view transactions of fiat account in responsive', () => {
do you want to run only this test or is it by mistake?

2024-06-18 05:36 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/fiatWithdrawal.cy.js
>      cy.c_visitResponsive('/', 'large')
do we not need a skip pass keys here?

```suggestion
    cy.c_visitResponsive('/', 'large')
    cy.c_skipPassKeysV2()
```

2024-06-18 05:36 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/wallerCashierRedirection.cy.js
>      cy.c_skipPasskeysV2()
should we not run the pass key command befor ethe cy.contains ('Deposit' .....)

2024-06-19 09:03 UTC, afsaneh-rezaeinejad-deriv commented on cypress/e2e/smoke/Wallets/fiatWithdrawal.cy.js
>      cy.c_visitResponsive('/', 'large')
@bilalmajid-deriv passkey is only visible in responsive view

2024-06-19 09:22 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/fiatWithdrawal.cy.js
>      cy.c_visitResponsive('/', 'large')
oh sorry my bad

2024-06-19 09:22 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/fiatDeposit.cy.js
> +    cy.c_skipPasskeysV2()
this is missed again @afsaneh-rezaeinejad-deriv

2024-06-20 03:40 UTC, meeyun-deriv requested changes
why the new tests are locate inside the `wip` folder and not `smoke` or `full` folder?

2024-06-24 08:46 UTC, bilalmajid-deriv approved these changes

2024-06-24 09:19 UTC, meeyun-deriv approved these changes
LGTM

2024-06-24 09:19 UTC, merged