Bilal/qatest 20050
deriv-com/e2e-deriv-app pull request #384
Opened 2024-06-18 08:04 UTC by bilalmajid-deriv

Refactored previous tests
Refactored common commands being used between cashierLegacy accounts.
Added new test QATEST-20050
![image](https://github.com/deriv-com/e2e-deriv-app/assets/155507124/bd17f2af-36fe-4414-b7ac-e705bcb3187d)

2024-06-18 08:11 UTC, bilalmajid-deriv commented
The code is very complex and hard to maintain hence created card https://app.clickup.com/t/86bz8jf20 for refactoring

2024-06-24 03:19 UTC, maliheh-deriv commented on cypress/e2e/smoke/cashierLegacy/transferFiatNonUSDToMT5.cy.js
> +        cy.c_loadingCheck()
The cy.c_loadingCheck() function is called in both the if and else conditions. It can be called just once outside the if/else block to avoid duplication.

2024-06-24 03:21 UTC, maliheh-deriv commented on cypress/e2e/smoke/cashierLegacy/transferFiatToCrypto.cy.js
> +        cy.c_loadingCheck()
same as this comment https://github.com/deriv-com/e2e-deriv-app/pull/384/files#r1650287517

2024-06-24 03:33 UTC, maliheh-deriv commented on cypress/e2e/smoke/cashierLegacy/transferFiatToMT5.cy.js
> +        cy.c_loadingCheck()
@bilalmajid-deriv can you help to update this line as well please

2024-06-24 03:33 UTC, maliheh-deriv approved these changes

2024-06-24 06:03 UTC, abuzar-deriv requested changes

2024-06-24 06:05 UTC, bilalmajid-deriv commented on cypress.config.js
> +    projectId: '6rs1zi',
```suggestion
    projectId: 'rjvf4u',
```

2024-06-24 06:07 UTC, abuzar-deriv approved these changes
LGTM

2024-06-24 06:07 UTC, merged