QATEST-4249 Cypress test - Bot Builder - Search block menu
deriv-com/e2e-deriv-app pull request #386
Opened 2024-06-18 12:58 UTC by alexander-deriv

Cypress card https://app.clickup.com/t/20696747/BOT-1851
Test cases https://app.clickup.com/t/20696747/QATEST-4249

Description:
Test checks approved that writing valid information in the 'Search bar' in DBot allows us to see valid information. At the same time, writing invalid requests leads to the appearance of the phrase 'No results found'.
<img width="1705" alt="Screenshot 2024-06-18 at 3 55 01 PM" src="https://github.com/deriv-com/e2e-deriv-app/assets/169877832/ce0b4f49-0c35-41a1-bcc9-24ea2b7df3fe">

2024-06-19 04:05 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +    it('Login from app.deriv.com, opening DBot and checking of valid/invalid requests in Search bar on Desktop', () => {
the test case name should follow the format 
it('should [what test should do here]' ,()=>{})

2024-06-19 04:05 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +      cy.get('[class="flyout flyout__search"]', { timeout: 10000 }).should(
do we not have any other locator here?

2024-06-19 05:46 UTC, abuzar-deriv requested changes
Code formatting workflow is failing. Can you please run `npm i` and then commit your changes? Requesting some other changes as well.

2024-06-19 05:46 UTC, abuzar-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +      cy.c_visitResponsive('/')
Can you please remove this line? It's not needed.

2024-06-19 05:46 UTC, abuzar-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +      cy.c_skipTour() //presses skip button
Please remove the comment. This command is self-explanatory.

2024-06-19 05:46 UTC, abuzar-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +      cy.get('[class="flyout flyout__search"]', { timeout: 10000 }).should(
If yes to above question, please use cy.get('.flyout flyout__search') instead of this.

2024-06-19 05:46 UTC, abuzar-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +        'exist'
Assertion on visibility would be better, i.e. should('be.visible')

2024-06-19 05:46 UTC, abuzar-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +      cy.findByRole('heading', { name: 'No results found' }).should('exist')
Can you assert on visibility instead?

2024-06-19 05:46 UTC, abuzar-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +
Can you please add another assertion here verifying that search result is displayed?

2024-06-21 10:51 UTC, alexander-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +      cy.get('[class="flyout flyout__search"]', { timeout: 10000 }).should(
I couldn't make it work with another locator but changed the approach by using a valid assert result as requested here: https://github.com/deriv-com/e2e-deriv-app/pull/386#discussion_r1645437621

2024-06-21 11:05 UTC, alexander-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +
this is updated

2024-06-21 11:05 UTC, alexander-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +      cy.findByRole('heading', { name: 'No results found' }).should('exist')
done

2024-06-21 11:05 UTC, alexander-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +        'exist'
done

2024-06-21 11:05 UTC, alexander-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +      cy.c_skipTour() //presses skip button
done

2024-06-21 11:06 UTC, alexander-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +      cy.c_visitResponsive('/')
done

2024-06-21 11:06 UTC, alexander-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +    it('Login from app.deriv.com, opening DBot and checking of valid/invalid requests in Search bar on Desktop', () => {
done

2024-06-24 03:46 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +    cy.contains('Results for "Trading"')
can you use testing library locator here?
```suggestion
    cy.findByText('Results for "Trading"')
```

2024-06-24 04:33 UTC, abuzar-deriv approved these changes
LGTM pending Bilal's comment.

2024-06-24 06:07 UTC, alexander-deriv commented on cypress/e2e/smoke/dbot/SearchBlockMenu.cy.js
> +    cy.contains('Results for "Trading"')
done

2024-06-24 06:08 UTC, bilalmajid-deriv approved these changes

2024-06-24 08:35 UTC, meeyun-deriv approved these changes
LGTM

2024-06-24 08:35 UTC, merged