Update cryptoTransactions.cy.js
deriv-com/e2e-deriv-app pull request #392
Opened 2024-06-19 08:52 UTC by zubair-deriv

## Card
https://app.clickup.com/t/20696747/WALL-4430

2024-06-19 10:10 UTC, maliheh-deriv approved these changes

2024-06-19 10:17 UTC, markodonnell-deriv requested changes

2024-06-19 10:17 UTC, markodonnell-deriv commented on cypress/e2e/smoke/Wallets/cryptoTransactions.cy.js
> +    Cypress.prevAppId = 0
What issue does this cause when you don't initialise to prevAppId to 0?

2024-06-20 03:17 UTC, zubair-deriv commented on cypress/e2e/smoke/Wallets/cryptoTransactions.cy.js
> +    Cypress.prevAppId = 0
@markodonnell-deriv  
this is because the oAuthURL which we retrieve contains the accounts for the user as well and in the first `it` block a new account (Options account) is created. And, when we try to visit the oAuthUrl saved earlier again in the next `it` block, it does not load the newly added account as it does not exist in the oAuthURL hence we need to get the newly generated oAuthUrl which will contain the added account as well.
Since we are using the stored oauthUrl repeatedly, it causes the issue only in automation test cases.
When executing the same test manually the UI deals with it and we get a new OauthURL

2024-06-24 08:03 UTC, markodonnell-deriv commented on cypress/e2e/smoke/Wallets/cryptoTransactions.cy.js
> +    Cypress.prevAppId = 0
OK, understood.

2024-06-24 08:04 UTC, markodonnell-deriv approved these changes
Looks good

2024-06-24 08:27 UTC, meeyun-deriv approved these changes
LGTM

2024-06-24 08:27 UTC, merged