Add test for UPM-1183
deriv-com/e2e-deriv-app pull request #396
Opened 2024-06-20 07:46 UTC by munnfaye-deriv

**Card**
https://app.clickup.com/t/20696747/UPM-1183

**Description**
Added test to for production bug [UPM-1162](https://app.clickup.com/t/20696747/UPM-1162) where `Invalid date` is displayed under 'Date and time' field in 'Login history' page.

2024-06-24 05:07 UTC, bilalmajid-deriv reviewed
left comments

2024-06-24 05:07 UTC, bilalmajid-deriv commented on cypress/e2e/wip/UPM/loginHistory.cy.js
> +}
I think we can move this to the support/helper/utility.js file and import from there

2024-06-24 05:07 UTC, bilalmajid-deriv commented on cypress/e2e/wip/UPM/loginHistory.cy.js
> +      .contains('GMT')
can we not use testing library locators over here?

2024-06-24 05:07 UTC, bilalmajid-deriv commented on cypress/e2e/wip/UPM/loginHistory.cy.js
> +    cy.findByText('Invalid date').should('not.exist')
can creat a cypress command for this as this is common code between both tests

2024-06-24 06:06 UTC, munnfaye-deriv commented on cypress/e2e/wip/UPM/loginHistory.cy.js
> +}
Moved this function to support/helper/utility.js file

2024-06-24 06:07 UTC, munnfaye-deriv commented on cypress/e2e/wip/UPM/loginHistory.cy.js
> +      .contains('GMT')
Improved lines 25 and 26 to not use testing library locators but for maintained line 28 and 29 as there are no other other suitable locators that can be used.

2024-06-24 06:07 UTC, munnfaye-deriv commented on cypress/e2e/wip/UPM/loginHistory.cy.js
> +    cy.findByText('Invalid date').should('not.exist')
Created the command

2024-06-24 06:21 UTC, bilalmajid-deriv approved these changes

2024-06-24 08:31 UTC, meeyun-deriv requested changes

2024-06-24 08:31 UTC, meeyun-deriv commented on cypress/e2e/wip/UPM/loginHistory.cy.js
> +describe('UPM-1183 - Verify Login history page', () => {
we should reference to the test scenario and use its custom ID here. Since the test scenario is not available, can you please create one?

2024-06-24 09:38 UTC, munnfaye-deriv commented on cypress/e2e/wip/UPM/loginHistory.cy.js
> +describe('UPM-1183 - Verify Login history page', () => {
I have created the test scenario and updated the description in code

2024-07-22 03:41 UTC, meeyun-deriv requested changes

2024-07-22 03:41 UTC, meeyun-deriv commented on cypress/e2e/wip/UPM/loginHistory.cy.js
> +    cy.c_skipPasskeysV2()
this is not needed as we already skip passkey in log in and visit responsive

2024-07-23 04:39 UTC, maliheh-deriv approved these changes

2024-07-29 05:26 UTC, meeyun-deriv approved these changes
LGTM

2024-07-29 05:26 UTC, merged