E2E tests for onfido fake profile
deriv-com/e2e-deriv-app pull request #400
Opened 2024-06-20 13:01 UTC by deborah-deriv

**E2E tests for onfido fake profile**
These are end to end tests for scenario where onfido supported client creates an account with fake names (names with no vowels). So in BO we should show "Un welcome Login ID" status

2024-06-24 05:16 UTC, bilalmajid-deriv approved these changes

2024-06-24 05:45 UTC, maliheh-deriv commented on cypress/e2e/wip/KYC/onfidoFakeProfile.cy.js
> +    cy.findByRole('button', { name: 'Submit' }).click()
Can we add verification for `account notification`: https://app.clickup.com/t/20696747/QATEST-4779

2024-06-24 08:44 UTC, meeyun-deriv requested changes
are we planning not to cover the step `https://app.clickup.com/t/20696747/QATEST-4781`?

2024-06-28 06:55 UTC, bilalmajid-deriv requested changes

2024-06-28 06:55 UTC, bilalmajid-deriv commented on cypress/support/helper/utility.js
> +}
@deborah-deriv can you please help to merge the two commands into one as generateRandomName() and make it parameterized to avoid duplication

2024-06-28 07:58 UTC, bilalmajid-deriv reviewed
one comment left

2024-06-28 07:58 UTC, bilalmajid-deriv commented on cypress/support/commands/common.js
> +})
can merge with the above command and parameterize this.

2024-06-28 07:59 UTC, bilalmajid-deriv commented on cypress/support/commands/common.js
> +})
the default behavior should be to login.

2024-06-28 09:55 UTC, bilalmajid-deriv reviewed
can do this for easy readability

2024-06-28 09:55 UTC, bilalmajid-deriv commented on cypress/support/commands/common.js
>    cy.viewport('macbook-16')
```suggestion
Cypress.Commands.add('c_visitBackOffice', (options = {}) => {
  const {
    login = true,
    } = options
  cy.viewport('macbook-16')
```

2024-06-28 09:55 UTC, bilalmajid-deriv commented on cypress/e2e/manual/kyc/onfidoFakeProfile.cy.js
> +    cy.c_visitBackOffice(false)
```suggestion
    cy.c_visitBackOffice({ login : false })
```

2024-06-28 10:22 UTC, bilalmajid-deriv approved these changes
LGTM

2024-07-02 06:27 UTC, meeyun-deriv approved these changes
LGTM

2024-07-02 06:27 UTC, merged