Onfido Verified account once becomes high risk
deriv-com/e2e-deriv-app pull request #405
Opened 2024-06-21 14:31 UTC by deborah-deriv

**Onfido Verified account once becomes high risk**
These are end-to-end tests for verified onfido account once becomes high risk with their expected behaviors:
- He/she should not be asked for POI again upon creating MT5 regulated account. He should only be asked for POA. 
- He should be asked to first fill FA upon he clicks "Create Deriv MT5 password" button

2024-06-24 03:05 UTC, maliheh-deriv commented on cypress/e2e/wip/KYC/onfidoHighLisk.cy.js
> +    cy.get('#dc_cfd_toggle_item').should('be.visible').click()
Better to use this format to click on CFD button. 
`cy.findByRole('button', { name: 'CFDs' }).click()`

2024-06-24 03:09 UTC, maliheh-deriv commented on cypress/e2e/wip/KYC/onfidoHighLisk.cy.js
> +    cy.contains(
It is better to use findByText because class names can be updated in future. For example:
`cy.findByText('British Virgin Islands').click()`

2024-06-24 03:10 UTC, maliheh-deriv commented on cypress/e2e/wip/KYC/onfidoHighLisk.cy.js
> +    cy.findByTestId('dt_mt5_password').type('Abcd@1234')
Please do not hardcode the password

2024-06-24 03:12 UTC, maliheh-deriv commented on cypress/e2e/wip/KYC/onfidoHighLisk.cy.js
> +    cy.contains('p', 'Please complete your financial assessment.').should(
Better to use `cy.findByText`

2024-06-24 07:23 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/onfidoHighLisk.cy.js
> +    cy.get('#dc_cfd_toggle_item').should('be.visible').click()
This is addressed thanks

2024-06-24 07:56 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/onfidoHighLisk.cy.js
> +    cy.contains(
This is addressed. Thank you

2024-06-24 07:57 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/onfidoHighLisk.cy.js
> +    cy.findByTestId('dt_mt5_password').type('Abcd@1234')
This is addressed thanks

2024-06-24 07:57 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/onfidoHighLisk.cy.js
> +    cy.contains('p', 'Please complete your financial assessment.').should(
This is changed

2024-06-24 08:17 UTC, maliheh-deriv approved these changes

2024-06-25 09:33 UTC, markodonnell-deriv requested changes

2024-06-25 09:33 UTC, markodonnell-deriv commented on cypress/e2e/wip/KYC/onfidoHighLisk.cy.js
> +    cy.findByTestId('dt_traders_hub').should('be.visible')
Should this not be part of login now?

2024-06-25 10:29 UTC, meeyun-deriv requested changes

2024-06-25 10:29 UTC, meeyun-deriv commented on cypress/e2e/wip/KYC/onfidoHighLisk.cy.js
> +      'cypress/fixtures/kyc/testDocument.jpg',
please also include the validation where the POA shows up in the page

2024-06-26 14:08 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/onfidoHighLisk.cy.js
> +    cy.findByTestId('dt_traders_hub').should('be.visible')
this is removed

2024-06-27 10:36 UTC, deborah-deriv commented on cypress/e2e/wip/KYC/onfidoHighLisk.cy.js
> +      'cypress/fixtures/kyc/testDocument.jpg',
This is added @meeyun-deriv , Kindly help check again

2024-06-27 10:54 UTC, meeyun-deriv approved these changes
LGTM

2024-06-27 11:54 UTC, markodonnell-deriv approved these changes
Looks good

2024-06-27 11:58 UTC, merged