Ivo/idv mt5 modal
deriv-com/e2e-deriv-app pull request #406
Opened 2024-06-21 20:53 UTC by ivo-deriv

Adds test spec for IDV submission through MT5 modal. Mobile view.

2024-06-24 02:51 UTC, maliheh-deriv approved these changes

2024-06-27 11:13 UTC, meeyun-deriv requested changes

2024-06-27 11:13 UTC, meeyun-deriv commented on cypress/e2e/wip/KYC/idvMT5Modal.cy.js
> +describe('QA-TEST-149356 POI through MT5 acc creation', () => {
typo on the custom id, it should be `QATEST-149356`

2024-06-27 11:13 UTC, meeyun-deriv commented on cypress/e2e/wip/KYC/idvMT5Modal.cy.js
> +    cy.findByText('Your proof of identity verification has failed', {
are we planning to do the passing POI in next PR?

2024-07-02 19:52 UTC, ivo-deriv commented on cypress/e2e/wip/KYC/idvMT5Modal.cy.js
> +describe('QA-TEST-149356 POI through MT5 acc creation', () => {
fixed

2024-07-02 19:52 UTC, ivo-deriv commented on cypress/e2e/wip/KYC/idvMT5Modal.cy.js
> +    cy.findByText('Your proof of identity verification has failed', {
have added a second POI attempt (pass) in recent commit

2024-07-08 08:43 UTC, meeyun-deriv requested changes

2024-07-08 08:43 UTC, meeyun-deriv commented on cypress/e2e/wip/KYC/idvMT5Creation.cy.js
> +    cy.findByRole('button', { name: 'Continue' }).click().wait(4500)
why need the wait?

2024-07-08 08:43 UTC, meeyun-deriv commented on cypress/e2e/wip/KYC/idvMT5Creation.cy.js
> +    cy.c_login()
JFYI, this current test is keep failing when the passkey appears in mobile view. This might be resolved in another PR (https://github.com/deriv-com/e2e-deriv-app/pull/465) which will disable the passkey.

2024-07-08 08:43 UTC, meeyun-deriv commented on cypress/e2e/wip/KYC/idvMT5Creation.cy.js
> +    //Checks both POI and POA were submitted correctly
comment should put before the relevant steps

2024-07-08 08:43 UTC, meeyun-deriv commented on cypress/e2e/wip/KYC/idvMT5Creation.cy.js
> +    cy.findByLabelText('Enter your document number').type('0000000000000')
i think this test is not rerun-able as the IDV document cannot be reused for other account

2024-07-08 08:43 UTC, meeyun-deriv commented on cypress/e2e/wip/KYC/idvMT5Creation.cy.js
> +    }).should('exist') // Failure expected due to document rejected test data
Are you able to run the test locally with passing result? the `Your proof of identity verification has failed` didnt show up when running in local.

2024-07-09 16:47 UTC, ivo-deriv commented on cypress/e2e/wip/KYC/idvMT5Creation.cy.js
> +    }).should('exist') // Failure expected due to document rejected test data
Yes, but after checking it seems the submission time for IDV sometimes can be 3.5 seconds, which overrides the wait(3000) so the modal is closed before IDV is sent

2024-07-17 21:02 UTC, ivo-deriv commented on cypress/e2e/wip/KYC/idvMT5Creation.cy.js
> +    cy.findByLabelText('Enter your document number').type('0000000000000')
fixed

2024-07-26 06:07 UTC, meeyun-deriv approved these changes
LGTM

2024-07-26 06:07 UTC, merged