Run Even Odd strategy on responsive
deriv-com/e2e-deriv-app pull request #409
Opened 2024-06-24 08:23 UTC by thivya-deriv

Card: https://app.clickup.com/t/20696747/BOT-1669
Description: To run a custom strategy on responsive

2024-06-25 04:47 UTC, abuzar-deriv requested changes

2024-06-25 04:47 UTC, abuzar-deriv commented on cypress/support/pageobjects/dbot/bot_dashboard_page.js
> +  get openStrategyButtonDekstop() {
Typo.
```suggestion
  get openStrategyButtonDesktop() {
```

2024-06-25 04:47 UTC, abuzar-deriv commented on cypress/support/pageobjects/dbot/bot_dashboard_page.js
> +    this.deleteStrategyButtonDekstop.click()
Same here

2024-06-25 04:47 UTC, abuzar-deriv commented on cypress/e2e/smoke/dbot/RunEvenOdd.cy.js
> +      botDashboard.deleteModalConfirm.click({ force: true })
Why not make` deleteStrategy()` a custom command and use here since it will be used across multiple tests?

2024-06-25 09:23 UTC, meeyun-deriv approved these changes
LGTM other than @abuzar-deriv comment

2024-06-28 01:26 UTC, abuzar-deriv requested changes

2024-06-28 01:26 UTC, abuzar-deriv commented on cypress/support/commands/dBot.js
> +Cypress.Commands.add('c_deleteStrategy', (isMobile) => {
This will run as you expect anyway but it's good practice to provide a default value:
```suggestion
Cypress.Commands.add('c_deleteStrategy', (isMobile = false) => {
```

2024-06-28 01:26 UTC, abuzar-deriv commented on cypress/support/commands/dBot.js
> +    // cy.get('.bot-list__item__responsive').should('have.class' , 'bot-list__item__responsive--active')
Please remove this.

2024-06-28 02:22 UTC, abuzar-deriv approved these changes
LGTM

2024-06-28 02:23 UTC, merged