Adding proposal.js and buy.js files containing PriceProposal and Buy API calls
deriv-com/e2e-deriv-app pull request #412
Opened 2024-06-24 12:51 UTC by rajendra-deriv

Adding proposal.js and buy.js files containing PriceProposal and Buy API calls

2024-06-24 14:11 UTC, markodonnell-deriv requested changes
I'd group the helper/.js files into a single file.

2024-06-24 14:11 UTC, markodonnell-deriv commented on cypress/support/helper/buy.js
> +      price: 100,
Avoid hard coding of low level data. We want to be able to use the APIs often, by different tests.

2024-06-24 14:11 UTC, markodonnell-deriv commented on cypress/support/helper/proposal.js
> +    const priceProposal = await api.basic.proposal({
Avoid hard coding of low level data. We want to be able to use the APIs often, by different tests.

2024-06-24 14:11 UTC, markodonnell-deriv commented on cypress/support/commands/common.js
> +Cypress.Commands.add('c_getPriceProposal', () => {
I think it's time to group API command into their own file. common is getting too busy.

2024-06-25 09:01 UTC, meeyun-deriv commented on cypress/e2e/api/buy.cy.js
> +        expect(actualAmountNum).to.be.lessThan(expectedAmountNum)
are we planning to add more buy scenario in future PR? (e.g. buy amount which more than available balance, buy the contract type which not offer to that account)

2024-06-25 09:42 UTC, abuzar-deriv reviewed
Have some questions.

2024-06-25 09:42 UTC, abuzar-deriv commented on cypress/e2e/api/buy.cy.js
> +    })
Suppose in future if I use a different email than Cypress.env('loginEmail')? Would it still work?
PS: I prefer to keep all the credentials at one place so I've recently moved Cypress.env('loginEmail') to Cypress.env('credentials').test.masterUser.ID

2024-06-25 09:42 UTC, abuzar-deriv commented on cypress/support/commands/common.js
> +      Cypress.env('actualEmail', email)
Why not ? Will it not work?
```suggestion
      Cypress.env('actualEmail', response)
```

2024-06-25 09:42 UTC, abuzar-deriv commented on cypress/support/commands/common.js
> +      Cypress.env('balanceAfterBuy', buyContractResp)
Same here:
```suggestion
      Cypress.env('balanceAfterBuy', response)
```

2024-06-25 09:42 UTC, abuzar-deriv commented on cypress/support/commands/common.js
> +      Cypress.env('priceProposalResponse', priceProposalResp)
And here:
```suggestion
      Cypress.env('priceProposalResponse', response)
```

2024-06-25 14:42 UTC, rajendra-deriv commented on cypress/support/helper/buy.js
> +      price: 100,
parameterized the variables

2024-06-25 14:42 UTC, rajendra-deriv commented on cypress/support/helper/proposal.js
> +    const priceProposal = await api.basic.proposal({
parameterized the variables

2024-06-25 15:16 UTC, rajendra-deriv commented on cypress/e2e/api/buy.cy.js
> +        expect(actualAmountNum).to.be.lessThan(expectedAmountNum)
Yes @meeyun-deriv , We will add other scenario's around Buy and Sell.

2024-06-25 15:20 UTC, rajendra-deriv commented on cypress/support/commands/common.js
> +      Cypress.env('balanceAfterBuy', buyContractResp)
Updated the code to use "response"

2024-06-25 15:20 UTC, rajendra-deriv commented on cypress/support/commands/common.js
> +      Cypress.env('priceProposalResponse', priceProposalResp)
Updated the code to use "response"

2024-06-26 07:12 UTC, rajendra-deriv commented on cypress/e2e/api/buy.cy.js
> +    })
Now dynamically creating the user and using that users email to assert. So there will no issue.

2024-06-26 07:13 UTC, rajendra-deriv commented on cypress/e2e/api/buy.cy.js
> +    cy.c_login()
Sure @meeyun-deriv , Added creating a new account and login instead of using existing one.

2024-06-26 07:14 UTC, rajendra-deriv commented on cypress/support/commands/common.js
> +Cypress.Commands.add('c_getPriceProposal', () => {
Sure @markodonnell-deriv , I have created api.js and moved all the API related methods from common.js. RUn all the API methods like Balance.cy.js , createApplicationRegister.cy.js and buy.cy.js and all are passing

2024-06-26 07:34 UTC, meeyun-deriv approved these changes
LGTM

2024-06-26 09:57 UTC, markodonnell-deriv requested changes

2024-06-26 09:57 UTC, markodonnell-deriv commented on cypress.config.js
> +          async createPriceProposalTask() {
We should be loading a price object from a fixture and passing that to the API. We have too many env vars already.
Coincidentally, we've been having the same conversation with @bertrand-deriv , so he should be able to help with this, if you haven't used fixtures before.
Have look at the use of cy.fixture in tradersHub and cashierLegacy too, written by @abuzar-deriv and @bilalmajid-deriv

2024-06-26 10:09 UTC, rajendra-deriv commented on cypress.config.js
> +          async createPriceProposalTask() {
Sure @markodonnell-deriv

2024-07-01 13:02 UTC, rajendra-deriv commented on cypress.config.js
> +          async createPriceProposalTask() {
Implemented the Fixture changes

2024-07-01 14:11 UTC, markodonnell-deriv requested changes

2024-07-01 14:11 UTC, markodonnell-deriv commented on cypress/support/helper/buy.js
> + * @returns Balance After The Contract Is Brought
*Bought not Brought

2024-07-01 14:11 UTC, markodonnell-deriv commented on cypress/support/helper/buy.js
> +    return buyContract.buy.balance_after
In the api interface you're declaring buy_id as the return type, but here you're returning balance_after?

2024-07-01 14:11 UTC, markodonnell-deriv commented on cypress.config.js
> +              return buy_id
In this api interface you're declaring buy_id as the return type, but in the function itself you're returning balance_after.

2024-07-02 12:39 UTC, rajendra-deriv commented on cypress/support/helper/buy.js
> + * @returns Balance After The Contract Is Brought
Updated to Bought

2024-07-02 12:39 UTC, rajendra-deriv commented on cypress/support/helper/buy.js
> +    return buyContract.buy.balance_after
Its has to be balance_after_buy and not buy_id. Updated to "balance_after_buy"

2024-07-02 12:39 UTC, rajendra-deriv commented on cypress.config.js
> +              return buy_id
Its has to be balance_after_buy and not buy_id. Updated to "balance_after_buy"

2024-07-08 12:06 UTC, markodonnell-deriv requested changes

2024-07-08 12:06 UTC, markodonnell-deriv commented on cypress.config.js
> +    loginEmail: process.env.E2E_LOGIN_EMAIL,
Is this necessary? Is this going to be different to E2E_DERIV_LOGIN?

2024-07-08 12:06 UTC, markodonnell-deriv commented on cypress.config.js
> +    balanceAfterBuy: process.env.E2E_BUY_RESPONSE,
Is this necessary? Does the scope of this returned value need to be global?

2024-07-08 12:06 UTC, markodonnell-deriv commented on cypress.config.js
> +    priceProposalCurrency: process.env.E2E_PRICE_PROPOSAL_CURRENCY,
These are retrieved from fixtures now, so can be removed.

2024-07-09 10:31 UTC, rajendra-deriv commented on cypress.config.js
> +    loginEmail: process.env.E2E_LOGIN_EMAIL,
Hi @markodonnell-deriv , You ment 
    newlyCreatedEmail: process.env.E2E_CREATED_NEW_EMAIL,
newlyCreatedEmail i am using in c_createDemoAccount() to assign accountEmail to newlyCreatedEmail and using it to compare the login email id's.
I am not using loginEmail for my automation card.

2024-07-09 11:38 UTC, rajendra-deriv commented on cypress.config.js
> +    balanceAfterBuy: process.env.E2E_BUY_RESPONSE,
Removed priceProposalResponse (created a local var for it). But we need priceProposalID and balanceAfterBuy

2024-07-09 11:43 UTC, rajendra-deriv commented on cypress.config.js
> +    priceProposalCurrency: process.env.E2E_PRICE_PROPOSAL_CURRENCY,
Removing below variables as now i am getting them from fixtures:
    priceProposalCurrency: process.env.E2E_PRICE_PROPOSAL_CURRENCY,
    priceProposalAmount: process.env.E2E_PRICE_AMOUNT,
    priceProposalBarrier: process.env.E2E_PRICE_PROPOSAL_BARRIER,
    priceProposalBasis: process.env.E2E_PRICE_PROPOSAL_BASIS,
    priceProposalContractType: process.env.E2E_PRICE_PROPOSAL_CONTRACT_TYPE,
    priceProposalDuration: process.env.E2E_PRICE_PROPOSAL_DURATION,
    priceProposalDurationUnit: process.env.E2E_PRICE_PROPOSAL_DURATION_UNIT,
    priceProposalSymbol: process.env.E2E_PRICE_PROPOSAL_SYMBOL,

2024-07-09 12:47 UTC, markodonnell-deriv requested changes

2024-07-09 12:47 UTC, markodonnell-deriv commented on cypress/support/commands/common.js
> +      Cypress.env('newlyCreatedEmail', accountEmail)
Why do we need this when we didn't need it for the other account creation commands?

2024-07-09 13:33 UTC, rajendra-deriv commented on cypress/support/commands/common.js
> +      Cypress.env('newlyCreatedEmail', accountEmail)
Removed this new variable assignment and using Cypress.env('credentials', currentCredentials)

2024-07-09 14:27 UTC, markodonnell-deriv submitted a review, later dismissed
Looks good

2024-07-11 08:04 UTC, bilalmajid-deriv reviewed
one recommendation and one comment.

2024-07-11 08:04 UTC, bilalmajid-deriv commented on cypress/fixtures/api/apiFixture.json
Suggestion:
I think these values should be default values and we should also be able to pass values as parameter to the api call so that we can change values if needed but I think that can be done in another PR as well if parameterization is not required urgently.

2024-07-11 08:04 UTC, bilalmajid-deriv commented on cypress/support/helper/proposal.js
> +
following up on the above recommendation here these inputs can be parameterized 
the precedence would be that if a parameter is passed then used that else use the default values.

2024-07-11 08:04 UTC, bilalmajid-deriv commented on cypress/support/helper/buy.js
> +    }
following up on the above recommendation here these inputs can be parameterized
the precedence would be that if a parameter is passed then used that else use the default values.

2024-07-11 08:31 UTC, rajendra-deriv commented on cypress.config.js
> +    balanceAfterBuy: process.env.E2E_BUY_RESPONSE,
Done. initialized these variables to empty.

2024-07-11 10:49 UTC, bilalmajid-deriv approved these changes

2024-07-11 10:51 UTC, merged