POI submission through real account creation
deriv-com/e2e-deriv-app pull request #420
Opened 2024-06-25 11:25 UTC by bertrand-deriv

- Added tests for POI submission through account creation

2024-06-26 04:52 UTC, bilalmajid-deriv commented on cypress/support/helper/utility.js
> +}
@bertrand-deriv do we not have a similar function in one of @deborah-deriv's PR
with the only difference that it generates a name without vowels 
can you guys coordinate and make this function parameterized so that both use same function 🙏

2024-06-26 07:24 UTC, bertrand-deriv commented on cypress/support/helper/utility.js
> +}
Ahh
yeah
that's right

2024-06-26 07:26 UTC, bertrand-deriv commented on cypress/support/helper/utility.js
> +}
Let me add a boolean parameter to know whether there should be vowels or not
Then Deborah will use this same function

2024-06-28 08:00 UTC, bilalmajid-deriv approved these changes

2024-06-28 09:19 UTC, markodonnell-deriv requested changes

2024-06-28 09:19 UTC, markodonnell-deriv commented on cypress/e2e/wip/KYC/poiRealAccount.cy.js
> +    cy.viewport('iphone-xr')
If traders hub is always the first page now after login, perhaps we need viewport param to cy.login() and check for existence of the last element to appear, as per visitResponsive().
Or we continue to use visitResponsive even though it seems wasteful calling the same page twice?
Thoughts @meeyun-deriv @bilalmajid-deriv @abuzar-deriv ?

2024-07-02 09:41 UTC, markodonnell-deriv commented on cypress/e2e/wip/KYC/poiRealAccount.cy.js
> +    cy.viewport('iphone-xr')
Let's do this as a separate PR Bertrand.

2024-07-02 11:43 UTC, merged