CSIT-896 Create test for regression bug P2PS-2560
deriv-com/e2e-deriv-app pull request #421
Opened 2024-06-25 13:12 UTC by Alena-deriv

ClickUp card https://app.clickup.com/t/20696747/CSIT-896

Description:
1. Test creates 3 Payments methods from BO side
2. Test checks if Payment methods are already exist, if yes, will proceed with further steps, if no - will create new ones.
3. On the DOUGHFLOW PAYMENT METHODS page, test will sort all available payment methods by 'Category' and will check that result with 'Category1' is filtered
<img width="1722" alt="Screenshot 2024-06-25 at 16 03 42" src="https://github.com/deriv-com/e2e-deriv-app/assets/153058266/04274a06-3f97-46f2-91a7-089c67914d16">

2024-06-26 04:56 UTC, bilalmajid-deriv approved these changes

2024-06-26 04:57 UTC, bilalmajid-deriv commented
Approved the usage of cy.get as it is tricky sometimes not possible to find a testing library locator

2024-07-01 08:54 UTC, meeyun-deriv requested changes

2024-07-01 08:54 UTC, meeyun-deriv commented on cypress/e2e/smoke/CSIT/boPaymentMethodSorting.cy.js
> +describe('QATEST-140205 - Sorting using category in BO Doughflow payment methods management page', () => {
this ID is reference to test case. We need to reference to the test scenarios instead

2024-07-01 09:38 UTC, Alena-deriv commented on cypress/e2e/smoke/CSIT/boPaymentMethodSorting.cy.js
> +describe('QATEST-140205 - Sorting using category in BO Doughflow payment methods management page', () => {
Updated

2024-07-02 06:51 UTC, meeyun-deriv approved these changes
LGTM

2024-07-02 06:52 UTC, merged