account closure transactional email
deriv-com/e2e-deriv-app pull request #422
Opened 2024-06-25 14:20 UTC by jyothi-deriv

Automate transactional emails for account_closure
Test case - https://app.clickup.com/t/20696747/QATEST-162618

**Note**: Since we can't automate checking emails through CustomerIO without Okta login, we're verifying that transactional events are being received properly from QA events([https://qaxx.deriv.dev/events/](https://qa10.deriv.dev/events/)) instead.

2024-06-26 04:43 UTC, bilalmajid-deriv requested changes
@jyothi-deriv 
can you please run `npm i` before your next commit so that prettier formatting is applied.

I dont know for sure if responsive test should also be created here as the test is to verify email is sent can you check with @meeyun-deriv on this?

2024-06-26 04:43 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/transactionalEmails/accountClosure.cy.js
> +describe('verify the transactional email content', () => {
need to have correct test ID and Name 
describe('QATEST-XXXXX' - Test Case Summary',()=>{})

2024-06-26 04:43 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/transactionalEmails/accountClosure.cy.js
> +        cy.findByRole('link', { name: 'Close your account' }).click()
Why not just redirect to the close-Account setting screen directly cy.c_visitResponsive('account/closing-account', 'desktop') ?
instead of using these three steps.

2024-06-26 05:34 UTC, abuzar-deriv requested changes

2024-06-26 05:34 UTC, abuzar-deriv commented on cypress/support/commands/transactionalEmail.js
> +        cy.get('p').filter(`:contains('${accountEmail}')`).should('be.visible').last())()
No need to use it like this here. That was just a specific case needed in the other command.
```suggestion
        cy.get('p').filter(`:contains('${accountEmail}')`).should('be.visible').last()
```

2024-06-26 05:34 UTC, abuzar-deriv commented on cypress/support/commands/transactionalEmail.js
> +        cy.get('p[style="margin:0;"]').should('contain', 'transactional_message_id: account_closure')
Better to verify it in the context of above email locator. It's an edge case, but if there are two emails inside account closure, then there is a possibility of false positive here.

2024-06-26 05:34 UTC, abuzar-deriv commented on cypress/support/commands/transactionalEmail.js
> +} = options
Do transactional emails go to some other url as well? If not, we don't need this parameter and can be just a local var.

2024-06-26 05:34 UTC, abuzar-deriv commented on cypress/e2e/smoke/transactionalEmails/accountClosure.cy.js
> +        cy.c_visitResponsive('/', 'desktop')
We are prioritizing responsive view. Can you please add that as well?

2024-06-27 07:21 UTC, abuzar-deriv requested changes
Two minor changes.

2024-06-27 07:21 UTC, abuzar-deriv commented on cypress/e2e/smoke/transactionalEmails/accountClosure.cy.js
> +    cy.c_visitResponsive('account/closing-account')
Better to pass size here otherwise it takes default size from env file which might change in future.
```suggestion
    cy.c_visitResponsive('account/closing-account', 'small')
```

2024-06-27 07:21 UTC, abuzar-deriv commented on cypress/support/commands/transactionalEmail.js
> +              .last()
```suggestion
          cy.get('p')
              .filter(`:contains('${accountEmail}')`)
              .last()
              .should('be.visible')
              .siblings()
              .should('contain', 'transactional_message_id: account_closure')
```

2024-06-27 07:46 UTC, abuzar-deriv approved these changes
LGTM

2024-06-27 15:32 UTC, leonid-deriv reviewed
See comments below

2024-06-27 15:34 UTC, leonid-deriv commented on cypress/e2e/smoke/transactionalEmails/accountClosure.cy.js
> +  it(`Verify account_closure are triggered as transactional emails on Mobile`, () => {
I would separate parts of the code (by empty line)  following AAA or GWT pattern... but this is up to you

2024-06-27 15:54 UTC, markodonnell-deriv commented on cypress/support/commands/transactionalEmail.js
> +Cypress.Commands.add(
Yep, good comment, because the location of the message night change over time. 
I think the type of content we're looking for should parameterised. Rather than hard-coded to account_closure.

2024-06-27 16:23 UTC, markodonnell-deriv requested changes

2024-06-27 16:23 UTC, markodonnell-deriv commented on cypress/support/commands/transactionalEmail.js
> +              .should('contain', 'transactional_message_id: account_closure')
Could you parameterize the message that we're looking for? Rather than hard code to 'account_closure'. There might be other transactional_message_id:s that we want to match against in future tests.

2024-06-28 08:21 UTC, bilalmajid-deriv approved these changes
LGTM

2024-06-28 10:11 UTC, markodonnell-deriv requested changes

2024-07-01 06:34 UTC, markodonnell-deriv approved these changes
Looks good now

2024-07-01 07:22 UTC, merged