Added new test and quick fix for withdrawal request test
deriv-com/e2e-deriv-app pull request #424
Opened 2024-06-26 04:17 UTC by bilalmajid-deriv

![image](https://github.com/deriv-com/e2e-deriv-app/assets/155507124/81aec55e-7cfc-4017-b2f7-ead2429afda9)
![image](https://github.com/deriv-com/e2e-deriv-app/assets/155507124/31c7a47b-0854-4ad5-8047-572dc01551f7)

2024-06-26 05:48 UTC, abuzar-deriv requested changes
Minor change.

2024-06-26 05:48 UTC, abuzar-deriv commented on cypress/e2e/full/cashierLegacy/paymentAgentDepositScreenLoad.cy.js
> +      }
```suggestion
      if (screenSize == 'small') {
        derivApp.commonPage.mobileLocators.header.hamburgerMenuButton().click()
        derivApp.commonPage.mobileLocators.sideMenu.sidePanel().within(() => {
          derivApp.commonPage.mobileLocators.sideMenu.cashierButton().click()
          derivApp.commonPage.mobileLocators.sideMenu.depositButton().click()
        })
      } else {
        derivApp.commonPage.desktopLocators.header.cashierButton().click()
      }
      cy.c_loadingCheck()
```

2024-06-26 05:53 UTC, abuzar-deriv approved these changes
LGTM

2024-06-28 04:12 UTC, maliheh-deriv approved these changes

2024-06-28 05:13 UTC, meeyun-deriv approved these changes
LGTM

2024-06-28 05:14 UTC, merged