Afsaneh/fix
deriv-com/e2e-deriv-app pull request #425
Opened 2024-06-26 09:33 UTC by afsaneh-rezaeinejad-deriv

2024-06-26 10:01 UTC, meeyun-deriv requested changes

2024-06-26 10:01 UTC, meeyun-deriv commented on cypress/e2e/smoke/Wallets/accountSwitcher.cy.js
> +  it.only('Responsive - Navigate to account switcher from Trade page &  Manage account settings page', () => {
is this `only` accidentally put here?

2024-06-26 10:01 UTC, meeyun-deriv commented on cypress/e2e/smoke/Wallets/walletSwitcher.cy.js
> +  // .then(() =>
remove the comment part if it is not needed anymore

2024-06-27 02:28 UTC, abuzar-deriv commented on cypress/support/commands/common.js
> +Cypress.Commands.add('c_WaitUntilPageIsLoaded', () => {
Since this is wallets specific, can you please move it to wallets.js and reanme to `c_WaitUntilWalletsPageIsLoaded`?

2024-06-27 02:28 UTC, abuzar-deriv requested changes
Slight change needed in command name and location.

2024-06-27 06:13 UTC, abuzar-deriv approved these changes
LGTM

2024-06-27 10:21 UTC, meeyun-deriv approved these changes
LGTM

2024-07-02 07:17 UTC, merged