fixed demo transactions failures
deriv-com/e2e-deriv-app pull request #432
Opened 2024-06-28 04:38 UTC by zubair-deriv

### Card 

https://app.clickup.com/t/20696747/WALL-4487

2024-06-28 09:01 UTC, maliheh-deriv approved these changes

2024-06-28 09:01 UTC, abuzar-deriv requested changes
Requesting minor changes.

2024-06-28 09:01 UTC, abuzar-deriv commented on cypress/e2e/smoke/Wallets/demoResetBalance.cy.js
> +    cy.findAllByText(/Wallet/, { timeout: 10000 }).should('exist')
This will make the test pass if /Wallet/ is any number gte 1. Better to either add eq(n) to assert the exact element, or to assert the exact count of the expected /Wallet/ elements. Same for rest of the instances.

2024-06-28 09:05 UTC, zubair-deriv commented on cypress/support/commands/wallets.js
>    /// this is a temp solution for https://deriv-group.slack.com/archives/C0548T15K1P/p1714546473367569
not sure about this change, since I didn't touch this part in my PR

2024-06-28 09:08 UTC, zubair-deriv commented on cypress/e2e/smoke/Wallets/demoResetBalance.cy.js
> +    cy.findAllByText(/Wallet/, { timeout: 10000 }).should('exist')
The purpose of this assertion is just to wait for the passkey modal to be visible.
Test was failing by using `findByText`, so that's why it is updated to `findAllByText`

2024-07-01 01:07 UTC, abuzar-deriv commented on cypress/support/commands/wallets.js
>    /// this is a temp solution for https://deriv-group.slack.com/archives/C0548T15K1P/p1714546473367569
Sure. Can you or @afsaneh-rezaeinejad-deriv please check if this can be removed in your next change?

2024-07-01 01:07 UTC, abuzar-deriv approved these changes
LGTM

2024-07-01 02:15 UTC, zubair-deriv commented on cypress/support/commands/wallets.js
>    /// this is a temp solution for https://deriv-group.slack.com/archives/C0548T15K1P/p1714546473367569
sure @abuzar-deriv, I will discuss this with @afsaneh-rezaeinejad-deriv, Thanks of raising this

2024-07-02 08:35 UTC, merged