Trigger KYC in different scenarios
deriv-com/e2e-deriv-app pull request #438
Opened 2024-06-28 15:03 UTC by deborah-deriv

**Trigger KYC in different scenarios**
These are end-to-end tests for different scenarios that trigger both POI and POA

2024-07-22 10:14 UTC, meeyun-deriv requested changes

2024-07-22 10:14 UTC, meeyun-deriv commented on cypress/e2e/manual/kyc/kycDifferentScenariosHighRiskMt5.cy.js
> +    /* submit FA */
can consider to put this in a custom common, as it will be needed eventually when we do testing on FA

2024-07-22 10:14 UTC, meeyun-deriv commented on cypress/e2e/smoke/KYC/kycDifferentScenarioP2pAdvertizer.cy.js
> +    cy.contains('li', 'My ads').click()
i think it has a better locator in testing library

2024-07-22 10:14 UTC, meeyun-deriv commented on cypress/e2e/manual/kyc/kycDifferentScenariosHighRiskMt5.cy.js
> +      'be.visible'
these lines quite repeatitive in few spec files. Lets put in a custom command to handle this so we dont need to keep repeat the same codes

2024-07-22 10:14 UTC, meeyun-deriv commented on cypress/e2e/manual/kyc/kycDifferentScenariosHighRiskMt5.cy.js
> +    )
same to this - also repeated many times in different spec files

2024-07-22 14:08 UTC, deborah-deriv commented on cypress/e2e/manual/kyc/kycDifferentScenariosHighRiskMt5.cy.js
> +    /* submit FA */
This is addressed

2024-07-22 14:08 UTC, deborah-deriv commented on cypress/e2e/manual/kyc/kycDifferentScenariosHighRiskMt5.cy.js
> +      'be.visible'
Custom command created

2024-07-22 14:09 UTC, deborah-deriv commented on cypress/e2e/manual/kyc/kycDifferentScenariosHighRiskMt5.cy.js
> +    )
custom command created

2024-07-22 14:33 UTC, deborah-deriv commented on cypress/e2e/smoke/KYC/kycDifferentScenarioP2pAdvertizer.cy.js
> +    cy.contains('li', 'My ads').click()
This is addressed

2024-07-23 02:58 UTC, bilalmajid-deriv reviewed
Left some comments

2024-07-23 02:58 UTC, bilalmajid-deriv commented on cypress/e2e/manual/kyc/kycDifferentScenariosHighRiskMt5.cy.js
> +    cy.c_visitResponsive('/', 'large')
this is not needed as the view port is being set in the next command
```suggestion
```

2024-07-23 02:58 UTC, bilalmajid-deriv commented on cypress/support/commands/kyc.js
> -  cy.c_closeNotificationHeader()
We do need these lines dont we?

2024-07-23 03:37 UTC, meeyun-deriv approved these changes
LGTM - please check Bilal comments too

2024-07-23 08:38 UTC, deborah-deriv commented on cypress/support/commands/kyc.js
> -  cy.c_closeNotificationHeader()
Sorry added back

2024-07-23 08:38 UTC, deborah-deriv commented on cypress/e2e/manual/kyc/kycDifferentScenariosHighRiskMt5.cy.js
> +    cy.c_visitResponsive('/', 'large')
This is removed

2024-07-24 08:36 UTC, bilalmajid-deriv approved these changes
LGTM

2024-07-24 08:58 UTC, bilalmajid-deriv requested changes
Can you also resolve conflicts

2024-07-24 08:58 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/kycDifferentScenarioMfClient.cy.js
> +    cy.c_visitResponsive('/cashier/', 'small')
```suggestion
    cy.c_visitResponsive('/cashier/', { size: 'mobile' })
```

2024-07-24 08:58 UTC, bilalmajid-deriv commented on cypress/e2e/manual/kyc/kycDifferentScenariosHighRiskMt5.cy.js
> +    cy.c_visitResponsive('/cashier/', 'small')
```suggestion
    cy.c_visitResponsive('/cashier/', { size: 'mobile' })
```

2024-07-24 08:58 UTC, bilalmajid-deriv commented on cypress/e2e/manual/kyc/kycDifferentScenariosHighRiskMt5.cy.js
> +    cy.c_visitResponsive('/cashier/', 'small')
```suggestion
    cy.c_visitResponsive('/cashier/', { size: 'mobile' })
```

2024-07-24 08:58 UTC, bilalmajid-deriv commented on cypress/e2e/manual/kyc/kycDifferentScenariosHighRiskMt5.cy.js
> +    cy.c_visitResponsive('/cashier/', 'small')
```suggestion
    cy.c_visitResponsive('/cashier/', { size: 'mobile' })
```

2024-07-24 08:58 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/KYC/kycDifferentScenarioP2pAdvertizer.cy.js
> +    cy.c_visitResponsive('/cashier/', 'small')
```suggestion
    cy.c_visitResponsive('/cashier/', { size: 'mobile' })
```

2024-07-24 08:58 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/KYC/kycDifferentScenarioP2pAdvertizer.cy.js
> +    cy.c_visitResponsive('/account/proof-of-address/', 'small')
```suggestion
    cy.c_visitResponsive('/account/proof-of-address/', { size: 'mobile' })
```

2024-07-24 08:58 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/KYC/kycDifferentScenarioP2pAdvertizer.cy.js
> +    cy.c_visitResponsive('/cashier/', 'small')
```suggestion
    cy.c_visitResponsive('/cashier/', { size: 'mobile' })
```

2024-07-24 08:58 UTC, bilalmajid-deriv commented on cypress/e2e/wip/KYC/kycDifferentScenarioDeposit.cy.js
> +    cy.c_visitResponsive('/cashier/', 'small')
```suggestion
    cy.c_visitResponsive('/cashier/', { size: 'mobile' })
```

2024-07-24 10:03 UTC, bilalmajid-deriv requested changes
changes requested

2024-07-24 10:03 UTC, bilalmajid-deriv commented on cypress/e2e/manual/kyc/kycDifferentScenariosHighRiskMt5.cy.js
> +    cy.c_visitResponsive('/', 'small')
```suggestion
    cy.c_visitResponsive('/', { size: 'mobile' })
```

2024-07-24 10:03 UTC, bilalmajid-deriv commented on cypress.config.js
> +          },
please correct this

2024-07-24 10:38 UTC, bilalmajid-deriv commented on cypress.config.js
> -      },
We need this closing bracket

2024-07-24 10:44 UTC, bilalmajid-deriv approved these changes

2024-07-24 10:46 UTC, merged