Spec added for Dtrader trading
deriv-com/e2e-deriv-app pull request #441
Opened 2024-07-01 06:49 UTC by zubair-deriv

### Card 
https://app.clickup.com/t/20696747/WALL-4448

2024-07-02 07:09 UTC, meeyun-deriv requested changes

2024-07-02 07:09 UTC, meeyun-deriv commented on cypress/support/commands/wallets.js
> +  cy.get('.dc-contract-card').should('be.visible')
how does it make sure this contract is bought from this test steps? As we do not close any accumulative contract, the contract which bought in previous run could give false positive result here

2024-07-03 10:06 UTC, zubair-deriv commented on cypress/support/commands/wallets.js
> +  cy.get('.dc-contract-card').should('be.visible')
@meeyun-deriv Previously validation check was only added for the reports page. 
Now, I have updated the verification check for dtrader page screen too.

2024-07-05 01:38 UTC, meeyun-deriv requested changes

2024-07-05 01:38 UTC, meeyun-deriv commented on cypress/support/commands/wallets.js
> +  cy.get('.dc-contract-card').should('be.visible')
but my concern is that we do not validate if the contract is purchase successfully. E.g. After clicking the buy button, if there is any pop up message indicate the contract cannot purchase, current cypress code will not catch that issue.

Although we check if there are contract exists in the report page or dtrader, if the test account already had previous purchased contract, then it will give false positive check.

2024-07-22 08:53 UTC, meeyun-deriv approved these changes
LGTM

2024-07-22 09:37 UTC, afsaneh-rezaeinejad-deriv requested changes

2024-07-22 09:37 UTC, afsaneh-rezaeinejad-deriv commented on cypress/e2e/smoke/Wallets/migrationAccountCanTradeDTrader.cy.js
> +    cy.c_login({ user: 'walletDemoAccount' })
@zubair-deriv we should avid adding extra variable to secret file. you can create a fresh account and migrate it, in this way transfer to demo is also not required

2024-07-22 09:55 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/migrationAccountCanTradeDTrader.cy.js
> +  let firstAccount = 'Options'
move this up with the other variable on line 1

2024-07-22 09:55 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/migrationAccountCanTradeDTrader.cy.js
> +}
Recommendation : better to create this a command and parameterized one as this can be used for multiple tests I assume.
And add verification before and after on the balance to make sure the balance is actually transferred.

2024-07-22 09:55 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/migrationAccountCanTradeDTrader.cy.js
> +  it('real - migrated account should be able to trade - DTrader', () => {
rename all test names to the format 
it('shouldbe able to .......... on mobile',()=>{})
it('shouldbe able to .......... on desktop',()=>{})

2024-07-22 11:20 UTC, zubair-deriv commented on cypress/e2e/smoke/Wallets/migrationAccountCanTradeDTrader.cy.js
> +    cy.c_login({ user: 'walletDemoAccount' })
A new created account doesn't have currency in real wallet, and we need currency to trade in dTrader

2024-07-22 11:23 UTC, zubair-deriv commented on cypress/e2e/smoke/Wallets/migrationAccountCanTradeDTrader.cy.js
> +}
Improvement task updated for this change: https://app.clickup.com/t/20696747/WALL-4571

2024-07-26 08:22 UTC, bilalmajid-deriv approved these changes
LGTM

2024-07-26 08:25 UTC, afsaneh-rezaeinejad-deriv approved these changes
LGTM

2024-07-29 09:38 UTC, merged