Dashboard - Quick strategy & Bot Builder (mobile)
deriv-com/e2e-deriv-app pull request #446
Opened 2024-07-02 06:31 UTC by paveetra-deriv

Check to ensure that Bot Builder and Quick Strategy is accessible from Dashboard tab. 
Covering for Mobile & Responsive mode.

2024-07-02 08:08 UTC, abuzar-deriv approved these changes
LGTM

2024-07-02 08:09 UTC, abuzar-deriv commented
Please don't use ci skip; we need the workflows.

2024-07-04 09:54 UTC, meeyun-deriv requested changes

2024-07-04 09:54 UTC, meeyun-deriv commented on cypress/e2e/smoke/dbot/DashboardQuickAction.cy.js
>  describe('QATEST-4128: Dashboard quick action to Quick Strategy and Bot Builder', () => {
this test id is outdated, please help to update it

2024-07-04 10:47 UTC, meeyun-deriv approved these changes
LGTM

2024-07-04 10:47 UTC, merged