Wall 3858
deriv-com/e2e-deriv-app pull request #455
Opened 2024-07-03 09:55 UTC by mohammedluqmaan-deriv

Added switch all available wallets.

2024-07-04 03:11 UTC, afsaneh-rezaeinejad-deriv approved these changes
LGTM

2024-07-05 13:29 UTC, markodonnell-deriv requested changes
I'm not seeing any testing library queries here for the locators.
This may often be the case with Wallets but could you double-check?

2024-07-12 04:05 UTC, meeyun-deriv requested changes
we have existing test covered ETH and BTC, can you please update the remaining in the existing test?

2024-07-12 05:15 UTC, mohammedluqmaan-deriv commented
> we have existing test covered ETH and BTC, can you please update the remaining in the existing test?



> we have existing test covered ETH and BTC, can you please update the remaining in the existing test?

Added the test in existing file cypress/e2e/smoke/Wallets/walletSwitcher.cy.js, Thank you.

2024-07-12 05:17 UTC, mohammedluqmaan-deriv commented
> I'm not seeing any testing library queries here for the locators. This may often be the case with Wallets but could you double-check?

I did use few things like aliases and common looping for [actions] but will get to know about testing library queries as-well, Thanks

2024-07-12 07:42 UTC, meeyun-deriv requested changes
we have existing test QATEST-139905 in this file:
…/cypress/e2e/smoke/Wallets/wallerCashierRedirection.cy.js

Can you please help to update in this file instead?

2024-07-16 09:18 UTC, afsaneh-rezaeinejad-deriv approved these changes
LGTM

2024-07-16 09:39 UTC, mohammedluqmaan-deriv commented on cypress/e2e/smoke/Wallets/walletCashierRedirection.cy.js
> +    cy.c_skipPasskeysV2()
Thank you have removed it.

2024-07-17 09:11 UTC, meeyun-deriv approved these changes
LGTM

2024-07-17 09:12 UTC, merged