disable passkey from local storage
deriv-com/e2e-deriv-app pull request #465
Opened 2024-07-08 03:45 UTC by meeyun-deriv

2024-07-08 14:12 UTC, markodonnell-deriv submitted a review, later dismissed
Looks good generally, pending your TODOs and a couple minor commnents.

I assume lines 31-33 be removed, and the command c_skipPasskeysV2 will be removed altogether?

2024-07-08 14:12 UTC, markodonnell-deriv commented on cypress/support/commands/common.js
>    cy.c_visitResponsive('/endpoint', 'large', { rateLimitCheck: rateLimitCheck })
Should this not be moved in to c_setDerivAppEndpoint?

2024-07-09 05:43 UTC, abuzar-deriv reviewed
Minor change in name

2024-07-09 05:43 UTC, abuzar-deriv commented on cypress/support/commands/common.js
> +Cypress.Commands.add('disablePasskey', (options = {}) => {
To align with current naming convention:
```suggestion
Cypress.Commands.add('c_disablePasskey', (options = {}) => {
```

2024-07-09 06:07 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Passkeys/passkeys.cy.js
> +      cy.c_setDerivAppEndpoint()
do we not have to pass the app here?

2024-07-09 06:07 UTC, bilalmajid-deriv commented on cypress/support/commands/common.js
> +    cy.disablePasskey()
```suggestion
    cy.c_disablePasskey()
```

2024-07-09 06:07 UTC, bilalmajid-deriv commented on cypress/support/commands/common.js
> +  cy.c_setDerivAppEndpoint(app, backEndProd, user).then(() => {
as per code we do not need to pass backEndProd and user instead need to pass loginEmail, loginPassword
```suggestion
  cy.c_setDerivAppEndpoint(app, loginEmail, loginPassword).then(() => {
```

2024-07-10 09:19 UTC, meeyun-deriv commented on cypress/support/commands/common.js
> +  cy.c_setDerivAppEndpoint(app, backEndProd, user).then(() => {
as discussed these will still needed for `c_setDerivAppEndpoint`

2024-07-11 02:44 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Passkeys/passkeys.cy.js
> +        cy.findByLabelText('Login with passkeys').should('not.visible')
Should this not remain 'not.exist' or do we have the element available in html and it is 'not.visible'

2024-07-11 08:46 UTC, meeyun-deriv commented on cypress/e2e/smoke/Passkeys/passkeys.cy.js
> +        cy.findByLabelText('Login with passkeys').should('not.visible')
yes, the element is available in html but will not visible on the desktop view

2024-07-11 09:14 UTC, bilalmajid-deriv approved these changes
LGTM

2024-07-12 02:11 UTC, abuzar-deriv requested changes

2024-07-12 02:11 UTC, abuzar-deriv commented on cypress/e2e/full/cashierLegacy/paymentAgentDepositScreenLoad.cy.js
> +      cy.c_visitResponsive('appstore/traders-hub', screenSize, {})
No need to pass empty obj here since it's there in default args.
```suggestion
      cy.c_visitResponsive('appstore/traders-hub', screenSize)
```

2024-07-12 02:11 UTC, abuzar-deriv commented on cypress/e2e/smoke/Wallets/accountSwitcher.cy.js
>      cy.get('.wallets-trading-account-card__content')
This was earlier part of else block but now it's not? Is this change intentional?

2024-07-12 03:06 UTC, abuzar-deriv approved these changes
LGTM

2024-07-12 03:27 UTC, maliheh-deriv approved these changes

2024-07-12 03:30 UTC, merged