BOT-1875 prod bug test
deriv-com/e2e-deriv-app pull request #471
Opened 2024-07-10 06:28 UTC by thivya-deriv

2024-07-10 09:42 UTC, bilalmajid-deriv approved these changes

2024-07-10 09:42 UTC, abuzar-deriv commented on cypress/e2e/smoke/dbot/QuickStrategies.cy.js
> +              cy.log(`Duration ${value2} is visible`)
if(!value) , fail the test.

2024-07-10 11:40 UTC, meeyun-deriv requested changes
the test seems missing the winning scenario - where the stake will use the same amount

2024-07-10 11:40 UTC, meeyun-deriv commented on cypress/e2e/smoke/dbot/QuickStrategies.cy.js
> +      cy.wait(7000)
why the wait?

2024-07-10 13:54 UTC, thivya-deriv commented on cypress/e2e/smoke/dbot/QuickStrategies.cy.js
> +      cy.wait(7000)
Fixed now

2024-07-10 13:54 UTC, thivya-deriv commented on cypress/e2e/smoke/dbot/QuickStrategies.cy.js
> +              cy.log(`Duration ${value2} is visible`)
This is done

2024-07-12 02:46 UTC, abuzar-deriv commented on cypress/e2e/smoke/dbot/QuickStrategies.cy.js
> +          cy.get('[data-testid="dt_qs_durationtype"]')
Why this; why not?
```suggestion
          cy.findByTestId('dt_qs_durationtype')
```

2024-07-12 02:47 UTC, abuzar-deriv commented on cypress/e2e/smoke/dbot/QuickStrategies.cy.js
> +              cy.log(`Duration ${value2} is visible`)
Where? 😅

2024-07-12 03:08 UTC, thivya-deriv commented on cypress/e2e/smoke/dbot/QuickStrategies.cy.js
> +              cy.log(`Duration ${value2} is visible`)
Please check again now

2024-07-12 03:10 UTC, thivya-deriv commented
> the test seems missing the winning scenario - where the stake will use the same amount

This will be done separately in BOT-1973

2024-07-12 03:11 UTC, abuzar-deriv approved these changes
LGTM

2024-07-12 03:54 UTC, meeyun-deriv approved these changes
LGTM

2024-07-12 03:54 UTC, merged