Toolbar Reset on Mobile and Desktop
deriv-com/e2e-deriv-app pull request #478
Opened 2024-07-11 05:51 UTC by thivya-deriv

Card: https://app.clickup.com/t/20696747/BOT-1950
Desc: This is to cover test on reseting workspace from toolbar

2024-07-11 06:23 UTC, rajendra-deriv commented on cypress/e2e/smoke/dbot/Toolbar.cy.js
> +      //Save strategy from toolbar
You can remove the commented line as there is a Logger message which states the same.

2024-07-11 06:23 UTC, rajendra-deriv commented on cypress/e2e/smoke/dbot/Toolbar.cy.js
> +      //Import strategy from toolbar
You can remove the commented line as there is a Logger message which states the same.

2024-07-11 11:26 UTC, rajendra-deriv approved these changes

2024-07-12 03:27 UTC, abuzar-deriv requested changes
Looks good but please add testid QATEST-4238 to the file.

2024-07-12 03:46 UTC, abuzar-deriv approved these changes
LGTM

2024-07-12 03:49 UTC, abuzar-deriv approved these changes
LGTM

2024-07-12 03:49 UTC, merged