update
deriv-com/e2e-deriv-app pull request #484
Opened 2024-07-15 08:58 UTC by afsaneh-rezaeinejad-deriv

2024-07-16 05:27 UTC, meeyun-deriv requested changes

2024-07-16 05:27 UTC, meeyun-deriv commented on cypress/e2e/smoke/Wallets/walletMigrationSuccess.cy.js
> +    cy.c_createCRAccount({ country_code: 'aq' })
lets put it in a list so that we can support more wallet countries in future

2024-07-16 05:27 UTC, meeyun-deriv commented on cypress/e2e/smoke/Wallets/walletMigrationSuccess.cy.js
> +  cy.findAllByText(/Wallet/, { timeout: 10000 }).should('exist')
I think we need to make sure deposit and withdrawal page loaded properly

2024-07-17 04:21 UTC, abuzar-deriv approved these changes
LGTM

2024-07-17 06:24 UTC, meeyun-deriv requested changes
Can you please check why the test is running in desktop view?

2024-07-17 07:48 UTC, meeyun-deriv approved these changes
LGTM

2024-07-17 09:09 UTC, merged