Verify SmartCharts in the Toolbar Section on Bot Builder
deriv-com/e2e-deriv-app pull request #499
Opened 2024-07-22 05:24 UTC by paveetra-deriv

Checking if the Charts toolbar is working fine on Bot Builder.
Ensure charts is loading fine, and able to select another asset.

2024-07-22 05:42 UTC, meeyun-deriv requested changes

2024-07-22 05:42 UTC, meeyun-deriv commented on cypress/e2e/smoke/dbot/Toolbar.cy.js
> +        cy.wait(3000)
lets not have hard wait. By default cypress should have automatically retry to find the element in the default timeout duration (we set the default timeout to 15s in the config file). If you are seeing the element takes more time to load, you can set the timeout in the query that you want, e.g.
```
cy.findAllByTestId('dt_toolbar_chart_button').should('be.visible', {
        timeout: 30000,
      })

2024-07-22 05:42 UTC, meeyun-deriv commented on cypress/e2e/smoke/dbot/Toolbar.cy.js
> +        cy.findByTestId('dt_react_draggable-close-modal').click()
we have an action here but we dont have any validation after this. Does it has missing validation?

2024-07-22 05:42 UTC, meeyun-deriv commented on cypress/e2e/smoke/dbot/Toolbar.cy.js
> +        cy.log('Clicking Charts from Toolbar')
we can remove this log as this is not useful

2024-07-22 05:42 UTC, meeyun-deriv commented on cypress/e2e/smoke/dbot/Toolbar.cy.js
> +  const sizes = ['small', 'desktop'] // Changed `size` to `sizes` to avoid naming conflict
comment is not needed

2024-07-22 06:21 UTC, paveetra-deriv commented on cypress/e2e/smoke/dbot/Toolbar.cy.js
> +        cy.findByTestId('dt_react_draggable-close-modal').click()
I will a check to ensure that chart dialog is not there once clicking on close icon? Does that work?

2024-07-23 10:38 UTC, meeyun-deriv requested changes
LGTM

2024-07-23 14:54 UTC, indulekha-deriv commented on cypress/e2e/smoke/dbot/Toolbar.cy.js
> +      if (isDesktop) {
If lines 46-50 is same for tablet view then instead of adding a constant i_sDesktop_ we can give condition when not isMobile. (!isMobile) so that in future no code change will be required for this spec.

2024-07-24 05:37 UTC, indulekha-deriv approved these changes

2024-07-24 09:01 UTC, meeyun-deriv approved these changes
LGTM

2024-07-24 09:35 UTC, closed without merging