standardized viewport through out project
deriv-com/e2e-deriv-app pull request #501
Opened 2024-07-22 07:59 UTC by bilalmajid-deriv

- Standardized all screenSizes for all tests to use 'mobile', 'desktop'
- options now available will be : 'mobile', 'tablet' and 'desktop'
- Updated all commands that use cy.c_visitResponsive() to pass an optional parameter for size which will default to 'desktop' size. example: cy.c_login(), cy.c_doOauthLogin() etc.
- removed all extra steps of visit after login because now login will visit in specified screen size.
Note : some test are still using visit after login because did not want to change of structure of test and will be done in separate PR to avoid complexity in this huge PR.

GH Worflow for Smoke Test: https://github.com/regentmarkets/e2e-deriv-app/actions/runs/10036272146
GH workflow for Full Test: https://github.com/regentmarkets/e2e-deriv-app/actions/runs/10036277341

2024-07-23 05:05 UTC, bilalmajid-deriv commented
The screen sizes for all the test are now standardized to `mobile` `tablet` and `desktop` and all the custom commands that are using visitResponsive can now take an optional parameter for size All the commands will be defaulting to the desktop size  
Commands that are now able to take size as an optional parameter: 
cy.c_setEndpoint() 
cy.c_visitResponsive() 
cy.c_login() 
cy.c_doOAuthLogin()
cy.c_createDemoAccount() 
cy.c_createMFAccount() 
cy.c_createCRAccount()  
I have updated all previous tests to adapt to the new changes. It is recommended that these three terms are now used `mobile` `tablet` and `desktop` for size and avoid terms like `small` `large` or `responsive` to maintain uniformity.

Now you can run complete flow for either of the sizes from login to the last verification. (Some tests are still using login in desktop and then running test in mobile size this will be covered in a separate PR as this demanded more structural changes in the spec files ) 

Note:  BackOffice and /events is still using desktop size only.

2024-07-23 05:43 UTC, bilalmajid-deriv commented
The failures due to this PR are verified and fixed remaining errors are not due to this PR

2024-07-23 09:46 UTC, abuzar-deriv reviewed
question: If we're picking default size from env var for `c_visitResponsive`, why are we not doing the same for rest of the commands such as `c_doOAuthLogin`?

2024-07-23 10:29 UTC, markodonnell-deriv requested changes

2024-07-23 10:29 UTC, markodonnell-deriv commented on cypress.config.js
> +    viewPortSize: 'desktop',
Should this not be defaulting to mobile?

2024-07-24 03:02 UTC, bilalmajid-deriv commented on cypress.config.js
> +    viewPortSize: 'desktop',
Hi @markodonnell-deriv previously as well the size small was supposed to be set as default but was defaulting to large screen size when no parameter for size was passed. To mimic that I set it up as desktop.

so previously without a mandatory size parameter we visited the page on large/desktop size
and now without the optional parameter we visit the page on desktop/large size

I can make the default viewPortSize to be mobile. what ever is suggested.

2024-07-24 03:08 UTC, abuzar-deriv commented on cypress.config.js
> +    viewPortSize: 'desktop',
I suggest we set it to mobile since we are aiming for mobile first approach. 🙏

2024-07-24 03:38 UTC, abuzar-deriv approved these changes
LGTM

2024-07-24 03:47 UTC, meeyun-deriv approved these changes
LGTM

2024-07-24 06:01 UTC, maliheh-deriv commented on cypressTemplate.config.js
> +    emailVerificationCode: process.env.E2E_EMAIL_VERIFICATION_CODE,
Duplicate line , please remove one of them .

2024-07-24 06:02 UTC, maliheh-deriv commented on cypressTemplate.config.js
> +    specPattern: 'cypress_template/e2e/**/*.js',
Duplicate lines 14,15 .

2024-07-24 06:04 UTC, maliheh-deriv commented on cypress/support/commands/tradersHub.js
> +  cy.get('.wallets-skeleton.wallets-add-more-loader').should('not.exist', {
could we improve element locator ?

2024-07-24 06:12 UTC, maliheh-deriv commented on cypress/support/commands/common.js
> +  if (size == 'mobile' || size != 'tablet' || size != 'desktop') {
if result always be true here.

2024-07-24 06:44 UTC, bilalmajid-deriv commented on cypress/support/commands/common.js
> +  if (size == 'mobile' || size != 'tablet' || size != 'desktop') {
updated

2024-07-24 06:44 UTC, bilalmajid-deriv commented on cypress/support/commands/tradersHub.js
> +  cy.get('.wallets-skeleton.wallets-add-more-loader').should('not.exist', {
this loader is only accessible using the class hence can not use any other locator

2024-07-24 06:45 UTC, bilalmajid-deriv commented on cypressTemplate.config.js
> +    emailVerificationCode: process.env.E2E_EMAIL_VERIFICATION_CODE,
Done

2024-07-24 06:46 UTC, bilalmajid-deriv commented on cypressTemplate.config.js
> +    specPattern: 'cypress_template/e2e/**/*.js',
Removed

2024-07-24 06:51 UTC, maliheh-deriv approved these changes

2024-07-24 07:19 UTC, markodonnell-deriv commented on cypress.config.js
> +    viewPortSize: 'desktop',
> Hi @markodonnell-deriv previously as well the size small was supposed to be set as default but was defaulting to large screen size when no parameter for size was passed. To mimic that I set it up as desktop.
> 
> so previously without a mandatory size parameter we visited the page on large/desktop size and now without the optional parameter we visit the page on desktop/large size
> 
> I can make the default viewPortSize to be mobile. what ever is suggested.

Understood, but yeah, mobile default was the intention, even if small didn't actually work :)

2024-07-24 07:19 UTC, markodonnell-deriv approved these changes
Looks good!

2024-07-24 07:25 UTC, merged