Afsaneh/mt5 change pass
deriv-com/e2e-deriv-app pull request #504
Opened 2024-07-22 10:22 UTC by afsaneh-rezaeinejad-deriv

use fresh account for mt5 change password test
CU: https://app.clickup.com/t/20696747/WALL-4384

2024-07-24 10:12 UTC, bilalmajid-deriv requested changes
Please update the visits and login

2024-07-24 10:12 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/mt5ResetPassword.cy.js
> +            cy.c_visitResponsive(Cypress.env('verificationUrl'), 'large')
```suggestion
            cy.c_visitResponsive(Cypress.env('verificationUrl'), { size: 'desktop' })
```

2024-07-24 10:12 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/mt5ResetPassword.cy.js
> +    cy.c_visitResponsive('/', 'large')
```suggestion
    cy.c_visitResponsive('/', { size: 'desktop' })
```

2024-07-24 10:12 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/mt5ResetPassword.cy.js
> +    cy.c_login({ user: 'walletloginEmail' })
```suggestion
    cy.c_login({ user: 'walletloginEmail', app: 'wallets })
```

2024-07-24 10:12 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/mt5ResetPasswordResponsive.cy.js
> +            cy.c_visitResponsive(Cypress.env('verificationUrl'), 'large')
```suggestion
            cy.c_visitResponsive(Cypress.env('verificationUrl'), { size: 'desktop' })
```

2024-07-24 10:12 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/mt5ResetPasswordResponsive.cy.js
> +    cy.c_visitResponsive('/', 'small')
```suggestion
    cy.c_visitResponsive('/', { size: 'mobile' })
```

2024-07-24 10:12 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/mt5ResetPasswordResponsive.cy.js
> +  it('should be able to change mt5 password in responsive', () => {
```suggestion
  it('should be able to change mt5 password on mobile', () => {
```

2024-07-24 10:12 UTC, bilalmajid-deriv commented on cypress/e2e/smoke/Wallets/mt5ResetPasswordResponsive.cy.js
> +    cy.c_login({ user: 'walletloginEmail' })
```suggestion
    cy.c_login({ user: 'walletloginEmail', app: 'wallets' })
```

2024-07-24 10:12 UTC, bilalmajid-deriv commented on cypress/support/commands/wallets.js
> +  cy.c_visitResponsive('/', size) // Replace with your actual command to visit a responsive URL
```suggestion
  cy.c_visitResponsive('/', {size: size }) // Replace with your actual command to visit a responsive URL
```

2024-07-24 10:12 UTC, bilalmajid-deriv commented on cypress/support/commands/wallets.js
> +  cy.c_login({ relogin: true })
```suggestion
  cy.c_login({ relogin: true, app: 'wallets' })
```

2024-07-24 10:12 UTC, bilalmajid-deriv commented on cypress/e2e/wip/Wallets/addcryptoWallet.cy.js
> +    cy.c_login()
If this will login to wallet UI then do this but of it logs in to the tradershub UI then can leave it as it is
```suggestion
    cy.c_login({ app: 'wallets' })
```

2024-07-24 11:35 UTC, indulekha-deriv commented on cypress/e2e/smoke/Wallets/mt5ResetPassword.cy.js
> +            .type(Cypress.env('credentials').test.mt5User.PSWD)
Need to add invalid password check.

2024-07-24 11:36 UTC, indulekha-deriv commented on cypress/e2e/smoke/Wallets/mt5ResetPasswordResponsive.cy.js
> +          cy.findByRole('button', { name: 'Create' }).click()
Include invalid password check as per test case bank

2024-07-26 07:58 UTC, bilalmajid-deriv commented on cypress/support/commands/wallets.js
> +  cy.c_visitResponsive('/', size) // Replace with your actual command to visit a responsive URL
missed this one here

2024-07-26 08:17 UTC, indulekha-deriv approved these changes

2024-07-26 08:18 UTC, bilalmajid-deriv approved these changes

2024-07-26 08:29 UTC, indulekha-deriv commented on cypress/e2e/smoke/Wallets/addcryptoWallet.cy.js
> +    // it('should be able to add more wallets on mobile', () => {
Can we delete these commented lined if not required.

2024-07-26 08:34 UTC, indulekha-deriv approved these changes

2024-07-26 08:34 UTC, merged