IDV POI Submission -- name mismatch
deriv-com/e2e-deriv-app pull request #73
Opened 2024-02-05 15:33 UTC by bertrand-deriv

## IDV POI Submission -- name mismatch [Work in progress]
- setup cypress directory for kyc
- added a custom command
- developed test scenario for name mismatch

2024-02-05 17:19 UTC, markodonnell-deriv requested changes
Can you exclude the node modules from this PR?

2024-02-05 17:19 UTC, markodonnell-deriv commented on cypress/e2e/wip/KYC/idvPoi.cy.js
> +describe('IDV POI submission', () => {
Could you add the test case code? See other tests for example formate.

2024-02-06 09:06 UTC, bertrand-deriv commented on cypress/e2e/wip/KYC/idvPoi.cy.js
> +describe('IDV POI submission', () => {
Yes. it is still in progress

2024-02-07 07:34 UTC, bertrand-deriv commented on cypress/e2e/wip/KYC/idvPoi.cy.js
> +describe('IDV POI submission', () => {
Hi @markodonnell-deriv  It seems someone has merged node modules folder on master 3 weeks ago. The reason why I was having those changes on my PR is that I have pulled the latest master changes into my branch few days ago. I have removed the node modules folder on my branch.

2024-02-07 13:44 UTC, markodonnell-deriv approved these changes
Looks good

2024-02-07 13:45 UTC, markodonnell-deriv commented on cypress/e2e/wip/KYC/idvPoi.cy.js
> +describe('IDV POI submission', () => {
OK, understood. Please add the test case task id as soon as possible.

2024-02-07 14:07 UTC, merged