Verify MF user signup flow
deriv-com/e2e-deriv-app pull request #83
Opened 2024-02-13 09:11 UTC by abuzar-deriv

1. Added MF user signup flow test
2. Moved assertion from c_addressDetails command to cypress/e2e/full/userSignupROW.cy.js to make the command reusable
3. Added new config variables

2024-02-13 09:39 UTC, markodonnell-deriv requested changes
Looks really good. Just a minor issue regarding the use of ; (see coding standards in e2e wiki).
![image](https://github.com/deriv-com/e2e-deriv-app/assets/144238191/5ad92cfe-f0ff-4ea5-99bd-e04d81dae87d)

2024-02-15 08:42 UTC, rajendra-deriv commented on cypress/e2e/wip/Tradershub/accountSignupMF.cy.js
> +    cy.wait(5000) //TODO - To be replaced by a loop within the emailVerification below.
Do you have a card planned for it? Else plz keep track of this TODO

2024-02-15 08:51 UTC, abuzar-deriv commented on cypress/e2e/wip/Tradershub/accountSignupMF.cy.js
> +    cy.wait(5000) //TODO - To be replaced by a loop within the emailVerification below.
I will update it within https://app.clickup.com/t/20696747/TRAH-2808

2024-02-15 09:07 UTC, rajendra-deriv approved these changes
Changes looks good to me. Approving.

2024-02-15 17:51 UTC, markodonnell-deriv approved these changes
Looks good

2024-02-15 17:52 UTC, merged