Validate chart is updating
deriv-com/e2e-deriv-app pull request #88
Opened 2024-02-19 09:26 UTC by meeyun-deriv

This PR is still a work in progress (no review needed until the work is done).

This PR aims to validate that the chart is updating and not broken. The process involves the following steps:

1. Open the Deriv app and create the first screenshot.
2. Wait for 2 seconds (almost all symbols will have new ticks within 2 seconds).
3. Create the second screenshot.
4. Compare both screenshots; they should have some detected pixel differences.

Additional information:

1. The screenshots exclude expected live update elements, such as contract price and timestamp in the footer.
2. If the chart is not loaded at all or the feed is stopped, both screenshots will be identical. Thus, the mismatched pixel count will be 0 (this has been tested in QA10 by stopping the feed).

ClickUp card: To be attached later.

2024-02-20 09:06 UTC, markodonnell-deriv requested changes
Some minor comments

2024-02-20 09:06 UTC, markodonnell-deriv commented on cypress/e2e/wip/dtrader/chartStreaming.cy.js
> +        cy.c_visitResponsive
This line should error, and probably was a mistake as it's in the befreEach?

2024-02-22 02:08 UTC, meeyun-deriv commented on cypress/e2e/wip/dtrader/chartStreaming.cy.js
> +describe('QATEST-6247 - Verify if chart streaming is working with feeds', () => {
here is the click up task https://app.clickup.com/t/20696747/QATEST-6247

2024-02-22 02:17 UTC, meeyun-deriv commented on cypress/e2e/wip/dtrader/chartStreaming.cy.js
> +        cy.c_visitResponsive
thanks @markodonnell-deriv , you are right, it shouldn't be there. I have removed it.

2024-02-22 08:56 UTC, markodonnell-deriv approved these changes
Looks good

2024-02-22 08:56 UTC, merged