Afsaneh/add mt5 account
deriv-com/e2e-deriv-app pull request #92
Opened 2024-02-20 05:35 UTC by afsaneh-rezaeinejad-deriv

2024-02-20 11:33 UTC, markodonnell-deriv requested changes
The standard at the moment is to leave out ; 
![image](https://github.com/deriv-com/e2e-deriv-app/assets/144238191/e545aa96-5d26-48e4-9e4b-70bf2a2a2a3d)

2024-02-21 08:28 UTC, markodonnell-deriv approved these changes
Looks good

2024-02-21 08:30 UTC, markodonnell-deriv requested changes
Do we ned the wait?

2024-02-21 08:30 UTC, markodonnell-deriv commented on cypress/support/e2e.js
> +  cy.wait(3000)
Is this necessary?

2024-02-21 10:31 UTC, meeyun-deriv approved these changes
LGTM

2024-02-26 01:38 UTC, meeyun-deriv approved these changes
LGTM

2024-02-26 09:58 UTC, markodonnell-deriv approved these changes
Looks good

2024-02-26 10:34 UTC, merged