Indu/trah 2802
deriv-com/e2e-deriv-app pull request #94
Opened 2024-02-21 07:55 UTC by indulekha-deriv

https://app.clickup.com/t/20696747/TRAH-2802 and refactoring of CR signup

2024-02-21 08:48 UTC, markodonnell-deriv approved these changes
Looks good

2024-02-21 10:35 UTC, meeyun-deriv requested changes

2024-02-21 10:35 UTC, meeyun-deriv commented on cypress/e2e/full/userSignupROW.cy.js
>  describe('Cypress test for ROW account sign up', () => {
can you please help to add the test scenario custom ID?

2024-02-22 09:42 UTC, meeyun-deriv approved these changes
LGTM

2024-02-22 09:42 UTC, merged