wip
deriv-com/e2e-deriv-app pull request #97
Opened 2024-02-21 10:38 UTC by maliheh-deriv

# Description 
Verify exchange rate for floating rate 

# cards 
https://app.clickup.com/t/20696747/P2PS-2460
https://app.clickup.com/t/20696747/P2PS-2423

2024-02-23 10:45 UTC, markodonnell-deriv requested changes
Custom commands need the need the c_ prefix as per the coding standards here: https://wikijs.deriv.cloud/en/Quality-Assurance/e2e-test-automation

I'm guessing certain commands are embedded within the P2P.js because they are generic (i.e. could be used by other tests) and the commands in createAdBuy.cy.js are specific to createAdBuy tests only?

@bilalmajid-deriv @meeyun-deriv . This is the standard I have proposed in the past, shall we add it to the new doc?

2024-02-26 01:26 UTC, meeyun-deriv reviewed
The test does not delete the created ad after running the test or it did not delete all existing ad before starting the test. So if the current test run failed in creating new ad, will the test pass as the account already has intended ad for validation?

2024-02-26 01:28 UTC, meeyun-deriv requested changes
The test does not delete the created ad after running the test or it did not delete all existing ad before starting the test. So if the current test run failed in creating new ad, will the test pass as the account already has intended ad for validation?

2024-02-26 01:28 UTC, meeyun-deriv commented on cypress/e2e/wip/P2P/createAdBuy.cy.js
> +let ratecalculation
follow camelCase

2024-02-26 06:04 UTC, maliheh-deriv commented on cypress/e2e/wip/P2P/createAdBuy.cy.js
> +let ratecalculation
Regarding delete all ads , we have this [subtask](https://app.clickup.com/t/20696747/P2PS-2473) which I will be start working on it in another PR. they are all part of parent [card](https://app.clickup.com/t/20696747/P2PS-2423)

2024-02-28 09:33 UTC, meeyun-deriv approved these changes
LGTM

2024-03-07 09:32 UTC, bilalmajid-deriv requested changes
Changes suggested.

Question:
As per standard decided commands are only going to be used if the code is redundant  and can be used in multiple test files are all these commands required?

2024-03-07 09:32 UTC, bilalmajid-deriv commented on cypress/e2e/wip/P2P/createAdBuy.cy.js
> +    cy.c_ClickMyAdTab()
update to c_clickMyAdTab() to follow format cy.c_camelCase

2024-03-07 09:32 UTC, bilalmajid-deriv commented on cypress/e2e/wip/P2P/createAdBuy.cy.js
> +import { } from '../../../support/p2p'
can remove if not to be used

2024-03-07 09:32 UTC, bilalmajid-deriv commented on cypress/support/p2p.js
> +      cy.verifyExchangeRate
cy.verifyExchange needs to be updated to cy.c_verifyExchangeRate()

2024-03-07 09:32 UTC, bilalmajid-deriv commented on cypress/support/p2p.js
> +  // cy.xpath('//*[@id=900]').click()
please remove commented code

2024-03-07 09:32 UTC, bilalmajid-deriv commented on cypress/support/p2p.js
> +  cy.get('.notification__close-button').should("be.visible").click()
we have a custom command for this to close notification headers as c_closeNotificationHeader() which can be reused

2024-03-07 09:32 UTC, bilalmajid-deriv commented on cypress/support/p2p.js
> +})
we have two custom commands for this as well 

cy.c_navigateToDerivP2P()
cy.c_closeSafetyInstructions()

2024-03-07 09:32 UTC, bilalmajid-deriv commented on cypress/support/p2p.js
> +  // cy.findByText("If the ad doesn't receive an order for 3 days, it will be deactivated.").should("be.visible")
comment can be removed if not needed.

2024-03-07 09:52 UTC, maliheh-deriv commented on cypress/e2e/wip/P2P/createAdBuy.cy.js
> +import { } from '../../../support/p2p'
All functions defined in the support/p2p and only called in here.

2024-03-07 11:24 UTC, markodonnell-deriv approved these changes
Looks good

2024-03-07 11:29 UTC, bilalmajid-deriv requested changes

2024-03-07 11:29 UTC, bilalmajid-deriv commented on cypress/support/p2p.js
> +    // else  {
sorry to have missed this could you please remove these comments on line 11 and 16 as well

2024-03-08 00:59 UTC, maliheh-deriv commented
Next we will have createBuyAd for `fix rate`. That test will reuse these commands.

2024-03-08 02:33 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-11 06:36 UTC, merged